### ISSUE TITLE
[Help Required] Moving to Managed Identity for Azure Resource Authentication

### ISSUE THREAD

**Issue by animeshj9** [microsoft/chat-copilot#1009]
Hello. I am trying to move to use managed identity instead of apikey based authentication for azure services the chat copilot interacts with. I have been able to move Cosmos & Azure OpenAI successfully, but am having trouble figuring out how to move the AzureAISearch config from API Key based auth to Managed Identity / Token Credential based. 

Any help would be appreciated. Thanks!

**Comment by glahaye** [comment]
This is something we are interested in too.

The following could be useful:
https://learn.microsoft.com/en-us/azure/search/search-howto-managed-identities-data-sources?tabs=portal-sys%2Cportal-user

If this proves too hard, you could use Azure Key Vault instead as AKV does support managed identities.

Also, if you have made changes to support Cosmos and AOAI with managed identities, please feel free to create a PR to incorporate those changes in the repo!!!

**Comment by dluc** [comment]
@animeshj9 in the app config file, for services used by KM you can set `Auth` to `AzureIdentity`
