### ISSUE TITLE
Deploy to Azure Button

### ISSUE THREAD

**Issue by eugyev** [microsoft/chat-copilot#105]
**Describe the bug**
clicking deploy to azure fails in deploy section.  screenshot below. 

<img width="1490" alt="image" src="https://github.com/microsoft/chat-copilot/assets/5740366/3aa730aa-c285-4ef0-8261-adb374faf8c2">

There was an error downloading the template from URI 'https://raw.githubusercontent.com/microsoft/copilot-chat/main/deploy/main.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below.

**Comment by alliscode** [comment]
@eugyev Thank you for bringing this to our attention! The broken links have been fixed, please let us know if you see any more issues :)
