### ISSUE TITLE
Chat Copilot | csv xlsx file type not supported

### ISSUE THREAD

**Issue by vinaypadki** [microsoft/chat-copilot#1079]
Hello Team,
Recently i'm facing an issue with few file types (csv, xlsx) not supported by Chat Copilot and getting below error.
Where as pdf file type is working fine.

Failed to upload document(s). Details: Error: 400: Bad RequestUnsupported file type: .csv
Failed to upload document(s). Details: Error: 400: Bad RequestUnsupported file type: .xlsx_

We are using the latest version of Chat Copilot. Could anyone please suggest any changes required in ChatCopilot.

Thank you

Regards
Vinay

**Comment by glahaye** [comment]
Those file types are not directly supported by Chat Copilot.

You could upload the contents of your files as text.

If you need something more refined than that, you would either have to use the Copilot provided by Excel, or write some new code for Chat Copilot.

**Comment by vinaypadki** [comment]
> Those file types are not directly supported by Chat Copilot.
> 
> You could upload the contents of your files as text.
> 
> If you need something more refined than that, you would either have to use the Copilot provided by Excel, or write some new code for Chat Copilot.

Thanks for your reply, As per this link https://learn.microsoft.com/en-us/microsoft-copilot-service/content-sources-files , it suppose support specified file types, not sure in our case why it is not working.

**Comment by glahaye** [comment]
> Thanks for your reply, As per this link https://learn.microsoft.com/en-us/microsoft-copilot-service/content-sources-files , it suppose support specified file types, not sure in our case why it is not working.

The link you are referring to is for the Microsoft Copilot Service, not Chat Copilot.

That's what I meant when I said that you could use Microsoft Copilot or the copilot built in Excel to parse those files.

Chat Copilot, aside from having originally written by Microsoft as a demo for the Semantic Kernel library has nothing to do with Microsoft Copilot.

**Comment by vinaypadki** [comment]
> > Thanks for your reply, As per this link https://learn.microsoft.com/en-us/microsoft-copilot-service/content-sources-files , it suppose support specified file types, not sure in our case why it is not working.
> 
> The link you are referring to is for the Microsoft Copilot Service, not Chat Copilot.
> 
> That's what I meant when I said that you could use Microsoft Copilot or the copilot built in Excel to parse those files.
> 
> Chat Copilot, aside from having originally written by Microsoft as a demo for the Semantic Kernel library has nothing to do with Microsoft Copilot.

Thanks for your comment, Yes we are using Microsoft Copilot Service, from this repository we deployed.
i'm aware of other method (copilot built in Excel), however all our users using Microsoft Copilot Service and want to use supported file types. I'm not sure  in this case, whom we need to raise for this issue.

**Comment by glahaye** [comment]
Which service are you using? Copilot for Microsoft 365?

**Comment by vinaypadki** [comment]
We deployed from this repo (https://github.com/microsoft/chat-copilot?tab=readme-ov-file) and using the same.

**Comment by glahaye** [comment]
@vinaypadki Then you are NOT using the Microsoft Service Copilot.  Chat Copilot doesn't make use of it and is merely an unsupported demo app showcasing technology from 2023. It does not and never will support CSV and XLSX files.

What you want to use instead if the following:
https://www.microsoft.com/en-us/microsoft-copilot/microsoft-copilot-for-service

**Comment by vinaypadki** [comment]
Thanks @glahaye for your response. Is their any article which tells details like which all file type supports Azure Microsoft Chat-Copilot service.

**Comment by glahaye** [comment]
@vinaypadki In the following front-end file:
https://github.com/microsoft/chat-copilot/blob/24f5e76cd3d781329a18f45055fe6b0f635fe4c4/webapp/src/components/FileUploader.tsx#L49

You can see that only .pdf, .txt, .jpg, .png, and .tiff files are supported.

PDF files have their text extracted and parsed as text.

For JPG, PNG, and TIFF files, OCR is done on images and the extracted text parsed.
