### ISSUE TITLE
 Microsoft.SemanticKernel.KernelException: GetUserIntentAsync failed.  ---> Microsoft.SemanticKernel.HttpOperationException: Resource not found   Status: 404 (Resource Not Found)

### ISSUE THREAD

**Issue by eric80116** [microsoft/chat-copilot#1105]
Hi,

I have configured the information of AzureOpenAIText and AzureOpenAIEmbedding both in appsettings.json and appsettings.Development.json. But still got the error mesage when sending chat message.
Any suggestion where I could check and find out more detail?
![capture_240808_180720](https://github.com/user-attachments/assets/706f456a-a983-4786-b092-1231a4a504a6)
![capture_240808_180403](https://github.com/user-attachments/assets/f098acb8-8387-4ddf-80e7-668afb468b3c)
![capture_240808_180500](https://github.com/user-attachments/assets/d1ab18cf-a2fd-4272-a294-99b38da73bae)

**Comment by rogeriorfp** [comment]
> Hi,
> 
> I have configured the information of AzureOpenAIText and AzureOpenAIEmbedding both in appsettings.json and appsettings.Development.json. But still got the error mesage when sending chat message. Any suggestion where I could check and find out more detail? ![capture_240808_180720](https://private-user-images.githubusercontent.com/28819360/356177202-706f456a-a983-4786-b092-1231a4a504a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMTA5NjEsIm5iZiI6MTcyMzIxMDY2MSwicGF0aCI6Ii8yODgxOTM2MC8zNTYxNzcyMDItNzA2ZjQ1NmEtYTk4My00Nzg2LWIwOTItMTIzMWE0YTUwNGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDEzMzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwOGNmMWNjOTQ3N2FmZDQwNWVhN2U3NDkzMmE1MTc3NjY0NjM5MTY0NGE0M2NiMTA0OGQ3MGQzYjIzMTI0Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0SJdEWqbga03LkGFN2ROc64audEIYybb9omTdcd1-DI) ![capture_240808_180403](https://private-user-images.githubusercontent.com/28819360/356177282-f098acb8-8387-4ddf-80e7-668afb468b3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMTA5NjEsIm5iZiI6MTcyMzIxMDY2MSwicGF0aCI6Ii8yODgxOTM2MC8zNTYxNzcyODItZjA5OGFjYjgtODM4Ny00ZGRmLTgwZTctNjY4YWZiNDY4YjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDEzMzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YjQxYjhkZGNjZjU4MzQyMThhZTZhOWY5NzA3ZDFhNmQ4Mzk5ZmNmZWFjYmFiN2Y1M2RhMGE4MWMzZjI0YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hQBe5-qS3IOsM0Ga8fPmOyNhkww1p69lkSd2c49HsqI) ![capture_240808_180500](https://private-user-images.githubusercontent.com/28819360/356177304-d1ab18cf-a2fd-4272-a294-99b38da73bae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMTA5NjEsIm5iZiI6MTcyMzIxMDY2MSwicGF0aCI6Ii8yODgxOTM2MC8zNTYxNzczMDQtZDFhYjE4Y2YtYTJmZC00MjcyLWEyOTQtOTliMzhkYTczYmFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDEzMzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNjRkYTRkMzFmMjAwYjZhMjM2ZDkyYTk2MTg3MWIxNzllMGZhZjUxYjY4OWMyMTAxNzU5YTdjNmZlY2Q1ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GqR6x71FZG8gFush26Sf_BvD70_Av6plercOfT6liko)

I would check api-version query parameter

**Comment by glahaye** [comment]
@eric80116 Have you created entries named gpt-4o and text-embedding-ada-002 in you Azure Open AI account?

**Comment by eric80116** [comment]
@rogeriorfp thanks for suggestion, but i have tried to call the models by postman with the same endpoint with the same api-version param, I can get the response successfully. 
![capture_240813_092747](https://github.com/user-attachments/assets/f9e97907-324b-4569-9667-0f10551b0e48)
![capture_240813_092842](https://github.com/user-attachments/assets/71bb3f2a-e1c2-430d-baa4-f7ec40a90e6b)

**Comment by eric80116** [comment]
> @eric80116 Have you created entries named gpt-4o and text-embedding-ada-002 in you Azure Open AI account?

Do you mean the deployment name? I used the default name for deployment which are gpt-4o and text-embedding-ada-002. If it is different with the entries name you mention, could you give me more detail?
![capture_240813_093242](https://github.com/user-attachments/assets/3bdc70ca-0b38-4fc4-8c40-5cbcffdcf645)

**Comment by glahaye** [comment]
@eric80116 That's what I meant. And what you have looks correct.

I checked your error message again and I see it mentions something about an apim-request-id... Is any part of your solution behind Azure API Management?  Maybe a misconfigured APIM could be causing the problem?

**Comment by eric80116** [comment]
@glahaye I tried to remove my API Key which hard coded in the appsettings.json and appsettings.Development.json to make it read from the dotnet secret directly, then it works now. Thanks for help.
