### ISSUE TITLE
GitHub Plugin not working in Chat-Copilot App

### ISSUE THREAD

**Issue by dipteshbosedxc** [microsoft/chat-copilot#1147]
**Describe the bug**
Unable to generate bot response. Details: Error: 500: System.IO.FileNotFoundException: Invalid URI. The specified path 'C:\Users\x-nnn\Documents\GitHub\chat-copilot\webapi\bin\Debug\net8.0\Plugins\GitHubPlugin/openapi.json' does not exist. at Microsoft.SemanticKernel.Plugins.OpenApi.DocumentLoader.LoadDocumentFromFilePathAsync(String filePath, ILogger logger, CancellationToken cancellationToken) at Microsoft.SemanticKernel.Plugins.OpenApi.OpenApiKernelExtensions.CreatePluginFromOpenApiAsync(Kernel kernel, String pluginName, String filePath, OpenApiFunctionExecutionParameters executionParameters, CancellationToken cancellationToken) at Microsoft.SemanticKernel.Plugins.OpenApi.OpenApiKernelExtensions.ImportPluginFromOpenApiAsync(Kernel kernel, String pluginName, String filePath, OpenApiFunctionExecutionParameters executionParameters, CancellationToken cancellationToken) at CopilotChat.WebApi.Controllers.ChatController.RegisterGithubPlugin(Kernel kernel, String GithubAu...Unable to generate bot response. Details: Error: 500: System.IO.FileNotFoundException: Invalid URI. The specified path 'C:\Users\x-nnn\Documents\GitHub\chat-copilot\webapi\bin\Debug\net8.0\Plugins\GitHubPlugin/openapi.json' does not exist. at Microsoft.SemanticKernel.Plugins.OpenApi.DocumentLoader.LoadDocumentFromFilePathAsync(String filePath, ILogger logger, CancellationToken cancellationToken) at Microsoft.SemanticKernel.Plugins.OpenApi.OpenApiKernelExtensions.CreatePluginFromOpenApiAsync(Kernel kernel, String pluginName, String filePath, OpenApiFunctionExecutionParameters executionParameters, CancellationToken cancellationToken) at Microsoft.SemanticKernel.Plugins.OpenApi.OpenApiKernelExtensions.ImportPluginFromOpenApiAsync(Kernel kernel, String pluginName, String filePath, OpenApiFunctionExecutionParameters executionParameters, CancellationToken cancellationToken) at CopilotChat.WebApi.Controllers.ChatController.RegisterGithubPlugin(Kernel kernel, String GithubAu...

**To Reproduce**
1. Go to 'Chat-Copilot App'
2. Click on 'Plugin'
3. Scroll down to 'Github"...Configure itwith trhe required details
4. When trying to chat with the plugin ....See error mentioned above

**Expected behavior**
Should return the OPEN PR IDs

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: Main Branch Repo

**Additional context**

**Comment by dluc** [comment]
Fixed :-)
