### ISSUE TITLE
Python array indices using square brackets are omitted from code snippets produced by Copilot Chat in Edge

### ISSUE THREAD

**Issue by klaas-koster** [microsoft/chat-copilot#1173]
**Describe the bug**
Copilot accessed through Edge will consistently omit array inices in square brackets when asking for Python coding help

**To Reproduce**
1) Prompt Copilot as follows: for a 3D numpy array, how can i print the length of the second axis?

**Expected behavior**
Any answer should include [1], but instead the array index is completely omitted

**Screenshots**
![Image](https://github.com/user-attachments/assets/e333566e-dce5-4ddf-8062-f0d0eff3f0b0)

**Platform**
 - OS: Windows
 - IDE: Edge
 - Language: Python
 - Source: 

**Additional context**
None

**Comment by glahaye** [comment]
This project is NOT for Copilot, but rather for Chat Copilot.
