### ISSUE TITLE
upload attached error

### ISSUE THREAD

**Issue by JasonRinnki** [microsoft/chat-copilot#137]
![image](https://github.com/microsoft/chat-copilot/assets/135125734/979aeca6-8c25-4cf4-8bc4-fdf5a0d729e9)
Please refer to the attached image for the error encountered during file upload.

**Comment by dehoward** [comment]
hi @JasonRinnki, thanks for submitting this issue!

do you see any errors when sending a regular message to the bot?
I'm able to reproduce this when my AzureOpenAI instance key is invalid, which also prevents sending chats.

if that is working fine, I can provide some debugging guidance to help track down the error.

**Comment by crickman** [comment]
If targeting Azure CognativeSearch, this can also occur if that maximum number of indexes is reached.   Is there any failure/exception in the log of the webapi?

**Comment by JasonRinnki** [comment]
If the size of the file I upload is less than 2KB, it can be uploaded successfully. However, if it exceeds this size, an error will be thrown. Additionally, I would like to ask if deploying the vector database locally would help solve this problem.

**Comment by crickman** [comment]
Which vector database are you using?  Are you able to capture any exception details from the API for the failure case (> 2KB)?

**Comment by crickman** [comment]
There was an intermittent outage with embeddings last week.  This may have be involved.
