### ISSUE TITLE
Disable Application Insights Telemetry logs

### ISSUE THREAD

**Issue by victor-v-rad** [microsoft/chat-copilot#148]
**Describe the bug**
Application Insights Telemetry create quite verbose logs and it does not filter "Authorization: Bearer" headers. I tried to disable it but I still see it in my logs:

**To Reproduce**
1. Setup and run Copilot using Linux/macOS instruction https://github.com/microsoft/chat-copilot#linuxmacos
2. Write and submit any prompt in UI http://localhost:3000/ 
3. See Debug Console in VS Code 

**Expected behavior**
No logs from Application Insights Telemetry

**Screenshots**
My appsettings.json
<img width="1000" alt="image" src="https://github.com/microsoft/chat-copilot/assets/106504/67ed9d45-0005-40fa-92a3-3e6a6f6bc7f9">
 
My launch.json:
<img width="1013" alt="image" src="https://github.com/microsoft/chat-copilot/assets/106504/22500c7a-4861-4389-8fda-3d9d8c20da82">

**Platform**
 - OS: Mac
 - IDE: VS Code
 - Language: C#
 - Source: main branch of repository

**Comment by crickman** [comment]
Thank you for this feedback.  I'll repeat your steps and explore what is occurring here.

**Comment by crickman** [comment]
Can you please try changing your configuration of AZURE_TELEMETRY_DISABLED to `1` or `true` (not a string value: `"1"`).

https://learn.microsoft.com/en-us/dotnet/api/azure.core.diagnosticsoptions.istelemetryenabled?view=azure-dotnet.

Please let me know if this affected the behavior you are seeing, or not.

**Comment by victor-v-rad** [comment]
Thank you @crickman  for suggesting help. 
The value seems expected to be a string and VS Code cannot start the app
<img width="537" alt="image" src="https://github.com/microsoft/chat-copilot/assets/106504/d3a894ef-b0c7-4461-8034-5187f5b5478d">

Did you able to reproduce the issue?

**Comment by crickman** [comment]
I did reproduce and believed able to eliminate the message by changing the type, but on revisiting...there must've been an error in my process.  Looking deeper, I'm finding this in `Program.cs` of `webapi`:

```
#if DEBUG
        TelemetryDebugWriter.IsTracingDisabled = false;
#endif
```
When I remove this, the debug information is not present and this may be overriding configuration.  Let me find out from the team what the thinking behind this was.  I'll follow-up.

**Comment by victor-v-rad** [comment]
`TelemetryDebugWriter.IsTracingDisabled = Debugger.IsAttached;` works for me. Thank you!

**Comment by crickman** [comment]
https://github.com/microsoft/chat-copilot/pull/178
