### ISSUE TITLE
Custom Plugin in Chat-Copilot Fetching Outdated Data Instead of Up-to-Date Results

### ISSUE THREAD

**Issue by PBitukunti** [microsoft/chat-copilot#151]
**Describe the bug**
When enabling my custom plugin through Chat-Copilot and running it, the plugin doesn't provide up-to-date results. Specifically, I've created a custom plugin named "Grocery App Plugin," allowing users to add, list, and remove items. While using Swagger to add items to the list, I can retrieve the complete list of items. However, when running the same plugin through Chat-Copilot, it seems to fetch outdated data, appearing as if the planner is providing historical details. I'm utilizing the "Action" Planner /"Sequential" Planner with the gpt-35-turbo model.

**To Reproduce**
1.Enable custom plugin -"Grocery App Plugin"
2.List the grocery items using "Grocery App Plugin."
3.Attempt to add an item using the plugin or Swagger
4.Run the plugin to list the items.
5.Compare the listed items with the actual up-to-date list.

**Expected behavior**
I expected the plugin to fetch and display the most recent data when using Chat-Copilot, similar to the behavior when interacting with Swagger directly. This would ensure that users receive accurate and current information from the plugin.

**Screenshots**
Please find the screenshots of the outdated results from Chat-Copilot and the expected up-to-date results from Swagger.

![ChatCopilot-CustomPlugin-ErrorScreenshot](https://github.com/microsoft/chat-copilot/assets/96146927/64e1a754-c4b7-4b31-b949-b045c820067b)
![FastAPI-Swagger UI-Data Response](https://github.com/microsoft/chat-copilot/assets/96146927/5d3017d6-b7f1-42bf-be74-294df960d236)

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language:  C#, Python
 - Source: Main branch of repository: https://github.com/microsoft/chat-copilot.git

**Additional context**
I noticed that this issue is specific to Chat-Copilot's interaction with my custom plugin. Swagger integration seems to work correctly and provides real-time updates. This context could potentially help in identifying whether the problem lies within my plugin's implementation or Chat-Copilot's integration with both "Action"/ "Sequential" Planner along with the gpt-35-turbo model.

**Comment by crickman** [comment]
Thank you for reporting this.  I'm happy to review chat-copilot's interaction with custom-plug-ins for result handling and ifadditional logging might be helpful.

I'm wondering if the model is cosolidating `test`, `Test`, and `Test5` as a single logical item: `Test`.  Is it possible to provide the prompt metrics (click the "information" icon in the chat bubble) and the short/long term memory values from the persona tab.  This may help determine if actual values are provided and if the model then consolidates.

![image](https://github.com/microsoft/chat-copilot/assets/66376200/8b83d3be-28f6-469e-8d27-dd9bf3b2ac5c)

Another test might be to add distincts item such as `Cheese`, `Celery`, `Catfood`, etc...

I look forward to hearing back from you and will also investigate on this end.

**Comment by PBitukunti** [comment]
Thank you for your prompt response. I appreciate your suggestion to explore whether the model is consolidating similar terms and your interest in examining the prompt metrics and memory values.

I have conducted the tests as you've suggested. I created distinct items such as 'Cheese,' 'Celery,' and other 'Test' to ensure the items are unique. Despite this, the issue persists, and the plugin still fetches outdated data when interacting with Chat-Copilot.

I have attached the screenshots showing the error. The first screenshot demonstrates the outdated results from Chat-Copilot, while the second screenshot displays the prompt metrics and expected up-to-date results from Swagger for comparison. The third and fourth screenshots showcases the additional tests.

![ChatCopilot-CustomPlugin-ErrorScreenshot1](https://github.com/microsoft/chat-copilot/assets/96146927/574a3fd5-3808-4181-b478-ca541848e18f)
![Persona-FastAPI-Screenshot](https://github.com/microsoft/chat-copilot/assets/96146927/0a8e1c61-7821-4e6f-89a0-e80466d599e1)
![OutdatedResults](https://github.com/microsoft/chat-copilot/assets/96146927/21efc60f-6eb8-4c90-a136-80e95cde400e)
![AddNewItemsAPI](https://github.com/microsoft/chat-copilot/assets/96146927/23138ffd-d437-43f5-b0c7-045964ecdee7)


In addition, I've captured the short/long term memory values from the persona tab. I hope these details will be helpful in your investigation.
![Persona-MemoryErrorScreenshot](https://github.com/microsoft/chat-copilot/assets/96146927/9b61e42e-5191-415d-8c98-4b04fb94ed8d)


Please let me know if there's any other information or steps you'd like me to take to assist in resolving this issue. Your expertise is greatly valued, and I'm looking forward to your insights.

Thank you once again for your assistance.

**Comment by crickman** [comment]
Wonderful, thank you for these additional data-points.  I aim to complete my analysis today.

**Comment by crickman** [comment]
I was able to reproduce your report with a function that adds a new guid to the list upon each invocation:

![image](https://github.com/microsoft/chat-copilot/assets/66376200/02206346-e7a3-47cb-8678-20c502253228)
![image](https://github.com/microsoft/chat-copilot/assets/66376200/b48062f7-d867-4e6f-a754-b852e4465cb7)

In my case, the "cached" value is being derived from the chat history.  I suspect something similiar is occuring for you while the function result is being captured as expected.  I am a little uncertain as to which prompt details you've  shared...is that the planner prompt?  I'd the prompt related to the plan/function/plug-in execution to contain the function results.

In anycase, let me raise this to the team for ideas.
