### ISSUE TITLE
Failed: memory not established

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft/chat-copilot#164]
In the documents tab I upload a PDF file and shows in the list.
But on the Chat tab, there is a message from the bot with the file name
**To Reproduce**
1. Go to 'Documents'
2. Click on 'Upload'
3. Upload PDF file
4. Go to 'Chat'
5. Ask "write a summary of the file"
6. Bot answers: I apologize, but I don't have access to the content of the file you mentioned. Is there anything else I can help you with?

**Expected behavior**
The file should be in the list and the chat should suggest what to do with it.
I should be able to ask about the file. No?

**Screenshots**

![image](https://github.com/microsoft/chat-copilot/assets/5054931/70fe8167-463d-4ee3-97be-03b7a3baf978)

**Platform**
 - OS: Windows
 - IDE: N/A

Help fixing it please
Thank you

**Comment by crickman** [comment]
Thank you, I will explore these steps and inverstigate the behavior you've identified.

**Comment by crickman** [comment]
Two things going on here:

1. Copilot does not have a semantic understanding of the imported files as physical artifacts. (The files listed on the *Documents* are retreived from application storage. not semantic memory/vector db.)  In short, refering to "the file" is ambiguous for the model...but the memory was established.  As a test, please ask a question that pertains to some specific document content.

Examining the chat history in the prompt reveals one possible factor (empty chat entry):

![image](https://github.com/microsoft/chat-copilot/assets/66376200/6b7d7005-d4bf-4e4b-9767-1a163213ab83)
![image](https://github.com/microsoft/chat-copilot/assets/66376200/2db716b5-ba5c-464c-8f5a-12556ce324e9)

We are currently in the processing of shifting our memory architecture and improving functionality in this area might be best addressed within that that scope (as opposed to modifying the current code).  Stay posted!

2. Requesting the summary of such a large document (stored as many chunks in the vectordb) means that no single prompt will be able to accesss the all the chunks for summarization.  A planner _may_ be able to navigate this objective across multiple steps...unclear.  But if the document itself contains summary sections, then copilot can draw on those summaries.  In short, your satisfaction with the response to summarize may be dependent on the level of detail or completeness expected.

Please let me know if you have any issues or follow-up questions.  In the meantime, I'll raise this so the experience can be improved as part of the new memory architecture.

**Comment by Ofer-Gal** [comment]
I notice that .TXT files are processed fine. only .PDF are an issue.
When will office files be readable for summarization and such?

**Comment by crickman** [comment]
I'm unable to differentiate behavior for .txt and .pdf

We are currently working on a new memory archicture that does support word documents and is extensbile to many document types.
