### ISSUE TITLE
Use PostgresSQL as MemoryStore

### ISSUE THREAD

**Issue by kbeaugrand** [microsoft/chat-copilot#166]
Current Memory store options are: 
- volatile
- qdrant
- azure cognitive search
- chroma

While deploying to Azure, the only PaaS available directly on Azure is Azure Cognitive Search. 
However this is limited to 50 indexes, that might limit the usage when adding more users to the chat...

I'ld like to add CosmosDB as vector database (using PostgreSQL connector).

**Comment by kbeaugrand** [comment]
If this seems interesting, I'll provide a PR for that point.

**Comment by crickman** [comment]
Thank you for this proposal. 

When you say you want to use CosmosDB as a vector database using PostgreSQL connector, can you confirm that you are referring to [https://learn.microsoft.com/en-us/azure/cosmos-db/postgresql/introduction](https://learn.microsoft.com/en-us/azure/cosmos-db/postgresql/introduction)

**Comment by kbeaugrand** [comment]
> Thank you for this proposal and offer.
> 
> When you say you want to use CosmosDB as a vector database using PostgreSQL connector, can you confirm that you are referring to [Azure Cosmos DB for PostgreSQL](https://learn.microsoft.com/en-us/azure/cosmos-db/postgresql/introduction).
> 
> I believe Semantic Kerenal already has separate connectors for CosmsoDB and PostgreSQL. Would your proposal require a new connector?

Yes, I refer to Azure Cosmos DB for PostgreSQL. 

Semantic Kernel offers only PostgreSQL connector (which is sufficient to provide both Azure Database for PostgreSQL and Azure Cosmos DB for PostgreSQL).

**Comment by crickman** [comment]
Wonderful.  Thanks for the clear followup and the PR.
