### ISSUE TITLE
Enable Deploy to specify region of Static Web App

### ISSUE THREAD

**Issue by PlagueHO** [microsoft/chat-copilot#17]
- As a: Engineer deploying Chat Copilot
- I want: To the Static Web App resource to be deployed into the same region as all the other resources.
- So that: I can reduce latency to load the static web app.

The [Bicep defaults to deploying the Static Web App](https://github.com/microsoft/chat-copilot/blob/main/deploy/main.bicep#L65) to `westus2` and neither the `deploy-azure.sh` or `deploy-azure.ps1` pass this parameter in during deployment. Therefore, it will always deploy to `westus2` regardless.

Possible solutions:
1. Default the deployment location of the Static Web App to be the same as the `location` if not specified.
2. Add a parameter to `deploy-azure.ps1` and `deploy-azure.sh` to allow setting this value.
3. Remove the parameter entirely and always deploy the Static Web App to the same location as the other resources. 

I'm happy to submit a PR to resolve this if one of the options is preferrable. It is a minor issue, but I prefer all my resources in the same region if possible.

**Comment by glahaye** [comment]
In an ideal world, putting all the resources in the same region would always be possible. However, because not all services are available and have available quota in all regions, we found it difficult to do so.

But, I agree, always putting the Static Web App on westus2 is not the optimal workaround to that problem.

Given the availability issues mentioned above, the second solution you propose is likely the best.

If you can submit a PR for this, we'll make sure to merge it promptly.

**Comment by PlagueHO** [comment]
@glahaye, 100%. I'll add a parameter into `deploy-azure.ps1`, `deploy-azure.sh` to be passed through into the Bicep/ARM templates.

If it is possible to override the location of one of the resources (Static Web Apps), users might expect this to be possible for other resources. So, an optional enhancement might be to allow the user to pass their own params.json file through to the scripts. But for my needs, I only need everything in a single region - so I won't worry about this.

**Comment by matthewbolanos** [comment]
@PlagueHO, are you still planning on submitting a PR to this issue?

**Comment by PlagueHO** [comment]
Hi @matthewbolanos - thanks for the reminder. Yes, working on it now.

**Comment by glahaye** [comment]
Added!  Thanks, @PlagueHO
