### ISSUE TITLE
Complete enhancement for chat copilot for customer demos

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/chat-copilot#187]
```[tasklist]
### Tasks
```

**Comment by teresaqhoang** [comment]
@matthewbolanos I linked all the relevant PRs! 

We also had the work we did for the CIBC customer loan demo with Nilesh: 
- branch: [811_customer_loan](https://github.com/lemillermicrosoft/semantic-kernel/tree/811_customer_loan)
- Notes in our Lightspeed Loop > Demos > Saved Plans in Copilot Chat
