### ISSUE TITLE
Chat UI in Blazor

### ISSUE THREAD

**Issue by endintiers** [microsoft/chat-copilot#197]
We use Blazor Hybrid for everything - Web, Windows, Mac, Android (via MAUI). Write once, run everywhere.
I think it would be a lot more useful to have a Blazor Hybrid UI for this - and in the Same Solution as the Web API instead of React/TS.

**Comment by crickman** [comment]
Thank you for this suggestion.  I believe I remember you sharing about Blazor during office hours several weeks ago.  That was the first I'd heard of Blazor and I did take a quick look.

One factor for choosing React/Type-Script is that it is familiar to and well-supported within Microsoft and the community.

While re-writing the chat application would be quite a pivot, I am curious to hear from the team on their thoughts and experience regarding Blazor.

**Comment by crickman** [comment]
Here's one conversation on the matter:

https://learn.microsoft.com/en-us/answers/questions/989481/blazor-vs-typescript-angular

**Comment by win4r** [comment]
We use Blazor Hybrid for everything - Web, Windows, Mac, Android (via MAUI). Write once, run everywhere.
I think it would be a lot more useful to have a Blazor Hybrid UI for this - and in the Same Solution as the Web API instead of React/TS.

**Comment by endintiers** [comment]
Heh. It's a 'Religious' question. But to quote some guy from Reddit: 
"using Blazor is so much easier / straight forward it almost feels like cheating. Maybe for a Js dev it would be different, but for me as a backend dev using Blazor is very enjoyable."
Also Blazor is VERY Microsoft.

**Comment by crickman** [comment]
Thanks for the suggestion! We're looking into blazer/maui for app and sample front-ends moving forward, and we're always open to contributions from the community.
