### ISSUE TITLE
Created Chat copilot but don' know how to get to it

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft/chat-copilot#198]
**Describe the bug**

**To Reproduce**
1. Go to 'https://github.com/microsoft/chat-copilot/blob/main/scripts/deploy/README.md#azure-portal'
2. Click on 'Deploy to Azure'
3. Wait for the deployment to be done
4. See the resource group items 

**Expected behavior**
The URL of the static web site https://yellow-rock-07923991e.3.azurestaticapps.net should show the UI.

instead it shows "waiting for your content"

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/5054931/fb6cc9db-645a-45d1-ae59-a630a7f02b87)

**Platform**
 - OS: Windows,
 - IDE: None
 - Language: None

Did I miss something? Something else I need to do?

**Comment by crickman** [comment]
Can you confirm that you've deployed the static potion of the app:

https://github.com/microsoft/chat-copilot/tree/main/scripts/deploy#deploy-frontend-webapp

**Comment by Ofer-Gal** [comment]
The explanation does not include it.
This is so confusing.

**Comment by crickman** [comment]
Agree.  We are working to improve the documentation.   Were you able to access the static content after following these steps?

**Comment by Ofer-Gal** [comment]
Yes Thank you
