### ISSUE TITLE
Cannot import documents into the app - AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'

### ISSUE THREAD

**Issue by ekdnam** [microsoft/chat-copilot#199]
**Describe the bug**

I am trying to import documents into the chat copilot by following the procedure specified in [importdocument/README.md](https://github.com/microsoft/chat-copilot/blob/main/tools/importdocument/README.md).

However, I get the error
```
Error: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: <ID>
Correlation ID: <Corr_ID>
Timestamp: <TIMESTAMP>
Error: Failed to acquire user account.
```
How to resolve?

**To Reproduce**
1. Followed the procedure up until [configure your environment](https://github.com/microsoft/chat-copilot/blob/main/tools/importdocument/README.md#configure-your-environment)

**Expected behavior**

No Error

**Screenshots**

**Platform**
 - OS: MacOS
 - IDE: VS Code
 - Language: C#
 - Source: the original code base at [semantic-kernel](https://github.com/microsoft/semantic-kernel/tree/main/samples/apps/copilot-chat-app)

**Additional context**

**Comment by crickman** [comment]
Thank you for reporting this issue.  I will reproduce the process you've reported to analyze what may be occurring.

Can you please assist by providing a couple additional details:

1. Are you running chat-copilot locally (dev-box) or hosted?
2. Are you running the importdocument tool locally? (presumably: yes)
3. Are you importing into global or chat memory?
4. Are you able to import a document into chat memory through the web application?

Thank you

**Comment by ekdnam** [comment]
1. locally
2. locally
3. I don't know. Can you please explain more?
4. Can you explain more here as well?

Thanks

**Comment by crickman** [comment]
3. importdocument has an optional parameter to specify chatid, otherwise the documents are imported into "global" memory (available to all chats)
4. Import document via web-app:
![image](https://github.com/microsoft/chat-copilot/assets/66376200/f751c861-a524-414d-8ea4-48d1550d29b9)

**Comment by ekdnam** [comment]
Thanks for your reply.

1. Then it means i am importing into the global memory.
2. importing a document into the chat does not work.

-Aditya

**Comment by crickman** [comment]
Can you please provide the exception from the webapi when attempting to upload a  document with the app.  (Both the app and importdocument tool use the webapi).

**Comment by ekdnam** [comment]
1. It now works for uploading a document via the app. I think the behvaiour changed when I shifted to the current repo, rather the old codebase from semantic-kernel.
2. The error trace from running importdocument is
```
Requesting User Account ID...
Error: AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.
Trace ID: d5a5fd8a-d467-4bf7-8943-941e73fa3201
Correlation ID: b9f882f9-9f21-40ac-a65d-56575a0c72e9
Timestamp: 2023-08-21 07:19:20Z
Error: Failed to acquire user account.
```

I believe regarding this problem and https://github.com/microsoft/chat-copilot/issues/212 are related

**Comment by crickman** [comment]
Wonderful, thanks for the update.  I'll focus on #212 at this point.

(FWIW - Another recent post on this tool also: https://github.com/microsoft/chat-copilot/issues/229)

**Comment by crickman** [comment]
Hey, you filed #212...I'll close this out in favor of that.  Thank you.
