### ISSUE TITLE
uploading documents with memory `volatile` and `qdrant` - chatbot cannot answer questions on the document

### ISSUE THREAD

**Issue by ekdnam** [microsoft/chat-copilot#213]
**Describe the bug**
In `./webapi/appsettings.json`, I tried keeping once `MemoryStore.Type` once as`qdrant` and `then volatile` as well. 

I uploaded a document via the UI, but the chatbot cannot answer questions on the document. 

Something like the following (I uploaded the [llama](https://github.com/facebookresearch/llama) README.md)

<img width="1030" alt="Screenshot 2023-08-18 at 7 06 35 PM" src="https://github.com/microsoft/chat-copilot/assets/40426312/242aa537-e459-43a5-840c-3fc81469b82f">

**To Reproduce**
1. follow the procedure to turn on the qdrant vector store

**Expected behavior**

Chatbot can answer questions on the document

**Screenshots**

**Platform**
 - OS: MacOS
 - IDE: Code
 - Language: C#
 - Source: main branch of repository

**Additional context**

**Comment by crickman** [comment]
The "user-intent" included in the prompt info displays this as the intent:

![image](https://github.com/microsoft/chat-copilot/assets/66376200/9de5be33-451c-4dea-a6bd-88e5be2eee66)

This confirms my suspicion that the quesion is just too ambiguous.

When I ask: 

```
Does LLama support fine-tuning large language models?
```

The response includes the document snippet.

![image](https://github.com/microsoft/chat-copilot/assets/66376200/883292fe-8ba2-437f-8a22-6a5a8257ecdc)
![image](https://github.com/microsoft/chat-copilot/assets/66376200/7ec99b06-7c55-4021-b472-1e89052bcc99)

The experience you've reported is not specific to volitile or qdrant memory.

**Comment by AwesomeYuer** [comment]
@crickman I found same issue, have this bug been fixed? or in fixing? thanks
