### ISSUE TITLE
rewrite in .NET MAUI

### ISSUE THREAD

**Issue by win4r** [microsoft/chat-copilot#217]
rewrite in .NET MAUI

**Comment by crickman** [comment]
[Maui](https://learn.microsoft.com/en-us/dotnet/maui/what-is-maui)

Thanks for the suggestion! We're looking into blazer/maui for app and sample front-ends moving forward, and we're always open to contributions from the community.

Duplicate of https://github.com/microsoft/chat-copilot/issues/197
Duplicate of https://github.com/microsoft/chat-copilot/issues/210
