### ISSUE TITLE
Post latest changes, the app breaks if ContentSafety is disabled in appsettings.

### ISSUE THREAD

**Issue by saisescapades** [microsoft/chat-copilot#218]
**Describe the bug**
Object reference error observed in **DocumentImportController.cs**.

**To Reproduce**
- In Copilot API's appsettings.json, set the **ContentSafety** setting's **Enabled** property to **false**
- Launch the application in debugging mode.
- Refresh the copilot UI.
- Navigate to the ContentSafetyStatus method within DocumentImportController.cs.
- Object reference error is thrown on this line: return this._contentSafetyService!.ContentSafetyStatus(this._logger);

**Expected behavior**
This error has cropped up after changes made around Content Safety. Application should work fine even when ContentSafety setting's Enabled property is set to false. Error is not encountered when **ContentSafety** setting's **Enabled** property is set to **true**

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/50072973/c1cda946-4f85-46a8-8099-d8e3b30c2087)

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: main branch of Chat Copilot

**Comment by crickman** [comment]
Thank you for this report.

Is suspect the following might address:

`this._contentSafetyService?.ContentSafetyStatus(this._logger) ?? fase`

I'll repro as PR fix shortly.
