### ISSUE TITLE
Include a setting option in the webapp to select voice input in different languages

### ISSUE THREAD

**Issue by huangchao-shanghai** [microsoft/chat-copilot#220]
Chat Copilot's voice input currently only supports English, and changes can only be made by modifying the code. Is it possible to add a setting option in the web app to choose voice input in other languages, such as Chinese, Japanese, etc.?
![image](https://github.com/microsoft/chat-copilot/assets/3233883/57fbe373-eeb3-4561-aec9-e7fea98caa7d)

**Comment by crickman** [comment]
Great suggestion.  We're always open to contributions from the community.

I'll also follow-up w/ team.

**Comment by crickman** [comment]
I've created this team issue to track the feature support as well as UX treatment: https://github.com/microsoft/chat-copilot/issues/230
