### ISSUE TITLE
Issue with import document tool in Chat Copilot Deployed on Azure:

### ISSUE THREAD

**Issue by huangchao-shanghai** [microsoft/chat-copilot#229]
I have deployed Chat Copilot in Azure. Can the 'import document' tool be used normally? The documentation https://github.com/microsoft/chat-copilot/blob/main/tools/importdocument/README.md only mentions settings for local running mode. I tried the following settings, but it gives an 'Error: unauthorized Unauthorized.
![image](https://github.com/microsoft/chat-copilot/assets/3233883/48700ac1-c20e-4311-9560-776e199e0afb)

<img width="526" alt="image" src="https://github.com/microsoft/chat-copilot/assets/3233883/89bcf1d6-1d37-4534-86f0-465243ec78fc">

<img width="935" alt="image" src="https://github.com/microsoft/chat-copilot/assets/3233883/ba16c658-3d92-439e-90e3-cc9107f74700">

**Comment by crickman** [comment]
Thank you for reporting this issue and the good details.  Your read of the documentation is correct, the tool is for running locally (anywhere) and targets the REST API.  

I'll review the configuration and reply.

I'll also file an issue to update the documentation once we get this sorted for you.

**Comment by crickman** [comment]
@huangchao-shanghai - I've confirmed that the import document tool does not pass the required headers for hosted deployment.  (It only functions locally.)

As a work-around, you could configure a local version of your API to target the same vector-database as your hosted deployment.

I've created a feature request to add this support and update documentation: https://github.com/microsoft/chat-copilot/issues/231

We are currently working to evolve the memory architecture and should be able to consider this feature work as part of that initiative.
