### ISSUE TITLE
Unable to respond normally when using MemoryStore Postgres.

### ISSUE THREAD

**Issue by huangchao-shanghai** [microsoft/chat-copilot#232]
**Describe the bug**
I used ./deploy-azure.ps1 to deploy Chat Copilot to Azure, using the parameter -MemoryStore Postgres. The deployment process went smoothly. However, the following error was reported when I started using it:
`Unable to generate bot response. Details: Error: 400: Bad Request => The CLR type Pgvector.Vector isn't natively supported by Npgsql or your PostgreSQL. To use it with a PostgreSQL composite you need to specify DataTypeName or to map it, please refer to the documentation.`

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/3233883/c96bcda8-e285-4167-b57a-a8a3da701e03)
**Platform**

**Additional context**

**Comment by crickman** [comment]
Thank you for reporting this.  Pgvector is an extension for Postres:  https://github.com/pgvector/pgvector

Did you install and configure this extension?

**Comment by huangchao-shanghai** [comment]
Thank you for the reminder.  I referred to this Microsoft document https://learn.microsoft.com/en-us/azure/cosmos-db/postgresql/howto-use-pgvector and ran the following commands, which seem to have resolved the issue. 

`SELECT CREATE_EXTENSION('vector');`

I suggest that this situation should be mentioned in the deployment documentation.

However, I have encountered a new error, which seems to be the same issue as #215 

`Unable to generate bot response. Details: Error: 400: Bad Request => 42P01: relation "public.ce001975-756a-4dc5-9c09-bdfa5a8146b6-LongTermMemory" does not exist POSITION: 115`
<img width="482" alt="image" src="https://github.com/microsoft/chat-copilot/assets/3233883/5585b937-7a49-4993-b177-a7916e69cc4c">

**Comment by crickman** [comment]
Yes, I think this may be related: https://github.com/microsoft/chat-copilot/issues/215

**Comment by AwesomeYuer** [comment]
> Yes, I think this may be related: #215

same

**Comment by crickman** [comment]
I checked and the main connector readme does have a pointer to the extension info:

https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Connectors/Connectors.Memory.Postgres

I've created an issue to update our own documentation to refer to Postgres (currently only ACS and Qdrant):

https://github.com/microsoft/chat-copilot/issues/237
