### ISSUE TITLE
Question & Feature request: how can I integrate other 3rd party sign-in in Frontend react-app only？such as `Sign In with Google for Web (gsi)` 

### ISSUE THREAD

**Issue by AwesomeYuer** [microsoft/chat-copilot#236]
I have a simple react-app typescript sample by using package `react-gsi` which been integrated `Sign In with Google for Web (gsi)`  as below:

https://github.com/AwesomeYuer/react-gsi.sample.ts

I also made some login UI related modification in 
https://github.com/AwesomeYuer/chat-copilot/blob/mutiple-sign-in/webapp/src/components/views/Login.tsx
but I do not know how to enter the chat functional interface after login?
Would you give me some suggestion and sample code to implement it?

BTW: I want implement other 3rd party and custom common OAuth2/JWT SSO, not only Google Sign-In.
I think the unified solution abstraction for chat-copilot frontend webapp SSO is better.
I hope it will be new feature in recent future pipeline

the screenshots as below:
1. Google Login Button
![image](https://github.com/microsoft/chat-copilot/assets/1026479/a589e7e0-6456-4eba-bdb6-1f0df96b1d1b)
2. Signed-In Info show in `Login` View only
![image](https://github.com/microsoft/chat-copilot/assets/1026479/b3d4df30-8f5e-4c54-89ca-e5a2ed7e4d13)

**Comment by matthewbolanos** [comment]
@gitri-ms, do you have any pointers on how someone could integrate a different auth provider?

**Comment by AwesomeYuer** [comment]
for referring: another simple react js sample in js not ts , support msi and gsi

https://github.com/AwesomeYuer/msi-gsi-sso-react-spa.js

**Comment by gitri-ms** [comment]
This is not a feature we are planning to support in the Chat Copilot reference app, but I highly encourage you to keep pursuing it. Let me see if I can shed some light on our authentication setup to help you along.

- All requests from the frontend to the backend need to include an access token. We currently retrieve that token via [`AuthHelper.getSKaaSAccessToken`](https://github.com/microsoft/chat-copilot/blob/50f7230189fff0abf178070c37217c0088f86551/webapp/src/libs/auth/AuthHelper.ts#L116). You could consider adding another option in there that detects if the user has signed in with Google (or 

- You will also need to make changes on the backend, as the service is set up to require authentication to all endpoints. Take a look at the [`AddCopilotChatAuthentication`](https://github.com/microsoft/chat-copilot/blob/50f7230189fff0abf178070c37217c0088f86551/webapi/Extensions/ServiceExtensions.cs#L253) extension method. You could add a third authentication option here, and I encourage you to dig into the different options available through `IServiceCollection.AddAuthentication` -- looks like there is one for `AddOAuth`.

I have a [task on me](https://github.com/microsoft/semantic-kernel/issues/1640) to create an architecture document for our authentication setup. I am hoping to be able to start that soon, and I expect it would be helpful to you and others who are interested in supporting other auth providers.

**Comment by AwesomeYuer** [comment]
@gitri-ms thanks , go ahead

**Comment by gitri-ms** [comment]
@AwesomeYuer - I'm not sure of this answer here, but I think this would be a great conversation to have in our Discord community. In fact, we have a [dedicated channel just for Chat Copilot](https://discord.com/channels/1063152441819942922/1143586023851434074) where you can engage with other developers who might have ideas on how to build this.

As I mentioned before, this is not a feature that we are planning to bring to the Chat Copilot repo, so I am going to close this issue. But I encourage you to continue exploring how to build a unified identity solution and implement it in your own fork of Chat Copilot!

**Comment by AwesomeYuer** [comment]
@gitri-ms 

how can I join the [dedicated channel just for Chat Copilot](https://discord.com/channels/1063152441819942922/1143586023851434074)?

I can't access it now.
I can't search any useful results by using 'chat-copilot' or 'chat' or `copilot`? 
Is the discord NOT public?

Thanks
