### ISSUE TITLE
CosmosDb partitioning strategy causing high cost/low perf, max quota/too many requests

### ISSUE THREAD

**Issue by dluc** [microsoft/chat-copilot#238]
1. `chatsessions` table is partitioned by ID, but should be partitioned **by User** and have an index on the ID
2. `chatmessages` table is partitioned by ID, but should be partitioned **by Chat ID**

In the current setup, as these tables grow, CosmosDb takes more and more time to execute these operations:

1. Load the list of chats for the current user
2. Load the list of messages for the selected chat

Other than increasing **latency**, also the incurred **cost in RUs (and $)** grows, with the risk of hitting Max Quota when autoscale is not enabled.

**Comment by crickman** [comment]
Thank you for reporting this.  I think we may also want to consider how to apply any fix in a manner that doesn't break existing chats.

**Comment by crickman** [comment]
@dluc - Did you mean `chatparticipants` intead of `chatsessions` (no user in `chatsessions`):

> 1. `chatsessions` table is partitioned by ID, but should be partitioned **by User** and have an index on the ID

**Comment by crickman** [comment]
Linked branch with core fix:

CosmosDB database and container are created during deployment (not by code).  The partitioning scheme is defined at this time in [scripts/deploy/main.bicep](https://github.com/microsoft/chat-copilot/blob/fix-cosmosdb-partitioning/scripts/deploy/main.bicep).

If no migration is required (as Devis stated), the containers can simply be deleted and redeployed.

The proper partition key will be utilized upon entity insert (no code change required).

Existing chat-copilot deployments will continue to work, but using the non-performant partitioning.

If migration pathway is required or some other type of schema-version detection, let's identify and iterate on those cases.

**Comment by crickman** [comment]
Draft PR - https://github.com/microsoft/chat-copilot/pull/240

Following up w/ Tao tomorrow to explore deployment options to realize this change w/ minimal fuss.
