### ISSUE TITLE
Show input prompts and LLM outputs generated in stepwise planner

### ISSUE THREAD

**Issue by samleegithub** [microsoft/chat-copilot#243]
Is there a way to view the input prompts and LLM outputs that are generated in stepwise planner while it is running in Chat Copilot?

This would be very helpful in debugging why something goes wrong and let us find ways to improve the planner's behavior.

**Comment by teresaqhoang** [comment]
Hey @samleegithub, you should be able to see the context of the Stepwise Thought Process in the prompt dialog under the planner results section. 

1. Click on the `(i)` icon on any message. 
![image](https://github.com/microsoft/chat-copilot/assets/125500434/f2c803bd-e505-496d-9a90-d07aa62bc392)

2. If the Stepwise Planner was used, then there will be a `Planner Results` section right before `Chat History`. At the end of this section, there will be an expandable section `Explore how the stepwise planner reached this result! Click here to show the steps and logic.`. Click on this.
![image](https://github.com/microsoft/chat-copilot/assets/125500434/fadd524e-603f-4709-ae84-d3db3e3d643e)

3. You can click on any Action step to view additional details, including inputs and outputs. For actions, inputs are listed under `Action variables` and outputs are under `Observation:`.
![image](https://github.com/microsoft/chat-copilot/assets/125500434/7d88dc13-2dae-4242-80d8-8a912c7cf8a5)

Hope that helps! If you want to learn more about Stepwise Planner, Lee and Alex walk through the details in [this video](https://youtu.be/DG_Ge1v0c4Q).

**Comment by samleegithub** [comment]
This is great! Thank you @teresaqhoang!
