### ISSUE TITLE
Getting error during deployment of Azure resources for copilot

### ISSUE THREAD

**Issue by sganesan18** [microsoft/chat-copilot#245]
Hello, 

I am trying to follow the procedures listed here to setup copilot: https://github.com/microsoft/chat-copilot/blob/main/scripts/deploy/README.md#deploy-azure-infrastructure

Once I initiate deploy-azure.ps1, all the validation successfully completes. But the deployment fails with the below error message: 

Deploying Azure resources (xyz)...
{"error":{"code":"DeploymentNotFound","message":"Deployment 'xyz' could not be found."}}

Note: I am trying to deploy in East US region. 

Can you please guide us, if we are missing something?

**Comment by nacharya1** [comment]
@glahaye can you take a look into this?

**Comment by glahaye** [comment]
As per internal discussion, this seemed to be due to some Azure transient problem. Closing issue here and continuing related support by internal email.
