### ISSUE TITLE
Non-English Documents in Copilot Chat: Chinese Documents Not Producing Effective Answers

### ISSUE THREAD

**Issue by huangchao-shanghai** [microsoft/chat-copilot#249]
Uploading an English document and asking questions, the copilot chat can respond normally. However, uploading a Chinese document does not result in effective answers. 
I noticed that although the question was in Chinese, the user intent was converted to English in the prompt, and no document was embedded in the document snippets. I'm not sure if this is what caused the issue. Is it possible to enable copilot chat to support question and answer for documents in languages other than English?
![image](https://github.com/microsoft/chat-copilot/assets/3233883/dd768f66-198c-4c88-a004-108af0bf8346)

**Comment by alliscode** [comment]
@huangchao-shanghai thank you for letting us know about this issue. We have created an issue on our backlog to improve this functionality [here](https://github.com/microsoft/chat-copilot/issues/333). We will track the progress using the new issue so I'm closing this one. Thanks!
