### ISSUE TITLE
Incorrect behaivior and usage of  CreateNewChat

### ISSUE THREAD

**Issue by Rainson12** [microsoft/chat-copilot#250]
**Describe the bug**
When sending a chat message to the SemanticKernal api, the whole prompt as raw is being sent to the sdk however this has a huge impact on the response. For example the following prompt:
```
Optimize the following text to be sent to work colleague:
Dear Kris,
thank you for your thoughts and suggestions, this really helps! I have checked all common vendors but couldn't find anything that would match convertiable 13", with native HDMI port. The linked HP Spectre for example does not offer a native HDMI port. The closest I could find would be a "ThinkPad X1 Yoga" however it would be 14" size: https://www.lenovo.com/us/en/p/laptops/thinkpad/thinkpadx1/thinkpad-x1-yoga-gen-8-(14-inch-intel)/21hq001sus

Would you still be comfortable with it? I would like to purchase it through US and ship it to your address as in Germany there are generally no laptops available with US Keyboard available, it would require a "Build to Order" process which typically takes 3-4 Weeks minimum.
```
will result in this rawContent (https://github.com/microsoft/chat-copilot/blob/main/webapi/Skills/ChatSkills/ChatSkill.cs#L720C8-L720C8):
```
This is a chat between an intelligent AI bot named Copilot and one or more participants. SK stands for Semantic Kernel, the AI platform used to build the bot. The AI was trained on data through 2021 and is not aware of events that have occurred since then. It also has no ability to access data on the Internet, so it should not claim that it can or say that it will go and look things up. Try to be concise with your answers, though it is not required. Knowledge cutoff: Saturday, January 1, 2022 / Current date: Montag, 28. August 2023 11:49.

Either return [silence] or provide a response to the last message. If you provide a response do not provide a list of possible responses or completions, just a single response. ONLY PROVIDE A RESPONSE IF the last message WAS ADDRESSED TO THE 'BOT' OR 'COPILOT'. If it appears the last message was not for you, send [silence] as the bot response.

List of participants: Default User, Kris

User intent: The user wants the bot to optimize a message for them to send to their work colleague regarding their search for a convertible 13" laptop with a native HDMI port and to ask if their colleague would still be comfortable with purchasing a ThinkPad X1 Yoga that is 14" in size.


Chat history:
[28.08.2023 11:49:08] bot: Hello, this the Indivumed GPT! How can I help you today?
[28.08.2023 11:49:14] Default User: Optimize the following text to be sent to work colleague:
Dear Kris,
thank you for your thoughts and suggestions, this really helps! I have checked all common vendors but couldn't find anything that would match convertiable 13", with native HDMI port. The linked HP Spectre for example does not offer a native HDMI port. The closest I could find would be a "ThinkPad X1 Yoga" however it would be 14" size: https://www.lenovo.com/us/en/p/laptops/thinkpad/thinkpadx1/thinkpad-x1-yoga-gen-8-(14-inch-intel)/21hq001sus

Would you still be comfortable with it? I would like to purchase it through US and ship it to your address as in Germany there are generally no laptops available with US Keyboard available, it would require a "Build to Order" process which typically takes 3-4 Weeks minimum.

SINGLE RESPONSE FROM BOT TO USER:
[Montag, 28. August 2023 11:49 18] bot:
```

The response to this rawContent chat request will be (or similar): 
```
The message looks good to me! It clearly outlines your search for a convertible 13" laptop with a native HDMI port and offers an alternative option. Just make sure to double-check the specs and compatibility with Kris before making the purchase.
```

This response is however does not match the request. The same "request" of what the user entered into the azure ai playground, this would be the result:

![image](https://github.com/microsoft/chat-copilot/assets/13119203/5da2a33b-7efb-4979-9d50-e188f5d606ae)
which is much closer to what the user requested. A similar response can also be generated when leaving out all the additional info and just send the system behaivior and the actual chat message like:

```
This is a chat between an intelligent AI bot named Copilot and one or more participants. SK stands for Semantic Kernel, the AI platform used to build the bot. The AI was trained on data through 2021 and is not aware of events that have occurred since then. It also has no ability to access data on the Internet, so it should not claim that it can or say that it will go and look things up. Try to be concise with your answers, though it is not required. Knowledge cutoff: Saturday, January 1, 2022 / Current date: Montag, 28. August 2023 11:36.

Either return [silence] or provide a response to the last message. If you provide a response do not provide a list of possible responses or completions, just a single response. ONLY PROVIDE A RESPONSE IF the last message WAS ADDRESSED TO THE 'BOT' OR 'COPILOT'. If it appears the last message was not for you, send [silence] as the bot response.

Optimize the following text to be sent to work colleague:
Dear Kris,
thank you for your thoughts and suggestions, this really helps! I have checked all common vendors but couldn't find anything that would match convertiable 13", with native HDMI port. The linked HP Spectre for example does not offer a native HDMI port. The closest I could find would be a "ThinkPad X1 Yoga" however it would be 14" size: https://www.lenovo.com/us/en/p/laptops/thinkpad/thinkpadx1/thinkpad-x1-yoga-gen-8-(14-inch-intel)/21hq001sus

Would you still be comfortable with it? I would like to purchase it through US and ship it to your address as in Germany there are generally no laptops available with US Keyboard available, it would require a "Build to Order" process which typically takes 3-4 Weeks minimum.
```
as the rawContent. In this case at least the response is closer to what the user wanted:

```
Hi there! Here's the message optimized for your colleague: "Hi Kris, thank you for your input and suggestions. Unfortunately, I checked with all the common vendors, but none of them offer a convertible 13" laptop with a native HDMI port. The HP Spectre you linked doesn't have one either. The closest match I found would be the ThinkPad X1 Yoga, but it's a 14" laptop. Would that still work for you? If so, I can purchase it in the US and have it shipped to your address in Germany. Generally, laptops with US keyboards aren't available here and require a "Build to Order" process that takes at least 3-4 weeks."
```

**Comment by Rainson12** [comment]
It would require to rewrite the handling of the chat history to something like this:
https://github.com/Rainson12/chat-copilot/commit/9a552bd8e8152e12127f2cd2a4cbf1d296ef4488

**Comment by Rainson12** [comment]
@alliscode  I would like to work and suggest some alternative but I am unsure about how and why that logic was created in first place. I can not find the meaning behind maintaining a long-/shortterm memory (https://github.com/microsoft/chat-copilot/blob/main/webapi/Skills/ChatSkills/ChatSkill.cs#L443C15-L443C42) as well as querying the intent (https://github.com/microsoft/chat-copilot/blob/main/webapi/Skills/ChatSkills/ChatSkill.cs#L342) or the audience (https://github.com/microsoft/chat-copilot/blob/main/webapi/Skills/ChatSkills/ChatSkill.cs#L336). 

Here are my concerns:
* Querying open api just for the intent of the users request and then adding it to the final query might confuse as the actuall context of the conversations gets lost? I dont see any need of why the intent of the user must be queried in first place as just having the chatHistory should be enough unless we run out of tokens? Even in this case it might be better to just go with the chatHistory instead of the artifical generated Intent as the chatHistory will likely have more context of what the user actually expects.
* Whats the idea behind extracting the audience from the chat? How does that help getting a better result? OpenAis GPT should be able to get involved audiences by just checking the messages passed. I dont think hinting for audiences is beneficial? 
* Whats the idea behind the ExtractSemanticChatMemoryAsync function? I can not find any real benefit or usage of it?

**Comment by alliscode** [comment]
Hi @Rainson12, thank you for raising your concerns and questions here. I've been looking into this, and I agree that the way we are forming the prompt with user intent makes it ineffective for some queries such as the one you are demonstrating. I believe that there may be some prompt engineering that could be done to improve this, and we'll continue to look into making this better.

To answer some of your questions:

One of the goals of chat-copilot is to demonstrate one method of providing a continuous, long lived, ongoing chat session. One of the difficulties with this is that the prompt size can only be so large before you run out of tokens, and this limits the amount of chat history that you can include in the prompt. One of the ways that we deal with this is to _compress_ the chat history by periodically asking the LLM to summarize what it understands about the chat history into what we call semantic memories - this allows us to discard some of the verbatim chat history and yet retain some knowledge of it. The user intent extraction is performed for similar reasons, to _compress_ the users ask into a hopefully equivalent yet shorter semantic statement.  This works well for a lot of scenarios, but not so well for scenarios that are asking for operations to be performed on the verbatim text of the ask.

The audience extraction is something that we added to help with the multi-user chat scenarios. The webApi does not store usernames and so we add them to the prompt by asking the model to extract them from the message history.

We'll continue to work on making this work better for more scenarios, and If you have ideas on how to make this work better for your scenario, we're happy to discuss them. Thanks!

**Comment by alliscode** [comment]
Closing this issue for now. We will continue to work on improving these scenarios and look forward to any suggestions you have. Thanks!
