### ISSUE TITLE
Investigate Llama Index integration

### ISSUE THREAD

**Issue by alliscode** [microsoft/chat-copilot#271]
Investigate Llama Index and determine if there is an integration point with Semantic Kernel that we can demonstrate

**Comment by geffzhang** [comment]
[LLama.SemanticKernel]( https://github.com/SciSharp/LLamaSharp/tree/master/LLama.SemanticKernel)

**Comment by crickman** [comment]
Addressed as part of memory investigation.  Can track subsequent work with new issue.
