### ISSUE TITLE
Copilot Chat: add dotnet 6.0 SDK to devcontainer

### ISSUE THREAD

**Issue by iMicknl** [microsoft/chat-copilot#274]
Currently the provided devcontainer does not support dotnet 6, which is required for `samples/apps/copilot-chat-app`. When you try to install the dotnet sdk following the [instructions](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2004), you will face an error. This can block adoption for first time users that want to develop via GH CodeSpaces or VSCode devcontainer.

`
E: Conflicting values set for option Signed-By regarding source https://packages.microsoft.com/ubuntu/20.04/prod/ focal: /usr/share/keyrings/microsoft-archive-keyring.gpg != 
E: The list of sources could not be read.
`

I haven't been able to resolve it yet, but I will do a PR otherwise 😉.
```[tasklist]
### Tasks
```

**Comment by nacharya1** [comment]
@iMicknl - can you confirm if you are still facing the issue with the latest installation instructions for Chat Copilot found here > https://github.com/microsoft/chat-copilot#instructions. 
Apologies this issue was not triaged correctly hence extremely bad timing on the response.

**Comment by alliscode** [comment]
I believe this issue is no longer relevant for chat-copilot. @iMicknl please feel free to open another issue if you are still seeing issues! Thanks!
