### ISSUE TITLE
Chat Copilot token usage is extremely high

### ISSUE THREAD

**Issue by masonsawtell** [microsoft/chat-copilot#280]
**Describe the bug**
When using the Chat Copilot to upload a text file and ask questions about it, the usage of tokens is much higher than expected (13496 tokens total for a 949 token document and 429 tokens of chat text). This means that with the Azure OpenAI rate limit, an application would be limited to ~10 concurrent users. Is there any way to control the tokens being used? If not, is there a way to see exactly what Skills use the most amount of tokens? 

 

**To Reproduce**
1. Start new Session/Chat
2. Upload text file (below)
3. Ask questions "What is the fungus?", "What is Arachniotus ruber?", "What is its habitat?", and "How do I cultivate it?"?
4. Click on 'Settings' and view token usage

 

**Expected behavior**
Token usage is within a reasonable range for the size of the chat.

 

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/107892774/a8048949-2777-411b-a4ab-ec18825d77d8)
![image](https://github.com/microsoft/chat-copilot/assets/107892774/412a284c-95ba-4e98-98c2-f256fcc03c4c)

 

**Platform**
- OS: Windows
- IDE: VS Code
- Language: C#
- Source: Main branch of repository

 

**Additional context**
Text file used:
https://gist.github.com/masonsawtell/8fcaf4db88c8bbb1f69c5810f1a5cf41

**Comment by goyanx** [comment]
Hi, any workarounds ?

**Comment by evchaki** [comment]
@masonsawtell - thanks for bringing this up.  You can remove the chat history and memory to reduce the token usage.

To disable chat history in the prompt, remove line 381 to 389: [chat-copilot/webapi/Skills/ChatSkills/ChatSkill.cs at main · microsoft/chat-copilot (github.com)](https://github.com/microsoft/chat-copilot/blob/main/webapi/Skills/ChatSkills/ChatSkill.cs#L378)

To disable memory in the prompt, remove the components here: [chat-copilot/webapi/Skills/ChatSkills/ChatSkill.cs at main · microsoft/chat-copilot (github.com)](https://github.com/microsoft/chat-copilot/blob/main/webapi/Skills/ChatSkills/ChatSkill.cs#L379)

**Comment by aman-neudesic** [comment]
@evchaki Thank you for your reply. Could disabling the chat history and the memory in the prompt adversely affect the quality of responses? It seems that these changes might result in a loss of contextual awareness, potentially leading to less coherent and continuous interactions. What are your thoughts on the potential impacts of these modifications?

**Comment by aman-neudesic** [comment]
@evchaki -- Thank you for your input. Considering the potential impact on the quality of responses, are there any experiments underway on other branches to explore alternative approaches, perhaps controlling the token usage for summarizations, that might help in mitigating this issue?

**Comment by Rainson12** [comment]
> @evchaki -- Thank you for your input. Considering the potential impact on the quality of responses, are there any experiments underway on other branches to explore alternative approaches, perhaps controlling the token usage for summarizations, that might help in mitigating this issue?

If i find the time ill create a fork version tomorrow, with adjusted token consumption including chat history but without intent, audiance and memo generation. Its far away from perfect but uses much less tokens unless you want to maintain very long conversations. In this case you might want to stick to the current solution.

**Comment by aman-neudesic** [comment]
@masonsawtell  @Rainson12 - Thank you. No rush but it would be great to experiment with the version you have been using internally.

**Comment by Rainson12** [comment]
> @masonsawtell @Rainson12 - Thank you. No rush but it would be great to experiment with the version you have been using internally.
have a look at
https://github.com/Rainson12/chat-copilot/tree/feature/less-overhead

You can find the changes here:
https://github.com/microsoft/chat-copilot/commit/7039787a4dcf02af65e7a78e72ffec847f7b67fc

I removed the generation of the audience, intent and memorization and added the chat history, system description, SystemIntent, planResponse and documentContent as chat Message. This way the results should be more accurate. However the parts of the chat History can get lost due to insufficient tokens left. So it might not be suiteable for very long conversations.

**Comment by matthewbolanos** [comment]
Thanks @Rainson12 for sharing your solution. We don't currently have plans to change our token usage in the default version of Chat Copilot, so folks are encouraged to take a look at @Rainson12 changes.
