### ISSUE TITLE
`Server Error in '/' Application` after azure deployment

### ISSUE THREAD

**Issue by ekdnam** [microsoft/chat-copilot#281]
**Describe the bug**

I am deploying my copilot to azure by following `/scripts/deploy`. However after following all the steps, I get the following error. Screenshot attached.

I followed `deploy-azure.sh` as well as `package-webapi.sh` and `deploy-webapi.sh`. Nothing worked.

<img width="1351" alt="image" src="https://github.com/microsoft/chat-copilot/assets/40426312/a092ce15-c486-42c7-ba0d-284759ce9ce9">

**Comment by ekdnam** [comment]
Going to the /healhz does not work as well

**Comment by alliscode** [comment]
HI @ekdnam, sorry that you are experiencing this issue. Can you tell me what endpoint you are trying to load in the screenshot you provided? Is this the webApp or the webApi that you're pointing your browser at?

**Comment by ekdnam** [comment]
Thanks for the reply. This is the webapi endpoint

**Comment by DevBSC01** [comment]
Same same here. I'm not sure yet if it's the root cause but in the Diagnostics Dump of the WebAPI App Service there are a couple of exceptions that are constantly thrown like:

```
</Data><Data>https://app-copichat-xxxxxxxxxxxxxxx-webapi.azurewebsites.net:443/healthz</Data><Data>/healthz</Data><Data>xxx.xxx.xxx.xxx</Data><Data/><Data>False</Data><Data/><Data>IIS APPPOOL\app-copichat-xxxxxxxxxxxxxxx-webapi</Data><Data>9</Data><Data>IIS APPPOOL\app-copichat-xxxxxxxxxxxxxxx-webapi</Data><Data>False</Data><Data>   at Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule.Application_BeginRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.&lt;&gt;c__DisplayClass285_0.&lt;ExecuteStepImpl&gt;b__0()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)
</Data></EventData></Event><Event><System><Provider Name="ASP.NET 4.0.30319.0"/><EventID>1309</EventID><Level>2</Level><Task>0</Task><Keywords>Keywords</Keywords><TimeCreated SystemTime="2023-08-31T22:20:39Z"/><EventRecordID>81010625</EventRecordID><Channel>Application</Channel><Computer>DW0SDWK00063B</Computer><Security/></System><EventData><Data>3005</Data><Data>An unhandled exception has occurred.</Data><Data>8/31/2023 10:20:39 PM</Data><Data>8/31/2023 10:20:39 PM</Data><Data>2d50750391094b9baee0c8cac57309b8</Data><Data>181</Data><Data>180</Data><Data>0</Data><Data>/LM/W3SVC/1103074014/ROOT-1-133379935778399031</Data><Data>Full</Data><Data>/</Data><Data>C:\home\site\wwwroot\</Data><Data>DW0SDWK00063B</Data><Data/><Data>2860</Data><Data>w3wp.exe</Data><Data>IIS APPPOOL\app-copichat-xxxxxxxxxxxxxxx-webapi</Data><Data>FileNotFoundException</Data><Data>Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.4.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxx' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule.Application_BeginRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.&lt;&gt;c__DisplayClass285_0.&lt;ExecuteStepImpl&gt;b__0()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)
```
But as I'm not really into ASP I'm not sure if my two cents help.

**Comment by Rainson12** [comment]
> </Data></EventData></Event><Event><System><Provider Name="ASP.NET 4.0.30319.0"/><EventID>1309</EventID><Level>2</Level><Task>0</Task><Keywords>Keywords</Keywords><TimeCreated SystemTime="2023-08-31T22:20:39Z"/><EventRecordID>81010625</EventRecordID><Channel>Application</Channel><Computer>DW0SDWK00063B</Computer><Security/></System><EventData><Data>3005</Data><Data>An unhandled exception has occurred.</Data><Data>8/31/2023 10:20:39 PM</Data><Data>8/31/2023 10:20:39 PM</Data><Data>2d50750391094b9baee0c8cac57309b8</Data><Data>181</Data><Data>180</Data><Data>0</Data><Data>/LM/W3SVC/1103074014/ROOT-1-133379935778399031</Data><Data>Full</Data><Data>/</Data><Data>C:\home\site\wwwroot\</Data><Data>DW0SDWK00063B</Data><Data/><Data>2860</Data><Data>w3wp.exe</Data><Data>IIS APPPOOL\app-copichat-xxxxxxxxxxxxxxx-webapi</Data><Data>FileNotFoundException</Data><Data>Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.4.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxx' or one of its dependencies. The system cannot find the file specified.

This looks like you are trying to run the application with the asp.net framework instead of asp.net core which is what would be required I guess. Is there any chance you can change the framework from ASP.NET to ASP.NET Core?

**Comment by DevBSC01** [comment]
Hi Rene, 
thanks for the reply and the hint! I will check your recommendation. Actually I did'nt change anything within the deployment scripts beside the env values. Will will deploy now a fresh rebased branch to see if it's a "Layer 8" issue ;-)

**Comment by DataShedEd** [comment]
Which platform were you using to build? I tried on MacOS and got the same issue... building on a Windows Machine fixed things (*fixed*!)

**Comment by evchaki** [comment]
@matthewbolanos  - can you try to repro

**Comment by DevBSC01** [comment]
Hi, I build and deployed in WSL2. I got some warnings (FluentUI related) and while building the we app an X11 problem (had to use --no-key-chain) but the API build is fine.

**Comment by DataShedEd** [comment]
The target on the web app looks to be dotnet 7, rather than 6. Could that be the issue? Just incremented the target to 7, and it’s deployed fine, working as expected.
________________________________
From: DevBSC01 ***@***.***>
Sent: Tuesday, September 5, 2023 6:43:52 PM
To: microsoft/chat-copilot ***@***.***>
Cc: Ed Thewlis ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL]Re: [microsoft/chat-copilot] `Server Error in '/' Application` after azure deployment (Issue #281)


Hi, I build and deployed in WSL2. I got some warnings (FluentUI related) and while building the we app an X11 problem (had to use --no-key-chain) but the API build is fine.

**Comment by ekdnam** [comment]
It was not working earlier, but now suddenly started working 🤔

**Comment by abymsft** [comment]
After spending 2 hours with Bash 😐, I can confirm that the powershell deployment path didn't end up blocking me with  HTTP500 error with the API. 
Although this time with PwShell, I explicitly set the hosting stack and version through the azure portal before deploying the api
<img width="255" alt="image" src="https://github.com/microsoft/chat-copilot/assets/50873759/2ef26d3b-bc7b-4abe-a7e1-30ea5e68df40">
