### ISSUE TITLE
Failed: memory not established (Azure Cognitive Search)

### ISSUE THREAD

**Issue by seajhawk** [microsoft/chat-copilot#284]
I have a freshly deployed application where I used the `Deploy to Azure` button and specified AzureCognitiveSearch as the memoryStore. However, when I try to upload .pdf or .txt files I get "Failed: memory not established".

In addition
- looking in the resource group there is no 'Azure Cognitive Search' resource present. My assumption is that specifying it and not having a place to provide a link to an existing resource means the deployment should have created the resource. 
- the main.bicep file does indicate that ACS should be deployed:
```
resource azureCognitiveSearch 'Microsoft.Search/searchServices@2022-09-01' = if (memoryStore == 'AzureCognitiveSearch') {
  name: 'acs-${uniqueName}'
  location: location
  sku: {
    name: 'basic'
  }
  properties: {
    replicaCount: 1
    partitionCount: 1
  }
}
```
- and there were no deployment errors reported

**To Reproduce**
1. Deploy new instance
2. Specify memoryStore=AzureCognitiveSearch
3. Drop .pdf file on the page

**Expected behavior**
I expect the files to be uploaded and embedded into ACS.

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/18316676/ef6f6831-627f-4e43-9b61-0607fe8668ce)

**Platform**
 - OS: Windows
 - IDE: NA
 - Language: NA
 - Source: right here

**Additional context**

**Comment by alliscode** [comment]
Hi @seajhawk, thank you for reporting this, we'll investigate this issue and get back to you.

**Comment by seajhawk** [comment]
Correction - I do see that ACS was created (acs-copichat-[uniquename])

**Comment by seajhawk** [comment]
I've got it working now. I needed to deploy `text-embedding-ada-002` in my Azure OpenAI resource.

I missed that requirement in the readme.md because I clicked the "Deploying Chat Copilot" link above the requirement so I could deploy to Azure.

It might help others if you mention the Deployed Models requirements in the readme.md prior to the instructions to deploy to Azure, or to include those requirements on the deploy to Azure page.

<img width="677" alt="image" src="https://github.com/microsoft/chat-copilot/assets/18316676/2e5a4dbb-8299-4692-95fc-293dce155d26">

**Comment by alliscode** [comment]
Glad to see this is resolved. We'll update the README to make this clearer, thanks!

**Comment by ObsidianDelta** [comment]
Yes, you have to put the name of the EmbeddingModel when you run the configure.ps1 script. Make sure that it's the name that you gave it in the Azure AI Studio.

**Comment by seajhawk** [comment]
> Yes, you have to put the name of the EmbeddingModel when you run the configure.ps1 script. Make sure that it's the name that you gave it in the Azure AI Studio.

I appreciate the help, but to be clear for any who read this in the future, I didn't run the `configure.ps1`. I Deployed to Azure using the instructions at https://github.com/microsoft/chat-copilot/blob/main/scripts/deploy/README.md, and I used the `Deploy to Azure` button.
