### ISSUE TITLE
deploy to azure button - only backend, not the frontend?

### ISSUE THREAD

**Issue by AndreV84** [microsoft/chat-copilot#292]
Hi, after deploying the backend with 'deploy to azure' button
is there a simple way to run frontend deployment at azure as well not using local device terminal but from azure portal somehow?
Thanks

**Comment by alliscode** [comment]
Hi @AndreV84, unfortunately there isn't at this time. This is a known gap that we are fixing in the next couple weeks. You can watch the status of [this issue](https://github.com/orgs/microsoft/projects/852/views/1?filterQuery=-status%3ADone%2C%22In+progress%22%2C%22In+review%22%2C%22Community+PRs%22+webapp&pane=issue&itemId=37258462) for updates on this.

Closing this issue for now as we are already tracking this. Thanks!
