### ISSUE TITLE
Error Due to Context Length Limit Exceeded

### ISSUE THREAD

**Issue by MuhammadFauziHanif** [microsoft/chat-copilot#300]
**Describe the bug**
The issue is encountered when engaging in extended conversations with the GPT-3.5-turbo model within the Chat Copilot application. This issue is specific to the Chat Copilot application's handling of conversations that exceed the model's context length limit of 4097 tokens.

**To Reproduce**
1. Access the Chat Copilot application.
2. Initiate a conversation with the GPT-3.5-turbo model.
3. Engage in a lengthy conversation, accumulating messages that eventually surpass the model's context length limit.
4. Encounter the error message:
   ```
   Error: 400: => Invalid request: The request is not valid, HTTP status: 400 - Detail: This model's maximum context length is 4097 tokens. However, you requested 4141 tokens (3117 in the messages, 1024 in the completion). Please reduce the length of the messages or completion. Status: 400 (Bad Request) ErrorCode: context_length_exceeded Content: { "error": { "message": "This model's maximum context length is 4097 tokens. However, you requested 4141 tokens (3117 in the messages, 1024 in the completion). Please reduce the length of the messages or completion.", "type": "invalid_request_error", "param": "messages", "code": "context_length_exceeded" } }
   ```

**Expected behavior**
Users should be able to engage in extended conversations within the Chat Copilot application with the GPT-3.5-turbo model without encountering errors related to the model's context length limitations. The Chat Copilot application should have a mechanism to manage and handle longer conversations seamlessly, considering the context length limit of 4097 tokens for the GPT-3.5-turbo model.

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/101511362/f9097aa6-06dc-4bd0-b228-7261cf4ea642)

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: Typescript, C#
- Source: main branch of repository

**Additional context**
This issue pertains to the Chat Copilot application's interaction with the GPT-3.5-turbo model and the management of lengthy conversations. It is essential to address this issue at the application level to ensure a smooth and uninterrupted user experience when conversing with the model, while considering the model's context length limit of 4097 tokens.
```[tasklist]
### Tasks
```

**Comment by alliscode** [comment]
Hi @MuhammadFauziHanif, sorry that you are experiencing this issue. Would you mind providing the prompt information to help us debug where the token limit is being exceeded? If you click the information button in the bot response it contains all of the prompt information that we need.

One more thing to verify is that you have not changed the value of the `CompletionTokenLimit` setting in the webApi's appsettings.json.

**Comment by evchaki** [comment]
@teresaqhoang - can you take a look

**Comment by MuhammadFauziHanif** [comment]
After several attempts to reproduce the bug, I've encountered difficulties, and it appears to be more subtle than initially thought. I no longer believe that it's solely caused by having a lengthy conversation.

Moving forward, if I come across this exact issue again, I'll prioritize verifying its reproducibility before creating a new issue. I apologize for opening the issue without performing this step first.

Unfortunately, my chat history was lost, making it impossible for me to provide the full conversation. During the occurrence of the bug, I was heavily reliant on planners and plugins. It's possible that the bug may be related to their usage, so it's worth considering this as a factor.

Regarding the CompletionTokenLimit setting in the webApi's appsettings.json, I haven't made any changes to it, and it remains set at 4096.

Once again, I apologize for any confusion and appreciate your assistance in resolving this matter.

**Comment by Dikarabo-Molele** [comment]
I am experiencing this issue. 
CompletionTokenLimit is still set to 4096.

A user had this issue but after a window of about 1 hour, using the same chat, the error went away.

Hard to share reproduction steps since the chat history contains some non-public information.
