### ISSUE TITLE
Proper use and reuse of HttpClient / IHttpClientFactory

### ISSUE THREAD

**Issue by glahaye** [microsoft/chat-copilot#302]
In order to avoid creating and recreating HttpClient instances all the time (which can lead to port exhaustion, unnecessary overhead in constantly re-establishing TLS connections and so on) while avoiding the problems of only using a single static HttpClient (which can become stale in its DNS resolution), we need to revisit how we creates HttpClient instances and make proper use of IHttpClientFactory injection.

**Comment by prabhatranjan** [comment]
Hi @glahaye, is this something that you are already working on?

**Comment by glahaye** [comment]
@prabhatranjan Yes.  As a matter of fact, I should have a PR out today.

**Comment by glahaye** [comment]
@prabhatranjan See #578 

Feel free to add comments and let me know if something is missing or not correct
