### ISSUE TITLE
BrowserAuthError when launching chat-copilot

### ISSUE THREAD

**Issue by alliscode** [microsoft/chat-copilot#33]
**Describe the bug**
Often when launching chat-copilot a red screen with errors is shown. This appears to be an issue related to authentication and pop-up windows.

Running in Private mode seems to fix the issue.

![image](https://github.com/microsoft/chat-copilot/assets/25218250/a76be11a-24e1-41e9-944b-8a44c2147bdf)

![image](https://github.com/microsoft/chat-copilot/assets/25218250/041221b2-5373-46e6-afb8-ab04d093a118)

**Expected behavior**
The app should launch and authenticate without error.

**Comment by alliscode** [comment]
[This thread](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5709#issuecomment-1446096814) looks promising.

**Comment by teresaqhoang** [comment]
Fixed -- moved all the getAccessToken calls inside try catch blocks
