### ISSUE TITLE
Prompt user for info in Stepwise

### ISSUE THREAD

**Issue by benm5678** [microsoft/chat-copilot#330]
Can you please advise how to implement getting more info from user when using Stepwise?  I added an OpenSupportTicketSkill class that has a similar named SK function & registering it in ChatController's RegisterPlannerSkillsAsync.  Initially it calls it with blanks values, so I added validation check & function returns error message (tried both as exception and returned value) - in both cases, LLM seems to correctly realize it needs to call some function to prompt the user for info, but it can't find it.  What is the way to add such a function?  I tried to add something like promptUser(string msg)... but I'm not sure what I need to do in its implementation?  If I just return a string there, it keeps looping endlessly.  I tried to review the existing ChatSkill but could not figure it out.  Any tips will be appreciated!!

Sample segment from debug logs:

> Microsoft.SemanticKernel.Planning.StepwisePlanner: Information: Thought: It seems that I made an error in the action. I forgot to include the necessary information for opening a support ticket, such as the employee ID, category, description, and priority. I need to ask the user for these details and then use them in the action.
> Microsoft.SemanticKernel.Planning.StepwisePlanner: Information: Action: assistant.ask({"question":"Sure, I can help you with that. Could you please provide the category of the support issue?"}).
> info: Microsoft.SemanticKernel.Planning.StepwisePlanner[0]
>       Action: assistant.ask({"question":"Sure, I can help you with that. Could you please provide the category of the support issue?"}).
> Microsoft.SemanticKernel.Planning.StepwisePlanner: Information: Observation: assistant.ask is not in [AVAILABLE FUNCTIONS]. Please try again using one of the [AVAILABLE FUNCTIONS].

**Comment by teresaqhoang** [comment]
Hey @benm5678 , apologies for the delayed reply.

You can try adjusting the `StepwisePlannerSupplement` in [CopilotChatPlanner](https://github.com/microsoft/chat-copilot/blob/c9e585d690e4218a76776ddb0b3ea39710b3234d/webapi/Skills/ChatSkills/CopilotChatPlanner.cs#L65C26-L65C51) to be more clear about bailing out. 

private const string StepwisePlannerSupplement = "If you need more information to fulfill this request, return an answer that explicitly requests the information needed. For example: I need more information from the user to fulfill the request: name, email, and date..";

**Comment by glahaye** [comment]
@benm5678 Were you able to address your issue, or do you need more information?

**Comment by benm5678** [comment]
> @benm5678 Were you able to address your issue, or do you need more information?

No, even with adjusting it, gpt35 was never good enough at following instructions and would make up values.  I think we can close this as chat co-pilot issue.  I need to try strategies like AutoGen where we have a specific user proxy agent...perhaps would work better.
