### ISSUE TITLE
Scale out of webapi app service 

### ISSUE THREAD

**Issue by UTKBlake** [microsoft/chat-copilot#332]
**Describe the bug**
When enabling scale out for the back end webapi web app the application exhibits unexpected behavior in the form of failing to display AI responses or 'hanging' at waiting for kernel status message.

**To Reproduce**
Deploy the app to Azure following the documentation.
Set the webapi scale out to automatic, always ready instance count to 2, and maximum burst instance to 2.
Wait for both instances to report ready in health check - instances.
Log in to the application with the static web app url.
Submit a chat message to the application.
The application will either do one of two unexpected behaviors,
1. The application will display the first response, subsequent chat messages will fail to display the generated response. After refreshing the page with f5 the generated responses will be show.
2. The application will display the waiting for kernel message and no longer respond to messages

**Expected behavior**
The app should respond to each chat message without failing to display a response or getting stuck at the waiting on kernel status message.

**Screenshots**
The first response from the application calling healthz contains two different ARRAffinity tokens and a single AARAffinitySameSite that will match one of the AARAffinity tokens.
![Screenshot 2023-09-11 181935](https://github.com/microsoft/chat-copilot/assets/142993421/9f3a11e3-adb6-4764-a0a6-d923e08aa0a0)

Failing to display chat responses.
![Screenshot 2023-09-11 183831](https://github.com/microsoft/chat-copilot/assets/142993421/215a3cae-0dc3-46e1-aa75-d614e42a1c58)

Chat responses received from network inspector
![Screenshot 2023-09-11 184012](https://github.com/microsoft/chat-copilot/assets/142993421/1ee312e5-9f75-4255-b193-ff86bba8566b)

![Screenshot 2023-09-11 184113](https://github.com/microsoft/chat-copilot/assets/142993421/b6cd2dad-078f-48c0-880e-b96725d2316c)

Periodic failures 404 unauthenticated errors are also being picked up by application insights.
![Screenshot 2023-09-11 184741](https://github.com/microsoft/chat-copilot/assets/142993421/0bd0015b-d40e-4d7e-affa-3010077f0392)

**Comment by alliscode** [comment]
@UTKBlake thank you for raising this issue. We are looking at options for supporting or at least documenting scale-out of copilot-chat. We're tracking this with [this issue](https://github.com/orgs/microsoft/projects/852/views/1?pane=issue&itemId=39285001) in our backlog.

Closing this issue for now, thanks!
