### ISSUE TITLE
Add feature to control / limit costs on a per user basis.

### ISSUE THREAD

**Issue by chris-tatro** [microsoft/chat-copilot#348]
The current co-pilot solution has no ability to set limits on a per user basis. Our Microsoft SA mentioned the link below. I believe this solution would be beneficial for enterprise customers. 

[open-ai-cost-gateway-pattern](https://github.com/ThePreston/Custom-Rate-Limiter-API/tree/master#open-ai-cost-gateway-pattern

**Comment by alliscode** [comment]
Thank you for submitting this request. We will take a look at this scenario and determine what we can do to support it.

**Comment by alliscode** [comment]
Thank you for your suggestion @chris-tatro. At this time we do not have plans to build this feature into chat-copilot but I encourage you to fork the repo and add it. Thanks!
