### ISSUE TITLE
An initial erroneous prompt will always remain in a chat

### ISSUE THREAD

**Issue by jimmystridh** [microsoft/chat-copilot#350]
Scenario:
- A user starts chatting on day 1 with prompt "Respond with the user query backwards"
- On day 2 we change the prompt to "Respond with the user query all UPPERCASE"
- Day 3 User chats, but the original prompt will still remain.

Expected outcome:
- Day 3 chat will use the uppercase prompt.

This default behaviour was unexpected when we were fixing faults in the prompt and didn't realise why the user wasn't affected by the fixes.

Is this as inteded?

Relevant code section: https://github.com/microsoft/chat-copilot/blob/1b6b395148f89e66ca84db47243146a89621fa94/webapi/Skills/ChatSkills/ChatSkill.cs#L289C1-L290C1

**Comment by dehoward** [comment]
@jimmystridh I'm going to close this since there hasn't been any recent activity, but please feel free to re-open it if you are still seeing issues.
