### ISSUE TITLE
when use memory store qdrant , occurs 404 error

### ISSUE THREAD

**Issue by AwesomeYuer** [microsoft/chat-copilot#351]
**Describe the bug**

This issue is easy for occurs! I remember the old version have not this 404 error issue

I am not sure this issue whether cause the issue https://github.com/microsoft/chat-copilot/issues/213#issue-1856745720

BTW:  Up to now, I found same issue as #213 is exists indeed, but it have been closed.

@crickman  have this #213 bug been fixed? or in fixing? thanks

**To Reproduce**
You need to config as below only, and then chat!

```json
{
  "MemoryStore": {
    "Type": "qdrant",
    "Qdrant": {
      "Host": "http://localhost",
      "Port": "6333",
      "VectorSize": 1536
      // "Key":  ""
    },
}
```

**Expected behavior**

**Screenshots**

![image](https://github.com/microsoft/chat-copilot/assets/1026479/f6d55b0d-05f7-4e50-baed-f7ae45f36b74)

**Platform**
 - OS: Windows
 - IDE: VS 2022
 - Language: [e.g. C#,]
 - Source: Latest code on 16th Sep, 2023

**Additional context**

**Comment by crickman** [comment]
Hi AwesomeYuer, thank you for reporting this.   This is a known issue with all semantic-kernel connectors.  Chat-Copilot _should_ catche these and interprets the result appropriately.

Are you observing a functional failure?  If so, can you please provide additional information?

**Comment by crickman** [comment]
> This seems to be present to all memory store, (I also have it with CognitiveSearch and someone else with PostgreSQL).
> 
> It should be fixed with #152

Indeed, we are moving away from SK connectors in this change!  Thank for for calling this out.

**Comment by kbeaugrand** [comment]
Hi,

one question regarding this PR. By moving to semantic-memory, you remove the possibility to add new connectors directly to chat-copilot right?
We would only be able to use already implemented connectors in semantic-memory, if we want to leverage on other database, third-party connectors might be difficult to add in that case...

**Comment by crickman** [comment]
Ok, I think I found the root issue, the exception is causing SaveInformationAsync to be skipped.

**Comment by AwesomeYuer** [comment]
@crickman thanks.

How about #213? have this issue been fixed? or in fixing? thanks

Up to now, I uploaded a document via the UI, but the chatbot cannot answer questions on the document indeed.
