### ISSUE TITLE
Add memory for stepwise observations

### ISSUE THREAD

**Issue by kbeaugrand** [microsoft/chat-copilot#353]
I'm using custom plugins on Chat Copilot with Stepwise planner. 
My custom plugin returns semantic responses to the planner.

The stepwise planner works well and give me expected result while creating requests to the custom plugin.

However, I'd like to store the stepwise observation (results from the plugins) to the short-term or long-term memory. 
This would give me the possibility to ask more details about the responses it provides without requesting more the plugin.

Does it make sense ? 

Regards,

**Comment by teresaqhoang** [comment]
Hey @kbeaugrand, I'm working on Saved Plans functionality this sprint and as an extension. I'll look into saving Plan results for recall as well and will keep in mind this specific scenario. You can track that work here: https://github.com/microsoft/semantic-kernel/issues/2581 

Closing this issue as a dupe

**Comment by kbeaugrand** [comment]
> Hey @kbeaugrand, I'm working on Saved Plans functionality this sprint and as an extension. I'll look into saving Plan results for recall as well and will keep in mind this specific scenario. You can track that work here: https://github.com/microsoft/semantic-kernel/issues/2581 
> 
> 
> 
> Closing this issue as a dupe 

Hi, 

Thank you for this answer ! Really happy to note that you are working on that ;) 

I was also starting to think about the plan saving and retrieval by their objectives in SK. I think you will do it better than me
