### ISSUE TITLE
Keep chat responses confined to documents available in the search index

### ISSUE THREAD

**Issue by milind045** [microsoft/chat-copilot#374]
How do we keep chats and responses limited to sources available within the search index? I've been trying to play around with SystemPersona components to restrict information to Document Snippets; but still it returns facts in the LLM. I changed the reponseTemperature to 0.
Is there a way to achieve this? I'm looking for behavior similar to github.com/Azure-Samples/azure-search-openai-demo-csharp

**Comment by matthewbolanos** [comment]
To change the behavior of the chat bot, you'll want to update the SystemDescription property in the https://github.com/microsoft/chat-copilot/blob/main/webapi/appsettings.json file. I'd recommend adding text that tells the LLM to _only_ reference information that's provided in the doc section.

The SK team will also investigate on the side how we can help the bot stay more focused on the documents at hand.
