### ISSUE TITLE
The "Klarna Shopping" plugin doesn't work.

### ISSUE THREAD

**Issue by bmis** [microsoft/chat-copilot#381]
**Describe the bug**
The "Klarna Shopping" plugin doesn't work.

**To Reproduce**
1. Go to "Plugins"
2. Click "Enable" on "Klarna Shopping" 
3. Click "Enable"
4. Back to "Chat" Windows
5. Ask for example "Can you recommend a new laptop?"
6. Click "Yes, proceed"
7. See the error "Unable to generate bot response. Details: Error: 400: Bad Request => Entity with id xxxxxxxxxxxxxxxxxx not found."

**Expected behavior**
Possibility of using the "Klarna Shopping" plugin.

**Platform**
 - OS:  Windows

**Comment by dehoward** [comment]
can you check the Network tab in the browser to see which call is failing? after we figure that out can you try restarting your backend? for some reason the chat can't be found on the backend when that call is made, but I haven't been able to reproduce this error.

**Comment by bmis** [comment]
I think the problem is well described here https://github.com/microsoft/semantic-kernel/issues/911

**Comment by dehoward** [comment]
@bmis this is happening because the [Klarna plugin endpoint](https://www.klarna.com/us/shopping/public/openai/v0/products) is currently down:
![image](https://github.com/microsoft/chat-copilot/assets/52973358/ee7d7c40-c63d-4a77-a097-f15bdb251ce9)

please re-open the issue if you notice this is still occurring once the endpoint is live again.

**Comment by bmis** [comment]
This is not the store's fault. The application generates the query incorrectly. The application generates the query like this https://www.klarna.com/public/openai/v0/products/?countryCode=US&q=laptop&size=1 and it should be like this https://www.klarna.com/us/shopping/public/openai/v0/products/?countryCode=US&q=laptop&size=1
