### ISSUE TITLE
Broken URL: https://aka.ms/copilotchat/memorypipeline/latest

### ISSUE THREAD

**Issue by raffertyuy** [microsoft/chat-copilot#382]
**Describe the bug**
https://aka.ms/copilotchat/memorypipeline/latest points to https://github.com/microsoft/chat-copilot/releases/download/0.4/memorypipeline-0.4.0.zip which doesn't exist.

**To Reproduce**
1. Go to https://learn.microsoft.com/en-us/semantic-kernel/chat-copilot/deploy-to-azure
2. Click on 'Deploy to Azure'
3. See value of Memory Pipeline Package Uri default to https://aka.ms/copilotchat/memorypipeline/latest
4. Deploying this will cause an error because the URL is broken

**Expected behavior**
Successful IAC deployment

**Screenshot**
![image](https://github.com/microsoft/chat-copilot/assets/1037626/bc0fb892-01d3-461b-b6a6-cf3411a9651c)

**Comment by glahaye** [comment]
@raffertyuy Thanks for reporting this.

The problem was due to a change in process on our side.

This has been fixed now.

Cheers.

**Comment by raffertyuy** [comment]
Thanks for resolving quickly!
