### ISSUE TITLE
Redeploying to Azure leads to the error `Failed to open siteversion.txt. ZipFS setup failed. Error: 0x80070003`

### ISSUE THREAD

**Issue by ekdnam** [microsoft/chat-copilot#384]
**Describe the bug**

I had deployed the app to azure. The webapi and the webapp were working fine. I moved the parts around Qdrant and the app did not crash. However, recently I changed some stuff and redeployed the app to azure. Specifically I changed a configuration and redeployed. It gave me the error `Server Error in '/' Application` (Tagging my previous issue: https://github.com/microsoft/chat-copilot/issues/281)

Then I reverted the change and redeployed. Got the same error.

Note: The webapp works fine locally.

On some deep diving into the logs I saw the following error reoccuring whenever I went to`{api}/healthz`
```
Failed to open siteversion.txt. ZipFS setup failed. Error: 0x80070003
```

How to resolve this?

**Comment by TaoChenOSU** [comment]
Hi @ekdnam, 

Thanks for reporting this issue!

Could you try removing the bin/ and obj/ artifact folders on your local machine, then rerun package-webapi and redeploy?

And could you let us know which configuration you changed?

**Comment by glahaye** [comment]
Can't repro.

No reply from user for 3 weeks.

Closing.
