### ISSUE TITLE
xlsx (MS Excel) files are not supported

### ISSUE THREAD

**Issue by mkspwr12** [microsoft/chat-copilot#386]
**Describe the bug**
This is more of a feature request than a bug. I'd like the copilot to accept xlsx files as well as CSV files and use that to answer questions. For example, if I feed it business revenue targets by organization units, accounts etc, it should be able to answer when asked.

**Comment by crickman** [comment]
Hi @mkspwr12, thank you for commenting on this.  At this time, spread-sheets are not directly supported for import.  Such support, when provided, would be via https://github.com/microsoft/semantic-memory.

While the timeline for adding support to https://github.com/microsoft/semantic-memory isn't clearly defined at this point, one option would be to export the file as either pdf or csv and then import.  (For .csv, rename the file to ".txt" for import.)  Some online tools might be able to coverted a table to mark-down...which could also be imported.

**Comment by crickman** [comment]
Note - https://github.com/microsoft/semantic-memory has a query endpoint you might utilize more directly than the chat-bot.

**Comment by crickman** [comment]
https://github.com/microsoft/chat-copilot/pull/402
