### ISSUE TITLE
Resource Not Found 404 :  {"error":{"code":"404","message": "Resource not found"}} 

### ISSUE THREAD

**Issue by ahilangfnp** [microsoft/chat-copilot#408]
**Describe the bug**
While running the app in local environment, got the following error when trying to send a message 
(Calling the api, https://localhost:40443/chat)

![image](https://github.com/microsoft/chat-copilot/assets/127736224/61a6b3a1-461c-42fa-a19a-7d259e00fca9)

In the code it fails in the following line

![image](https://github.com/microsoft/chat-copilot/assets/127736224/a46239dc-f28c-4880-a8ef-875f0df8e593)

**To Reproduce**
1. Go to initial chat application
2. Send a chat message
3. See error

**Expected behaviorch
As shown in the example the chat app should function

**Platform**
 - OS: Windows
 - IDE: [Visual Studio, VS Code]
 - Language: C#

**Comment by glahaye** [comment]
Can't repro.

No news from user after 3 weeks.

Closing as likely config issue.
