### ISSUE TITLE
"Only the person who prompted this plan can take action on it." due to loggedInUserId != senderId

### ISSUE THREAD

**Issue by JoeNSalloum** [microsoft/chat-copilot#412]
**Describe the bug**
The "Only the person who prompted this plan can take action on it." message is meant to not allow User A to approve User B's plan, this is done by comparing 2 variables in `signalRHubConnection.ts`:

- `loggedInUserId` -> fetched from the redux store's state
- `senderId` -> passed by SignalR backend

The problem occurs, when a user (user@contoso.com) belongs to 2 AAD tenants:
- a home tenant (e.g. contoso.onmicrosoft.com) where the user is a `Member`
- a guest tenant (e.g. contosoit.onmicrosoft.com) where the user has been invited to it and is a `Guest`

If the 2 app registrations needed to enable authentication with AAD are created in the **guest** tenant, the 2 variables get different values as such:

`loggedInUserId` = user_object_id_at_home_tenant.home_tenant_id
`senderId` = user_object_id_at_guest_tenant.guest_tenant_id

therefore, the message "Only the person who prompted this plan can take action on it." appears and the user can't approve their own plans.

**To Reproduce**
1. Have your user belong to 2 AAD tenants, one where you're a Member, one where you're a guest
2. Follow steps in README.MD to enable AAD authentication, making sure the app registrations get created in the tenant where the user is a Guest user
3. Launch the app, login with SSO
4. Enable Microsoft Graph plugin
5. Enter a prompt in the chat which will trigger a planner to use the graph plugin (e.g. `"How does my calendar look like tomorrow?"`)

**Expected behavior**
The expectation is to get a plan that the user can approve

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/63871159/1799f999-1c2c-47c1-b6ef-9cab5ca6e556)

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: C#
 - Source: main branch of repository

**Additional context**
I initially thought that the Default tenant the user belonged to mattered, so I tried changing it using:
- Azure CLI: `az account set subscription --subscription_in_guest_tenant`
- PowerShell: `Set-AzContext -Subscription "xxxx-xxxx-xxxx-xxxx`
- Azure Portal: go to [Manage Tenants](https://portal.azure.com/#view/Microsoft_AAD_IAM/DirectorySwitchBlade/subtitle/) and make the Guest Tenant the default one.

All above steps were successful in changing the default tenant to the guest one, but the issue persists.

**Comment by teresaqhoang** [comment]
Hey, @JoeNSalloum, the user and sender Id should match even when in guest mode. 

It looks like your frontend client is authenticating to the home tenant, not the guest tenant, so make sure the AAD Authority you're using in the webapp is `https://login.microsoftonline.com/{GUEST_TENANT_ID}`.

Also, can you confirm all the values in your configuration files are correctly, notably that the tenant Id matches in `webapp/.env` and `webapi/appsettings.Development.json`? The tenant Id should be the tenant Id of the app registrations (so the tenant the user is a guest of). 

.env:
```
REACT_APP_BACKEND_URI=https://localhost:40443/
REACT_APP_AUTH_TYPE=AzureAd
REACT_APP_AAD_AUTHORITY=https://login.microsoftonline.com/{GUEST_TENANT_ID}
REACT_APP_AAD_CLIENT_ID={FRONTEND_CLIENT_ID}
REACT_APP_AAD_API_SCOPE=api://{BACKEND_CLIENT_ID}/access_as_user
```

appsettings.Development.json
```json
{
  "Frontend": {
    "AadClientId": "{FRONTEND_CLIENT_ID}"
  },
  ...
  "Authentication": {
    "AzureAd": {
      "TenantId": "{GUEST_TENANT_ID}",
      "Scopes": "access_as_user",
      "ClientId": "{BACKEND_CLIENT_ID}",
      "Instance": "https://login.microsoftonline.com"
    },
    "Type": "AzureAd"
  },
  ...
}
```

**Comment by JoeNSalloum** [comment]
I can confirm that this is no longer an issue with the latest version of the main branch - will close. The `Frontend` config entry you mentioned @teresaqhoang gave it away.

Thank you!
