### ISSUE TITLE
Unable to create new chat session and I am getting 500 status code.

### ISSUE THREAD

**Issue by rnpramasamy** [microsoft/chat-copilot#414]
I referred below instructions to deploy copilot chat on azure:
https://github.com/microsoft/chat-copilot/blob/main/scripts/deploy/README.md

I created two active directory apps, gave necessary permissions and configured those apps.
I used azure resource template to create infrastructure and deploy backed api. 
I deployed frontend app with help of below command. 
./deploy-webapp.ps1 -Subscription {YOUR_SUBSCRIPTION_ID} -ResourceGroupName rg-{YOUR_DEPLOYMENT_NAME} -DeploymentName {YOUR_DEPLOYMENT_NAME} -FrontendClientId {YOUR_FRONTEND_APPLICATION_ID} 

I loaded web api on browser and I got below result:
![image](https://github.com/microsoft/chat-copilot/assets/5311453/3076c0a5-1186-4cfe-ba5f-3c762adbf41d)

Then I loaded frontend web app on browser, I logged in successfully but I got below error and unable to create new session:
![image](https://github.com/microsoft/chat-copilot/assets/5311453/b6740adc-32ef-49ef-96aa-a55b69705cb0)

**Comment by dehoward** [comment]
given the 401 it seems that your backend may not be properly configured for AAD auth. can you make sure you've followed all of the instructions [here](https://github.com/microsoft/chat-copilot#instructions-1)? specifically step #5 to setup your env variables.

**Comment by rnpramasamy** [comment]
I am able to run copilot chat on local machine and I am having an issue once I deployed it to azure.

**Comment by TaoChenOSU** [comment]
Hi @rnpramasamy, 

Thanks for reporting the issue!

The deploy to Azure button is still pointing to the 0.4 release as of today. Could you try running the ./deploy-webapp.ps1 script from this commit: https://github.com/microsoft/chat-copilot/commit/c9e585d690e4218a76776ddb0b3ea39710b3234d, which is commit at which release 0.4 was created.

We are in the processing of consolidating our release workflow. Stay tuned. 

Let us know if you see other issues.

**Comment by rnpramasamy** [comment]
I successfully  deployed c9e585d commit on azure and uploaded few pdf documents into documents section.

Copilot still does not respond from pdf documents which I uploaded and I am getting message like "I apologize".

**Comment by TaoChenOSU** [comment]
> I successfully deployed [c9e585d](https://github.com/microsoft/chat-copilot/commit/c9e585d690e4218a76776ddb0b3ea39710b3234d) commit on azure and uploaded few pdf documents into documents section.
> 
> Copilot still does not respond from pdf documents which I uploaded and I am getting message like "I apologize".

Great to hear that you were able to deploy successfully!

It really depends on the document and the questions asked. You can read more about how to tune the behavior here: https://github.com/microsoft/chat-copilot/issues/407. In short, you can play with the relevance threshold. The lower the threshold, the more likely you will get matches from a semantic search.

**Comment by TaoChenOSU** [comment]
Closing. Feel free to reopen if you have further questions.
