### ISSUE TITLE
 Chat-copilot doesn't work properly using own data

### ISSUE THREAD

**Issue by bmis** [microsoft/chat-copilot#418]
**Describe the bug**

Earlier versions of chat-copilot worked properly after uploading your data (you could query about the file you added). The current version does not return information using added files.

**To Reproduce**
1. Go to 'Documents', upload ms10k.txt (chat-copilot\tools\importdocument\sample-docs)
2. Go to 'Chat'
3. Write 'What was Microsoft's cloud revenue for 2022?'
4. Check the answer "I'm sorry, but as an AI language model, my training data only goes up until January 1, 2022. I don't have access to real-time data or information about Microsoft's cloud revenue for 2022. It would be best to refer to the latest financial reports or news from Microsoft for the most accurate and up-to-date information on their cloud revenue."
5. Previous version of chat-copilot wrote 'Microsoft's cloud revenue for 2022 was $91.2 billion.'

**Expected behavior**
Chat-copilot should use data from the 'Documents' tab

**Screenshots**

The current version of chat-copilot

![image](https://github.com/microsoft/chat-copilot/assets/22316922/ced3586e-5fb2-4c9e-ab82-de68f3762723)

Previous version

![image](https://github.com/microsoft/chat-copilot/assets/22316922/6c652729-f250-4507-8187-8ba014ad037a)

**Platform**
 - OS: Windows

**Additional context**

**Comment by TaoChenOSU** [comment]
Closing. Feel free to reopen if you have further questions.
