### ISSUE TITLE
Documents uploaded with global scope not searched by CoPilot memory

### ISSUE THREAD

**Issue by arvashis** [microsoft/chat-copilot#421]
**Describe the bug**
Any documents uploaded with global scope via the console app ImportDocument in not included in documentmemory search. If the document is uploaded in the context of a chat via the UI then everything works fine.

**To Reproduce**
1. Upload a supported document via ImprtDocument console app as per the README.md.
2. Start a new chat OR even use an ongoing chat with the copilot and ask a specific question about the content from the document you uploaded. 
3. CoPilot will return a generic answer without any context to the uploaded document.
4. Now, upload the same / other document from the upload tab on the copilot
5. Now Ask Copilot as in #2 
6. This time CoPilot returns the expected response.

**Expected behavior**
Documents uploaded with Global scope are used by the copilot to respond to the query in any chat thread.

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#

**Additional context**

**Comment by dehoward** [comment]
@TaoChenOSU can you help take a look at this? we should be seeing the same results no matter where how the document was uploaded.

**Comment by arvashis** [comment]
I believe ISemanticMemoryExtensions clss sets filter with chatid and since the globally uploaded doc is not associated with this chatid, the filter leaves them out. If the memory has a chatid=Guid.Empty then that also should be included as it would seem global.

public static async Task<SearchResult> SearchMemoryAsync(
 this ISemanticMemoryClient memoryClient,
 string indexName,
 string query,
 float relevanceThreshold,
 int resultCount,
 string chatId,
 string? memoryName = null,
 CancellationToken cancellationToken = default)
 {
     var filter =
         new MemoryFilter
         {
             MinRelevance = relevanceThreshold,
         };

     filter.ByTag(MemoryTags.TagChatId, chatId);

     if (!string.IsNullOrWhiteSpace(memoryName))
     {
         filter.ByTag(MemoryTags.TagMemory, memoryName);
     }

     var searchResult =
         await memoryClient.SearchAsync(
             query,
             indexName,
             filter,
             resultCount,
             cancellationToken);

     return searchResult;
 }

**Comment by liebert100** [comment]
Changing the code in chat-copilot\webapi\Skills\ChatSkills\SemanticMemoryRetriever.cs fixed it for me.
Calling with chatId only for WorkingMemory

`async Task SearchMemoryAsync(string memoryName)
        {
            var searchResult =
                await this._memoryClient.SearchMemoryAsync(
                    this._promptOptions.MemoryIndexName,
                    query,
                    this.CalculateRelevanceThreshold(memoryName, chatSession!.MemoryBalance),
                    memoryName == this._promptOptions.WorkingMemoryName ? chatId : Guid.Empty.ToString(),
                    memoryName)
                .ConfigureAwait(false);

            foreach (var result in searchResult.Results.SelectMany(c => c.Partitions.Select(p => (c, p))))
            {
                relevantMemories.Add(result);
            }
        }`

**Comment by arvashis** [comment]
That worked for me - Thanks!

**Comment by TaoChenOSU** [comment]
Hello @arvashis, 

Thanks for reporting the bug!

The solution provided above is an ideal solution. We are working to fix this bug properly.
