### ISSUE TITLE
Deployment using the deploy-webapi.ps1 script has failed. HTTP Error 500.30 - ASP.NET Core app failed to start

### ISSUE THREAD

**Issue by huangchao-shanghai** [microsoft/chat-copilot#423]
**Describe the bug**

When deploying with the deploy-webapi.ps1 script, I encountered an error when accessing https://app-copichat-gjkg6vpyfkht6-webapi.azurewebsites.net/healthz.
The code has not been modified in any way. 
How should I proceed to further diagnose the issue?

```
./package-webapi.ps1
./deploy-webapi.ps1 -Subscription  $Subscriptionid  -ResourceGroupName rg-$DeploymentName -DeploymentName $DeploymentName
```

HTTP Error 500.30 - ASP.NET Core app failed to start

</head><body><div id="content"><div class="content-container"><h3>HTTP Error 500.30 - Internal Server Error</h3><h4>The page cannot be displayed because an internal server error has occurred.</h4></div><div class="content-container"><fieldset><h4>Most likely causes:</h4><ul> 	<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul></fieldset></div><div class="content-container"><fieldset><h4>Things you can try:</h4><ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul></fieldset></div>
<div class="content-container"><fieldset><h4>Detailed Error Information:</h4><div id="details-left"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;AspNetCoreModuleV2</td></tr><tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr><tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;aspNetCore</td></tr><tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x8007023e</td></tr>
</table></div><div id="details-right"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://app-copichat-gjkg6vpyfkht6-webapi:80/healthz</td></tr><tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;C:\home\site\wwwroot\healthz</td></tr><tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr><tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr>
</table><div class="clear"></div></div></fieldset></div>
<div class="content-container"><fieldset><h4>More Information:</h4>This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error.<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,30,0x8007023e,14393">View more information &raquo;</a></p><p>Microsoft Knowledge Base Articles:</p>
</fieldset></div></div></body></html>

**Screenshots**
<img width="475" alt="image" src="https://github.com/microsoft/chat-copilot/assets/3233883/392b1b63-1901-4730-9bee-da2b573a593a">

**Comment by TaoChenOSU** [comment]
Hello @huangchao-shanghai, 

Thank you for reporting the issue!

We are also seeing this issue frequently and currently do not have a good solution & explanation for it. Something worth trying is to completely delete the build artifact folders (obj/ and bin/) and rerun the scripts.

We are actively investigating. Feel free to posting further findings and questions here.

**Comment by PlagueHO** [comment]
+1 to this - I've also tried deleting obj/ and /bin folders, but no luck. The previous version I had deployed (a couple of weeks ago) did work just fine.

I do have multiple versions of VS on my machine as well as .NET SDK v7 and v8 previews. Not sure if this matters.

**Comment by phlaz** [comment]
Also still seeing this issue with latest code

**Comment by TaoChenOSU** [comment]
Hello,

If possible, could you please access the Kudu for the webapi (see here: https://learn.microsoft.com/en-us/azure/app-service/resources-kudu). Once you are in, you should see something similar to this:
![image](https://github.com/microsoft/chat-copilot/assets/12570346/57d97238-70e5-44aa-842a-c1f51615cae1)

Then click on **Debug console** and select either option:
![image](https://github.com/microsoft/chat-copilot/assets/12570346/53c0ac85-9799-4f83-8a93-8cc217eac0ae)

In there, you will find the folder **LogFiles**:
![image](https://github.com/microsoft/chat-copilot/assets/12570346/a4c9f878-09cf-4451-8e4a-1c51152d3fba)

Open it, and you will see the event log:
![image](https://github.com/microsoft/chat-copilot/assets/12570346/27482a96-9477-47a2-a30b-df419aace1e2)

Please open the event log, and see if you can spot anything there. Please post any exceptions you see here. There might be a lot, but they are likely recurrent exceptions. 

Service failing to start could be due to misconfiguration or other issues. We can assist you better by knowing what the exception is.

**Comment by glahaye** [comment]
@huangchao-shanghai This issue should now be fixed.  Please try the latest version of the code.
