### ISSUE TITLE
Unable to deploy to Azure: The bicep file needs to be updated to deploy the models

### ISSUE THREAD

**Issue by Dag-Calafell-MCA** [microsoft/chat-copilot#425]
**Describe the bug**
I was having issues with deploy-azure.ps1 and found the version in main.bicep is old.

**Expected behavior**
The deployment should succeed

**Screenshots**
The fix is to update to the latest version, remove the scale setting, and add the SKU setting.  I have tested this fix on ARM and bicep this way:

![image](https://github.com/microsoft/chat-copilot/assets/90263706/4fabe41b-ae4a-426c-bfc9-83cec64b3d17)

![image](https://github.com/microsoft/chat-copilot/assets/90263706/bda15ab4-9234-4922-bdf6-b62a5b98f884)

**Comment by TaoChenOSU** [comment]
Hello @Dag-Calafell-MCA,

Thank you for reporting the issue!

We are also seeing an issue with the deployment script and the Bicep template when deploying without an existing AOAI resource. Could you please provide us the error you saw so that we can better target the two issues.

**Comment by TaoChenOSU** [comment]
@Dag-Calafell-MCA You are more than welcome to submit a PR that contains you fix!

**Comment by glahaye** [comment]
Closing as fixed by PR #508
