### ISSUE TITLE
CosmoDB error PartitionKey doesn't match

### ISSUE THREAD

**Issue by chandanrjit** [microsoft/chat-copilot#426]
**Describe the bug**
Hi All ,  I have followed the https://learn.microsoft.com/en-gb/semantic-kernel/chat-copilot/deploy-to-azure for the deployment () . Deployment was successful.but I got the  cosmodb error  while creating the chat session

**To Reproduce**
1.  Deploy using https://aka.ms/sk-deploy-existing-azureopenai-portal  with CosmoDB true 
2. Deploy the frontend using https://learn.microsoft.com/en-gb/semantic-kernel/chat-copilot/deploy-to-azure#deploy-the-chat-copilot-frontend
3. Open the frontend Url and chat will through an error on /chatSession/create

**Expected behavior**
No Error for /chatSession/create

**Screenshots**
<img width="958" alt="image" src="https://github.com/microsoft/chat-copilot/assets/10242233/fc244ddc-d15b-4fd4-abfa-aba81e067bcc">
**Platform**
 - OS: Mac
 - IDE: VS Code ( Frontend ) 
 - Language: C#
 -  Cloud - Azure 

**Additional context**
Happy to connect online to share the details if Azure Infra is not available to run this .

**Comment by TaoChenOSU** [comment]
Hello @chandanrjit,

Thank you for reporting the issue!

We recently updated the Cosmos DB container partition keys: https://github.com/microsoft/chat-copilot/releases/tag/0.3. This was a breaking change, and you can read more about it here: https://devblogs.microsoft.com/semantic-kernel/chat-copilot-performance-improvements-for-chat-and-messaging-loading/. 

To make sure you are deploying over existing resource that has the old partition key, could you please go to your Cosmos DB instance and confirm? This will help us further diagnose the issue. 

Feel free to post further information here.

**Comment by TaoChenOSU** [comment]
Closing. Feel free to reopen if you have further questions.
