### ISSUE TITLE
Support for deployment slots in webapi and Preview Environments in webapp

### ISSUE THREAD

**Issue by arnoldblake** [microsoft/chat-copilot#428]
Currently the azure deployment scripts do not support a deployment slot parameter. This feature will be beneficial for those who wish to deploy multiple versions of chat-copilot without standing up an entire new set of resources.

Both commands 'az webapp deploy' and 'az webapp config' used by deploy-webapi support the -slot parameter which defaults to 'Production' if not specified. An optional parameter will be made with a default value of Production. Following similar behavior in the deployment scripts the deployment slot would be created if it does not exist by using `az webapp deployment slot list` and `az webapp deployment slot create`

The deploy-webapp script pulls the webapi URL from the resource group deployment at `$deployment.properties.outputs.webapiUrl.value` this value may not be correct if the intent is to use additional deployment slots. To support the change in webapi URL created by the deployment slot an optional parameter in the deploy-webapp script will be created allowing the user to specifiy the url of the webapi. However if a redeployment of the webapp is required in order to access the webapi at a new URL it would be simpler to perform a slot swap on the webapi web app instead. This leads into the requirement for support of swa preview environments.

Static Web Apps do not support the use of deployment slots and instead use Preview Environments. `swa deploy` supports the use of `--env [environment]`. My understanding is that this will create a new preview environment with a URL in the form of `<DEFAULT_HOST_NAME>-<BRANCH_OR_ENVIRONMENT_NAME>.<LOCATION>.azurestaticapps.net`. An optional parameter in deploy-webapp will be created to support the use of the Preview Environments.

**Comment by arnoldblake** [comment]
I will take a go at implementing these features.

**Comment by matthewbolanos** [comment]
Thanks! Please create a PR once you have one ready.

**Comment by glahaye** [comment]
Thanks for your contribution!
