### ISSUE TITLE
Help Enabling Cognitive Search

### ISSUE THREAD

**Issue by HiltonGiesenow** [microsoft/chat-copilot#429]
I guess this request would fall under "Documentation" - I'm new to Semantic Kernel & Chat Copilot and trying to integrate an existing Cognitive Search instance. Ideally I'd like to use a Custom Question Answering index as a first step. At first, I thought all I needed to do was configure:
```
 "AzureCognitiveSearch": {
        "Auth": "ApiKey",
        "APIKey": "[My Api Key]
        "Endpoint": "https://[myresource].search.windows.net"
      },
 ```
 
 But that got me nowhere, so I tried also:
 
 ```
 "Retrieval": {
      "VectorDbType": "AzureCognitiveSearch",
...
    },
````

But still nothing. From what I was able to find, that seemed to be all I needed to do? This is per https://github.com/microsoft/chat-copilot#optional-run-the-memory-pipeline . If possible, I'd really appreciate some guidance, but I'm also happy to assist with submitting a documentation PR based on that.

On a related note, I wasn't sure if this is the best place for questions, but there doesn't seem to be much happening at https://stackoverflow.com/questions/tagged/semantic-kernel and https://stackoverflow.com/questions/tagged/chat-copilot doesn't even exist so I created it now.

**Comment by TaoChenOSU** [comment]
Hi @HiltonGiesenow,

Thank you for your post!

You will also need to set `SemanticMemory:DataIngestion:VectorDbTypes` to `["AzureCognitiveSearch"]`.

In addition, if you have existing indexes that are not created by Chat Copilot, Chat Copilot will not query those indexes as Chat Copilot associates data with chat IDs. You can upload a document from the webapp and see the vector data that's generated.
![image](https://github.com/microsoft/chat-copilot/assets/12570346/07acfbc5-673f-486e-adc2-eb8ba8882f23)

Feel free to post further questions if you have any!

**Comment by HiltonGiesenow** [comment]
ok thanks, will test it out. I only realised afterwards Cognitive Search's role in this stack - originally I thought it was sort of as a searchable resource.
