### ISSUE TITLE
No run parameter -PackageFilePath in deploy-webapp.ps1

### ISSUE THREAD

**Issue by Josegc89** [microsoft/chat-copilot#430]
Hi,

When I run the script deploy-webapp.ps1 the bash show an error over that parameter -PackageFilePath is incorrect. 

I can see that PowerShell no use that parameter, what is the alternative???

![image](https://github.com/microsoft/chat-copilot/assets/146710697/ce676515-c84f-46d7-909e-f045a45a3bdf)

Thanks for your answers

**Comment by UTKBlake** [comment]
I do not believe that you need to use -PackageFilePath.

**Comment by TaoChenOSU** [comment]
Hello @Josegc89,

Thank you for posting the issue!

As @UTKBlake mentioned, the deploy-webapp.ps1 script doesn't take a parameter named `-PackageFilePath`. 

Feel free to reopen this issue if you see other errors.
