### ISSUE TITLE
Github Autopilot Chat Error

### ISSUE THREAD

**Issue by Ceysie** [microsoft/chat-copilot#431]
I just send / ask anything and its say "There was a problem Completing your requests" and the output is just this "[CopilotSessionProvider Information] Begin sending message (ConversationId:68076fb2-c799-467e-8eb2-2ceccb1c8c93, CorrelationId:21c91d38-24cb-4761-8014-ac2aab7c7e9e, MessageId: ec1b6317-790c-447b-b806-2dfc6075ede2)
[CopilotSessionProvider Information] Request content: "Wow"
"
![image](https://github.com/microsoft/chat-copilot/assets/60301429/0489c52d-c6cf-417b-b0ee-c4118a27ca5d)

**Comment by Ceysie** [comment]
any fix?

**Comment by matthewbolanos** [comment]
Are you referring to Github Copilot or the Semantic Kernel Chat Copilot? This is the repo for Chat Copilot, which is a reference app built on top of Semantic Kernel.

It looks like you're referring to Github, so I'll be closing this issue. Please reopen if you are referring to an issue with Chat Copilot.
