### ISSUE TITLE
Chatbot not able to answer questions from search index 

### ISSUE THREAD

**Issue by carlaelisa** [microsoft/chat-copilot#440]
**Describe the bug**
When deploying the solution i observed that several indexes were created in my search service. I created a search index based on some documents myself and was expecting that when asking a question based on the documents that are behind the index to get a proper answer. However, it seems like the chatbot can not retrieve information from the search index. 

**To Reproduce**
1. Go to 'indexes'
2. Click on 'new index' with data that is uploaded on blob storage 
3. Go back to the Chat and ask a question based on new index 
![image](https://github.com/microsoft/chat-copilot/assets/62431273/67bd4c97-0d90-492d-8a1d-299b7e96242c)

![image](https://github.com/microsoft/chat-copilot/assets/62431273/59fb3196-36d6-400e-83f9-1e39c0d341b2)

**Expected behavior**
I'd expected a description of what a SCHUBAN is because it is cleary written in the documents that i connected with the index. 

When using the index in the Azure OpenAI preview capability "Bring your own data" and connect it to my index. It generates the correct answer: 

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by TaoChenOSU** [comment]
Hello @carlaelisa,

Thank you for posting!

Chat Copilot only works with an index that is configured when the service starts: https://github.com/microsoft/chat-copilot/blob/main/webapi/Options/PromptsOptions.cs#L102. Additionally, it will only search for data entries with specific tags: https://github.com/microsoft/chat-copilot/blob/main/webapi/Extensions/ISemanticMemoryClientExtensions.cs#L83. Therefore, it won't work if you manually create an index and populate it with data.

Please use the document upload feature in Chat Copilot to chat with your data.
![image](https://github.com/microsoft/chat-copilot/assets/12570346/0c2f19f8-08b7-4710-847d-3b6b16bd5e69)

You can also read more here on troubleshooting if you see further issues: https://github.com/microsoft/chat-copilot/issues/407.

Feel free to post more questions or issues if you see any.
