### ISSUE TITLE
Could not validate OpenAI manifest

### ISSUE THREAD

**Issue by fredderf204** [microsoft/chat-copilot#452]
**Describe the bug**
I am running a plugin locally and when I try to enable it, I get a "Could not validate OpenAI manifest" error. I know chat copilot is hitting my local server, as I can see the 200 OK to the http://localhost:8000/.well-known/ai-plugin.json endpoint. Is there a way to see why my plugin is not valid? Is there a logfile I can check?

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone https://github.com/Azure-Samples/openai-plugin-fastapi and run locally 
2. In chat copilot Click on Plugins
3. Next click on Add Custom Plugin
4. Enter http://localhost:8000 as the domain

**Expected behaviour**
The custom plugin to be enabled in Chat copilot

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/13340710/75463fb5-e29a-423f-b96a-d7412a8b07d9)

**Platform**
 - OS: Windows
 - IDE: VSCode
 - Language: Python

**Additional context**
ai-plugin.json
---
{
  "schema_version": "v1",
  "name_for_model": "contosoproducts",
  "name_for_human": "Product Search",
  "description_for_model": "Plugin for searching through Contoso's outdoor and recreational products. Use it whenever a user asks about products or activities related to camping, hiking, climbing or camping.",
  "description_for_human": "Search through Contosos wide range of outdoor and recreational products",
  "auth": {
    "type": "none"
  },
  "api": {
    "type": "openapi",
    "url": "$host/.well-known/openapi.yaml"
  },
  "logo_url": "$host/.well-known/logo.png",
  "contact_email": "support@example.com",
  "legal_info_url": "https://www.example.com/legal/"
}
---
$host gets extrapolated to localhost at runtime.

**Comment by TaoChenOSU** [comment]
Hello @fredderf204,

Thank you for reporting the issue!

When you say you can see the 200 OK to the http://localhost:8000/.well-known/ai-plugin.json, is it from the app or the browser? 

Copilot Chat indicated that the error was "Failed to fetch http://localhost:8000/.well-known/ai-plugin.json". This error could be due to CORS restrictions. Could you confirm?

**Comment by fredderf204** [comment]
Thank you for your quick reply.

The issue was with CORS on when running https://github.com/Azure-Samples/openai-plugin-fastapi locally.
