### ISSUE TITLE
Search Indexes are not being created

### ISSUE THREAD

**Issue by GryBsh** [microsoft/chat-copilot#453]
**Describe the bug**
Using both Qdrant and Cognitive Search on Docker, Chat CoPilot is not ensuring indexes are created, so all operations fail.

**To Reproduce**
1. Fix the webapi docker file so it builds the shared project
2. Deploy the docker stack from the docker-compose file
3. Goto Chat CoPilot
4. Ask any question or make any statement

**Expected behavior**
Chat memory will be committed properly when using Chat CoPilot.

**Screenshots**

**Platform**
 - OS: Linux
 - IDE: N/A
 - Language: C#
 - Source: main branch

**Additional context**

**Comment by GryBsh** [comment]
I can get qdrant to work by manually creating the missing index, I derived the size from the vector mismatch errors in the webapi logs after just creating one shot-in-the-dark style: 

`curl -X PUT -H 'Content-Type: application/json' -d '{"vectors":{"size":1536,"distance":"Cosine"}}' http://localhost:6333/collections/chatmemory`

**Comment by TaoChenOSU** [comment]
Hi @GryBsh,

Thanks for reporting the issue!

To assist you better, could you let us know if Chat Copilot shows any error messages for when index creation fails. In addition, could you also let us know what you needed to fix in the docker file?

**Comment by GryBsh** [comment]
There were no error messages for the indexs failing to be created, just errors when they were not found.
There was a global-documents index though. Completely fresh and empty qdrant every time.

For the docker file, you need to copy over both project and build them:
```docker
WORKDIR /source/webapi
COPY webapi/*.csproj /source/webapi/
COPY shared/*.csproj /source/shared/
RUN dotnet restore --use-current-runtime

COPY webapi/. /source/webapi/
COPY shared/. /source/shared/
RUN dotnet publish --use-current-runtime --self-contained false --no-restore -o /app
```

**Comment by GryBsh** [comment]
So I think this is the error for index creation:
```
cc_api_1  | fail: Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantVectorDbClient[0]
cc_api_1  |       Request for vector with payload ID failed Response status code does not indicate success: 500 (Internal Server Error).
cc_api_1  |       Microsoft.SemanticKernel.Diagnostics.HttpOperationException: Response status code does not indicate success: 500 (Internal Server Error).
cc_api_1  |        ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
cc_api_1  |          at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
cc_api_1  |          at HttpClientExtensions.SendWithSuccessCheckAsync(HttpClient client, HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
cc_api_1  |          --- End of inner exception stack trace ---
cc_api_1  |          at HttpClientExtensions.SendWithSuccessCheckAsync(HttpClient client, HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
cc_api_1  |          at HttpClientExtensions.SendWithSuccessCheckAsync(HttpClient client, HttpRequestMessage request, CancellationToken cancellationToken)
cc_api_1  |          at Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantVectorDbClient.ExecuteHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
cc_api_1  |          at Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantVectorDbClient.GetVectorByPayloadIdAsync(String collectionName, String metadataId, Boolean withVector, CancellationToken cancellationToken)
cc_api_1  | fail: CopilotChat.WebApi.Services.MemoryMigration.ChatMemoryMigrationService[0]
cc_api_1  |       Error migrating chat memories
cc_api_1  |       Microsoft.SemanticKernel.Diagnostics.HttpOperationException: Response status code does not indicate success: 500 (Internal Server Error).
cc_api_1  |        ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
cc_api_1  |          at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
cc_api_1  |          at HttpClientExtensions.SendWithSuccessCheckAsync(HttpClient client, HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
cc_api_1  |          --- End of inner exception stack trace ---
cc_api_1  |          at HttpClientExtensions.SendWithSuccessCheckAsync(HttpClient client, HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
cc_api_1  |          at HttpClientExtensions.SendWithSuccessCheckAsync(HttpClient client, HttpRequestMessage request, CancellationToken cancellationToken)
cc_api_1  |          at Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantVectorDbClient.ExecuteHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
cc_api_1  |          at Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantVectorDbClient.GetVectorByPayloadIdAsync(String collectionName, String metadataId, Boolean withVector, CancellationToken cancellationToken)
cc_api_1  |          at Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore.ConvertFromMemoryRecordAsync(String collectionName, MemoryRecord record, CancellationToken cancellationToken)
cc_api_1  |          at Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore.UpsertAsync(String collectionName, MemoryRecord record, CancellationToken cancellationToken)
cc_api_1  |          at Microsoft.SemanticKernel.Memory.SemanticTextMemory.SaveInformationAsync(String collection, String text, String id, String description, String additionalMetadata, CancellationToken cancellationToken)
cc_api_1  |          at CopilotChat.WebApi.Services.MemoryMigration.ChatMemoryMigrationService.<>c__DisplayClass9_0.<<InternalMigrateAsync>g__SetTokenMemory|2>d.MoveNext() in /source/webapi/Services/MemoryMigration/ChatMemoryMigrationService.cs:line 137
cc_api_1  |       --- End of stack trace from previous location ---
cc_api_1  |          at CopilotChat.WebApi.Services.MemoryMigration.ChatMemoryMigrationService.InternalMigrateAsync(CancellationToken cancellationToken) in /source/webapi/Services/MemoryMigration/ChatMemoryMigrationService.cs:line 79
cc_api_1  |          at CopilotChat.WebApi.Services.MemoryMigration.ChatMemoryMigrationService.MigrateAsync(CancellationToken cancellationToken) in /source/webapi/Services/MemoryMigration/ChatMemoryMigrationService.cs:line 58
```
I've also discovered creating the index only works if I create it after I've already logged into the frontend, and allowed it to first create the global-documents collection.

**Comment by GryBsh** [comment]
It looks like if you leave it running for some period of time, it sorts itself out. Not sure if thats the intended behavior.

**Comment by TaoChenOSU** [comment]
Looks like it's the memory migration service that is reporting error. We will take a further look. 

Were you able to chat or upload documents with the present of this error?

**Comment by crickman** [comment]
Is this still an issue for you?  W/ 500 Error, I'm wondering if something may be misconfigured.  Have you had success with the appication prior to this?

**Comment by sayanghosh123** [comment]
Hey @crickman -
I seem to be running into the same issue. I've deployed the site and code using the scripts provided. No errors.

When I try to open the chat copilot site it throws an error
"Looking for your backend
This sample expects to find a Semantic Kernel service from webapi/ running at https://app-*******-webapi.azurewebsites.net/"

When I access the EventLog.xml file via Kudu, I see the following errors - 

Category: CopilotChat.WebApi.Services.MemoryMigration.ChatMigrationMonitor EventId: 0 SpanId: REDACTED TraceId: REDACTED ParentId: 0000000000000000 RequestId: REDACTED RequestPath: /maintenanceStatus ActionId: REDACTED ActionName: CopilotChat.WebApi.Controllers.MaintenanceController.GetMaintenanceStatusAsync (CopilotChatWebApi) Failure searching collections: global-documents The index 'global-documents' for service 'acs-copichat-REDACTED' was not found. Status: 404 (Not Found) Content: {"error":{"code":"","message":"The index 'global-documents' for service 'acs-copichat-REDACTED' was not found."}} Headers: Server: Microsoft-IIS/10.0 Strict-Transport-Security: REDACTED client-request-id: REDACTED x-ms-client-request-id: REDACTED request-id: REDACTED elapsed-time: 1 Date: Sun, 12 Nov 2023 11:21:11 GMT Content-Length: 118 Content-Type: application/json; charset=utf-8 Content-Language: REDACTED

Category: CopilotChat.WebApi.Services.MemoryMigration.ChatMemoryMigrationService EventId: 0 SpanId: REDACTED TraceId: REDACTED ParentId: REDACTED RequestId: REDACTED RequestPath: /maintenanceStatus Error migrating chat memories Exception: Microsoft.SemanticKernel.Diagnostics.HttpOperationException: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again. Status: 404 (Not Found) ErrorCode: DeploymentNotFound Content: {"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}} Headers: apim-request-id: REDACTED x-ms-client-request-id: REDACTED Strict-Transport-Security: REDACTED X-Content-Type-Options: REDACTED x-ms-region: REDACTED Date: Sun, 12 Nov 2023 11:21:11 GMT Content-Length: 198 Content-Type: application/json ---> Azure.RequestFailedException: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again. Status: 404 (Not Found) ErrorCode: DeploymentNotFound Content: {"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}} Headers: apim-request-id: REDACTED x-ms-client-request-id: REDACTED Strict-Transport-Security: REDACTED X-Content-Type-Options: REDACTED x-ms-region: REDACTED Date: Sun, 12 Nov 2023 11:21:11 GMT Content-Length: 198 Content-Type: application/json at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken) at Azure.AI.OpenAI.OpenAIClient.GetEmbeddingsAsync(String deploymentOrModelName, EmbeddingsOptions embeddingsOptions, CancellationToken cancellationToken) at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request) --- End of inner exception stack trace --- at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request) at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetEmbeddingsAsync(IList`1 data, CancellationToken cancellationToken) at Microsoft.SemanticKernel.AI.Embeddings.EmbeddingGenerationExtensions.GenerateEmbeddingAsync[TValue,TEmbedding](IEmbeddingGeneration`2 generator, TValue value, CancellationToken cancellationToken) at Microsoft.SemanticKernel.Memory.SemanticTextMemory.SaveInformationAsync(String collection, String text, String id, String description, String additionalMetadata, CancellationToken cancellationToken) at CopilotChat.WebApi.Services.MemoryMigration.ChatMemoryMigrationService.<>c__DisplayClass9_0.<<InternalMigrateAsync>g__SetTokenMemory|2>d.MoveNext() in C:\Users\REDACTED\.........\chat-copilot\webapi\Services\MemoryMigration\ChatMemoryMigrationService.cs:line 137 --- End of stack trace from previous location --- at CopilotChat.WebApi.Services.MemoryMigration.ChatMemoryMigrationService.InternalMigrateAsync(CancellationToken cancellationToken) in C:\Users\REDACTED\\.........\chat-copilot\webapi\Services\MemoryMigration\ChatMemoryMigrationService.cs:line 78 at CopilotChat.WebApi.Services.MemoryMigration.ChatMemoryMigrationService.MigrateAsync(CancellationToken cancellationToken) in C:\Users\REDACTED\\.........\chat-copilot\webapi\Services\MemoryMigration\ChatMemoryMigrationService.cs:line 63

Do you want me to reopen this bug, or is this a different issue and should I open it directly?

**Comment by SvenAries** [comment]
I am having the exact same problem. Deployed the project to azure, using the template, but webapp keeps showing the message that it's waiting for the semantic kernel service.

When looking into the application log, I see the same error as reported by @sayanghosh123 

Someone else encountering this or encountered this and knows how to fix this?

**Comment by glahaye** [comment]
This problem is now solved in the latest version of the code.
