### ISSUE TITLE
when excute the plan, alert:Unable to execute plan. Details: Error: 404: Not Found

### ISSUE THREAD

**Issue by zhongerxin** [microsoft/chat-copilot#454]
![image](https://github.com/microsoft/chat-copilot/assets/8215057/ac12b063-d6cc-4dc4-9331-1961dabaa258)

**Comment by gitri-ms** [comment]
Thanks @zhongerxin - this appears to be a regression from a recent change, I'll have a fix shortly!

**Comment by zhongerxin** [comment]
> Thanks @zhongerxin - this appears to be a regression from a recent change, I'll have a fix shortly!
Thank you，I was wondering why there's no 'processPlan' in the backend interface.

![image](https://github.com/microsoft/chat-copilot/assets/8215057/5a356422-0707-490c-ad98-8286d056969f)
