### ISSUE TITLE
Unable to delete chat sessions and associated memories.

### ISSUE THREAD

**Issue by lpmulholland** [microsoft/chat-copilot#456]
**Describe the bug**
I have been unable to delete chat sessions in web app.

**To Reproduce**

Click on the Delete icon next to the chat you wish to delete.

Confirm Delete.
Error presented explaining memories cannot be deleted from chat.

**Expected behavior**

I'd expect the chat to be deleted with any associated memories and a success message.

**Screenshots**
![deleteChat](https://github.com/microsoft/chat-copilot/assets/146981129/fc2cbfce-075c-461a-850a-ff237c90bbfc)

**Platform**
 - OS: Windows 10
 - IDE: Visual Studio 2022
 - Language: c#
 - Source: main branch of repository

**Additional context**

This is in ISemanticMemoryClientExtensions.cs at line 186.

`await memoryClient.DeleteDocumentAsync(indexName, memory.Link,  cancellationToken);`

should read

`await memoryClient.DeleteDocumentAsync(memory.Link, indexName, cancellationToken);`

as per the interface implementation of 'DeleteDocumentAsync' from ISemanticMemoryClient in Memory.cs

The reversed parameters causes a 404 when searching the points in the Quadrant DB Client.

**Comment by TaoChenOSU** [comment]
Hello @lpmulholland, 

Thank you for reporting the issue!

Could you please post the error message here too?

**Comment by lpmulholland** [comment]
Unable to delete chat {Chat about AI}. Some or all resources associated with this chat couldn't be deleted. Please try again.

![deleteChatError](https://github.com/microsoft/chat-copilot/assets/146981129/eff03810-9d36-4149-893c-77bdec31bd3b)

**Comment by TaoChenOSU** [comment]
Hello @lpmulholland, thank you for posting the error message! We are still unable to reproduce the error. 

We are hoping you could provide more information:
1. Did you upload any document to the chat?
2. Did the chat generate any memory? (You can check in the persona tab to see if there is content in Working & Long-term memories)
3. Which vector database did you configure Chat Copilot to use?

**Comment by lpmulholland** [comment]
Hello,

Documents were uploaded to the chat session.
A Qdrant database was used as the vector DB store.
The chat did generate memories.

Regards

**Comment by TaoChenOSU** [comment]
Thanks for the details!

I was able to reproduce the error with Qdrant. And we are working to address the issue. Stay tuned!

**Comment by TaoChenOSU** [comment]
Link this to an enhancement that SM is going make: https://github.com/microsoft/semantic-memory/issues/80

**Comment by crickman** [comment]
https://github.com/microsoft/chat-copilot/pull/585
