### ISSUE TITLE
Planer cannot generate the correct request

### ISSUE THREAD

**Issue by zhongerxin** [microsoft/chat-copilot#458]
In cases where the API for the plugin is complex, Plan cannot generate the correct request. but ChatGPT can be correct, should I use GPT4 ?
SCHEMA
![image](https://github.com/microsoft/chat-copilot/assets/8215057/83b6167a-ec36-42eb-88be-5646e16cabb4)

bad request
![image](https://github.com/microsoft/chat-copilot/assets/8215057/dfdefcae-75f8-47b5-becb-40ace6f41465)

correct request (human edit)
![image](https://github.com/microsoft/chat-copilot/assets/8215057/71a99567-1996-401a-a022-2ae4b6fdc2ae)

**Comment by TaoChenOSU** [comment]
Hello @zhongerxin,

Thank you for reporting the issue!

The planner may not always provide the correct inputs to plugins, as the models are indeterministic. 

What was the model you were using? The better the model, the more likely you will see correct inputs. But that doesn't necessary mean you have to use GPT4, which is expensive. We have seen good performance from gpt-35-turbo as well.

**Comment by zhongerxin** [comment]
> Hello @zhongerxin,
> 
> Thank you for reporting the issue!
> 
> The planner may not always provide the correct inputs to plugins, as the models are indeterministic.
> 
> What was the model you were using? The better the model, the more likely you will see correct inputs. But that doesn't necessary mean you have to use GPT4, which is expensive. We have seen good performance from gpt-35-turbo as well.

in this case I use gpt3.5-turbo

**Comment by TaoChenOSU** [comment]
Have you tried with GPT-4? If so, can you let us know what the result was with GPT-4?

We are investigating this issue the planner not providing the correct parameters internally. The planner is known to have the limitation where it cannot handle complex types well due to the lack of function typing.

I will link the issue here later.

**Comment by zhongerxin** [comment]
@TaoChenOSU 
Still not work
![image](https://github.com/microsoft/chat-copilot/assets/8215057/f3a2ed2e-6942-4bd6-a5dd-8cf3c8bf0945)
![image](https://github.com/microsoft/chat-copilot/assets/8215057/fad15a0f-acdf-46a0-a921-dd7d3a7ac2a7)

**Comment by TaoChenOSU** [comment]
@zhongerxin Thanks for the information! We will take a further look into this.

**Comment by TaoChenOSU** [comment]
SK epic that could potentially address this issue: https://github.com/orgs/microsoft/projects/866/views/31?pane=issue&itemId=41242062. 

Feel free to also play around with the [ToManualString](https://github.com/microsoft/semantic-kernel/blob/7b46188f6f32eb8f29ff5f586ca54cd3f09bc191/dotnet/src/Planners/Planners.Core/Extensions/FunctionViewExtensions.cs#L19) function to try to get the type injected into the prompt to help guide the model in constructing the payload better.
