### ISSUE TITLE
Remove the option to stand up a new AOAI resource by our deployment

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/chat-copilot#461]
Currently, if the user doesn't provide an endpoint and a key to an existing AOAI resource, our deployment pipeline will create one. This could potentially cause some issues as not some regions do not have the AOAI resource.

**Comment by glahaye** [comment]
Then, the user can just provide a key and everything is fine, no?

**Comment by TaoChenOSU** [comment]
Yes. But some of them think they can create a new AOAI resource with our scripts, which could potentially run into quota issue.

**Comment by glahaye** [comment]
We still need to let people create AOAI resources when they can, though!

**Comment by glahaye** [comment]
Talked to @alliscode and he said we should keep the possibility of creating AOAI resources.

Instead, I'll document the limitations due to availability (or lack thereof) of AOAI resources in various regions.
