### ISSUE TITLE
Only ship the required version of leptonica-1.82.0.dll and tesseract50.dll

### ISSUE THREAD

**Issue by glahaye** [microsoft/chat-copilot#469]
Right now, both the x86 and x64 versions are package with all builds.

This add about 2 megs of unneeded binaries to our package files

**Comment by crickman** [comment]
@glahaye - What's the total size of the package file?

**Comment by glahaye** [comment]
@crickman Around 68 megs.  This change would shave off about 2.  Not the highest priority, but nice to have.

**Comment by crickman** [comment]
Turns out the nuget package is dynamically including these assets and its problematic to try and exclude them form the project file for two reasons:

1. Pathing (outside of repo)
1. Exclusion ignored in anycase
```
  <ItemGroup>
    <None Remove="C:\Users\crickman\.nuget\packages\tesseract\5.2.0\build\\..\x86\leptonica-1.82.0.dll" />
    <None Remove="C:\Users\crickman\.nuget\packages\tesseract\5.2.0\build\\..\x86\tesseract50.dll" />
  </ItemGroup>
```

It is possible to exclude assets, but not selectively:

```
    <PackageReference Include="Tesseract" Version="5.2.0">
      <IncludeAssets>none</IncludeAssets>
    </PackageReference>
```
