### ISSUE TITLE
Hide Cosmos details other than the connection string from settings

### ISSUE THREAD

**Issue by glahaye** [microsoft/chat-copilot#470]
We shouldn't let users specify Cosmos details other than the connection string. There's no reason why someone would need to change them and removing them from appsettings and hardcoding them would simplify the users' life.

More specifically, I'm talking about these settings:

      "Database": "CopilotChat",
      // IMPORTANT: Each container requires a specific partition key. Ensure these are set correctly in your CosmosDB instance.
      // See details at ./README.md#1-containers-and-partitionkeys
      "ChatSessionsContainer": "chatsessions",
      "ChatMessagesContainer": "chatmessages",
      "ChatMemorySourcesContainer": "chatmemorysources",
      "ChatParticipantsContainer": "chatparticipants"

**Comment by crickman** [comment]
Yeah, I noticed this was a bit "overkill" as well...

**Comment by jzingh98** [comment]
Yes please do this. Also the instructions for Cosmos setup aren't very clear (i.e. what type of Cosmos DB should be used?)
