### ISSUE TITLE
MySQL implementation of DbContext/IStorageContext

### ISSUE THREAD

**Issue by Ryangr0** [microsoft/chat-copilot#478]
I would like for there to be an option in the persistency layer that is not Cosmos (because it's a paid service) and not Filesystem or Volatile for obvious reasons. I got this to work in my local project, with some caveats (repositories, and therefore seemingly IStorageContext, is registered to be a singleton. That does not play well with the transactional nature of MySQL). I'm making this issue to check to see if there is an audience for this functionality.

Also a question. What has been decided about EF for the data model layer?

**Comment by Rainson12** [comment]
Hi @Ryangr0,
I have already implemented a EF Layer for mariadb which should also work for mysql. Have a look at https://github.com/microsoft/chat-copilot/issues/242#issuecomment-1740899503

**Comment by TaoChenOSU** [comment]
Hello @Ryangr0, 

Thanks for your post!

You are more than welcome to submit PRs if you think it's ready!

**Comment by matthewbolanos** [comment]
Closing this issue since the Chat Copilot team is not ready to merge a feature like this in.
