### ISSUE TITLE
"Unable to load user info" on refresh when deployed to Azure

### ISSUE THREAD

**Issue by dehoward** [microsoft/chat-copilot#485]
**Describe the bug**
User info object is not correctly set on reload.

**To Reproduce**
1. Deploy app to Azure
2. Login using AAD
3. Refresh

**Expected behavior**
User is still logged in

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/52973358/1fca6ae0-b118-46ef-ab65-e3a0c6778acd)

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by TaoChenOSU** [comment]
@glahaye Could you take a look at this? I think it's related to the removal of the static webapp.
