### ISSUE TITLE
Question: How can I set planState of `ProposedPlan` to  `PlanState.PlanApprovalRequired`  on server side and then make user can Approve and Trigger Processing the plan in frontend?

### ISSUE THREAD

**Issue by AwesomeYuer** [microsoft/chat-copilot#486]
**Describe the bug**
The `enum` type of `PlanState` has no value of  `PlanState.PlanApprovalRequired` on sever side webapi.

![image](https://github.com/microsoft/chat-copilot/assets/1026479/93f5555a-bcdd-4ff1-b295-8cda4bc79760)

but in frontend use it

![image](https://github.com/microsoft/chat-copilot/assets/1026479/b0cd695c-5664-4091-95a0-0bf0999b2a3e)

I did some temporary modification  both client and server, the screenshoot as below:

![da6f6d75d1a5f665daad0ca0b48f87e](https://github.com/microsoft/chat-copilot/assets/1026479/b552ae41-6914-44a7-a565-173af0f5d4ec)

I am not sure , are there other normal way to implement or invoke/trigger it?

Would you help to resolve it?

Thanks in advance

**Comment by TaoChenOSU** [comment]
Hello @AwesomeYuer,

Thank you for posting the question!

The `PlanApprovalRequired` is just a temporary flag for the frontend to indicate that the plan is waiting for action. In the backend, the plan state is `NoOp` while it's waiting for an action.

I am not sure what you'd like to achieve? Could you elaborate on what you meant by "other normal way"?
