### ISSUE TITLE
Chat can't show response when using Stepwise planner with plugins

### ISSUE THREAD

**Issue by jakobehn** [microsoft/chat-copilot#489]
**Describe the bug**
When using the Stepwise planner, and asking a question that involves one or more plugins, the chat always respond with something like:

_"I'm sorry for the confusion, but as an AI, I don't have access to your personal calendar or scheduling details. I recommend checking your preferred scheduling tool or application for this information."_

I can see in the API logs that it has indeed fetched the correct data and generated a correct answer, but it is not shown as a response in the chat session.

**To Reproduce**
1. Set **_Planner::Type_** to **_Stepwise_** in appsettings.json
2. Enable a plugin and ask a question that will use that plugin
3. Bot responds with "I'm sorry for the confusion, but as an AI, I don't have access to your personal calendar or scheduling details. I recommend checking your preferred scheduling tool or application for this information."
4. A look at the logs will show that it has indeed called the plugin and generated a response

**Expected behavior**
The final answer should be shown as a response

**Screenshots**
Output shown in chat session:
![image](https://github.com/microsoft/chat-copilot/assets/847244/c566dafb-1bbc-43ef-8f73-5c3edb415f08)

In prompt view, we can see that it actually did extract and summarized the correct response (using a custom plugin)
![image](https://github.com/microsoft/chat-copilot/assets/847244/41c4b10c-8984-44bd-825c-f42ad23c8926)

**Comment by teresaqhoang** [comment]
Hey @jakobehn, can you send me a screenshot of what the planner result message looks like under the raw content tab in prompt details?

**Comment by jakobehn** [comment]
Actually, the raw content tab doesn't show the planner result at all:

![image](https://github.com/microsoft/chat-copilot/assets/847244/64980db5-e918-4411-a20a-214c36a901d6)


Here is the relevant API log output in case that helps:

Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://localhost:40443/chats/cbfb58e1-42ed-4a37-ac25-7759e600f505/messages application/json 154
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Action: GetCompletionsAsync. Azure OpenAI Deployment Name: gpt-4-32k.
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Prompt tokens: 168. Completion tokens: 4. Total tokens: 172.
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Action: GetCompletionsAsync. Azure OpenAI Deployment Name: gpt-4-32k.
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Prompt tokens: 389. Completion tokens: 14. Total tokens: 403.
info: Microsoft.SemanticKernel.SkillDefinition.InstrumentedSKFunction[0]
      StepwisePlanner_Excluded.ExecutePlan: Function execution started.
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Action: GetChatCompletionsAsync. Azure OpenAI Deployment Name: gpt-4-32k.
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Prompt tokens: 741. Completion tokens: 61. Total tokens: 802.
info: Microsoft.SemanticKernel.Planning.StepwisePlanner[0]
      Thought: To find out the number of customers, I can use the ActiveCRM.GetCustomers function. This function does not require any parameters, so I can call it directly. The result should give me a list of all customers, and I can count the number of customers from this list.
info: Microsoft.SemanticKernel.Planning.StepwisePlanner[0]
      Action: No action to take
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Action: GetChatCompletionsAsync. Azure OpenAI Deployment Name: gpt-4-32k.
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Prompt tokens: 806. Completion tokens: 15. Total tokens: 821.
info: Microsoft.SemanticKernel.Planning.StepwisePlanner[0]
      Action: ActiveCRM.GetCustomers({}).
info: Microsoft.SemanticKernel.Planning.StepwisePlanner[0]
      Observation: {
        "content": "[\u0022Google\u0022,\u0022Microsoft\u0022,\u0022Amazon\u0022,\u0022Facebook\u0022,\u0022Netflix\u0022,\u0022Spotify\u0022,\u0022LinkedIn\u0022,\u0022Twitter\u0022,\u0022Uber\u0022,\u0022Lyft\u0022,\u0022Instagram\u0022,\u0022Snapchat\u0022,\u0022Airbnb\u0022,\u0022Slack\u0022,\u0022Zoom\u0022,\u0022Salesforce\u0022,\u0022Adobe\u0022,\u0022Oracle\u0022,\u0022Nvidia\u0022,\u0022IBM\u0022]",
        "contentType": "application/json; charset=utf-8"
      }
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Action: GetChatCompletionsAsync. Azure OpenAI Deployment Name: gpt-4-32k.
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Prompt tokens: 1022. Completion tokens: 44. Total tokens: 1066.
info: Microsoft.SemanticKernel.Planning.StepwisePlanner[0]
      Final Answer: We currently have 20 customers.
info: Microsoft.SemanticKernel.SkillDefinition.InstrumentedSKFunction[0]
      StepwisePlanner_Excluded.ExecutePlan: Function execution status: Success
info: Microsoft.SemanticKernel.SkillDefinition.InstrumentedSKFunction[0]
      StepwisePlanner_Excluded.ExecutePlan: Function execution finished in 9303ms
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Action: GetStreamingChatCompletionsAsync. Azure OpenAI Deployment Name: gpt-4-32k.
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Action: GetCompletionsAsync. Azure OpenAI Deployment Name: gpt-4-32k.
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Prompt tokens: 601. Completion tokens: 178. Total tokens: 779.
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Action: GetCompletionsAsync. Azure OpenAI Deployment Name: gpt-4-32k.
info: Microsoft.SemanticKernel.Connectors.AI.OpenAI.ChatCompletion.AzureChatCompletion[0]
      Prompt tokens: 595. Completion tokens: 183. Total tokens: 778.
info: CopilotChat.WebApi.Skills.ChatSkills.ChatSkill[0]
      Unable to extract semantic memory for WorkingMemory: ''' is an invalid start of a value. Path: $.items[5].label | LineNumber: 23 | BytePositionInLine: 15.. Continuing...

**Comment by TaoChenOSU** [comment]
@jakobehn Thanks for providing the details!

@teresaqhoang It didn't prompt the user for approving a plan, but it looks like a plan was executed.

**Comment by samleegithub** [comment]
> @jakobehn Thanks for providing the details!
> 
> @teresaqhoang It didn't prompt the user for approving a plan, but it looks like a plan was executed.

@TaoChenOSU, I noticed that it prompts the user to approve a plan for the ActionPlanner and SequentialPlanner but it doesn't do it for the StepwisePlanner. I assumed that this was intentionally implemented this way because the StepwisePlanner interatively determines the next step in the plan based on the latest results of the previous steps. This means that there is no plan steps for the user to approve.

**Comment by jakobehn** [comment]
@samleegithub Yes, I assume that this was intentional. My issue was about the fact that the chat doesn't show the final result, but instead shows the "error message" shown above.

**Comment by teresaqhoang** [comment]
@samleegithub yes correct, the Stepwise Planner iteratively executes actions and learns from observations, and we don't currently have a mechanism for user intervention before the Stepwise Planner executes an action without interrupting the loop of thought, action, and observation. 

@jakobehn The behavior you pointed out is related to a regression from a change we made to separate plan creation and execution. Due to this bug, the result from Stepwise Planner isn't injected into the meta-prompt, so it's just completely lost to void rn after it's generated. I will try to get this fixed later today or by Monday.

As a side note, we're also considering returning the response of Stepwise directly, since the result's already been tuned to be a sensical chat response base on the user's input. Would love to hear your thoughts here!

**Comment by samleegithub** [comment]
@teresaqhoang one vote from me for using the final response of the stepwise planner directly. I've found that the answer from the stepwise planner is usually better than the second response based on my testing.

**Comment by jakobehn** [comment]
@teresaqhoang +1 from me as well on this, the answer from the stepwise planner tends to be what you want as output here

**Comment by samleegithub** [comment]
https://github.com/microsoft/chat-copilot/issues/221

Here is the related issue.

**Comment by darakawa** [comment]
@teresaqhoang +1 from me as well. By using the output directly, we'd have the option to use a powerful model for the planner and a basic one for the bot. This would help with rate limits and costs management.

**Comment by teresaqhoang** [comment]
Thanks for your inputs! Here's the PR that fixes the bug where the planner's result wasn't being used in the meta prompt: https://github.com/microsoft/chat-copilot/pull/514

I also added an option to allow use of the StepwisePlanner result directly as the bot response. This is the default if using Stepwise Planner. You can set it under `UseStepwiseResultAsBotResponse` of Planner options in appsettings. 

@samleegithub @jakobehn @darakawa

**Comment by teresaqhoang** [comment]
Change is merged: [Refactor Stepwise Planner handler, added logic to allow use of stepwise plan result as bot response #514](https://github.com/microsoft/chat-copilot/pull/514)
