### ISSUE TITLE
The chatmemory index is not created in Azure Cognitive Search

### ISSUE THREAD

**Issue by vicentegarciadiez** [microsoft/chat-copilot#490]
warn: Microsoft.SemanticMemory.MemoryStorage.AzureCognitiveSearch.AzureCognitiveSearchMemory[0]
      Not found: The index 'chatmemory' for service 'acs-copichat-lghizlbtodfog' was not found.
      Status: 404 (Not Found)

      Content:
      {"error":{"code":"","message":"The index 'chatmemory' for service 'acs-copichat-XXXXXXXX' was not found."}}

How can I create it manually?

Thanks in advance.

**Comment by TaoChenOSU** [comment]
Hello @vicentegarciadiez,

Thanks for opening the issue!

Could you please provide the repro steps?

**Comment by vicentegarciadiez** [comment]
How can I create it manually? I was not able to find the way

**Comment by TaoChenOSU** [comment]
Where did you see the error? And if you go to your acs instance, do you see the index?

**Comment by vicentegarciadiez** [comment]
I'm getting that error in the logs of the webapi.

There is only one index in the acs instance, global-documents but I know I must have two.

Please, can you give me the json definition of the chatmemory index?

**Comment by TaoChenOSU** [comment]
You don't need to create the index manually. It should be created by Chat Copilot if it doesn't exist. Did you get the error when chatting with the bot or when you upload a document?

**Comment by vicentegarciadiez** [comment]
When chatting with the bot.

But it would be very helpful if you can send me the json definition of the chatmemory index

**Comment by TaoChenOSU** [comment]
> When chatting with the bot.
> 
> But it would be very helpful if you can send me the json definition of the chatmemory index

Unfortunately, we don't own the Json definition.

**Comment by TaoChenOSU** [comment]
> I'm using this Azure template to deploy the needed infrastructure
> 
> https://aka.ms/sk-deploy-existing-azureopenai-portal
> 
> I configure the web api to use this infrastructure, everything works right but I get that error.
> 
> I did the same yesterday and the index was created. But today I do the same but this index is missing

Redeploying should not wipe out the resource and its data.

**Comment by vicentegarciadiez** [comment]
> > I'm using this Azure template to deploy the needed infrastructure
> > https://aka.ms/sk-deploy-existing-azureopenai-portal
> > I configure the web api to use this infrastructure, everything works right but I get that error.
> > I did the same yesterday and the index was created. But today I do the same but this index is missing
> 
> Redeploying should not wipe out the resource and its data.

Before redeploy I delete all resources manually.

**Comment by vicentegarciadiez** [comment]
> > I'm using this Azure template to deploy the needed infrastructure
> > https://aka.ms/sk-deploy-existing-azureopenai-portal
> > I configure the web api to use this infrastructure, everything works right but I get that error.
> > I did the same yesterday and the index was created. But today I do the same but this index is missing
> 
> Redeploying should not wipe out the resource and its data.

But you can copy it from your deployed acs

**Comment by vicentegarciadiez** [comment]
I've deployed the new Azure template you published recently.

The webapi is correctly deployed, the chatmemory index is created but the static web ui is missed

**Comment by TaoChenOSU** [comment]
> I've deployed the new Azure template you published recently.
> 
> The webapi is correctly deployed, the chatmemory index is created but the static web ui is missed

Glad to hear that it created the index for you!

Please note that we no longer server the webapp from a static web. Please refer to the release note here: https://github.com/microsoft/chat-copilot/releases/tag/0.7

**Comment by TaoChenOSU** [comment]
Closing. Feel free to reopen if you have further questions.
