### ISSUE TITLE
Deploying a new build stops at search service (not found)

### ISSUE THREAD

**Issue by threegitty350** [microsoft/chat-copilot#491]
**Describe the bug**
Manually deploying chat copilot (new resource group) to azure is no longer possible due to the search service not being found on azure.

Specifically in the bicep file:
resource bingSearchService 'Microsoft.Bing/accounts@2020-06-10' = {
  name: 'bing-search-${uniqueName}'
  location: 'global'
  sku: {
    name: 'S1'
  }
  kind: 'Bing.Search.v7'
}

This prevents the setup to conclude and the app configuration fails to manifest on azure.  Prior to these major changes, it did not have the issue. To circumvent this, I could comment out the quoted lines and the lines found at 670:

      {
        name: 'PluginConfig:BingApiKey'
        value: bingSearchService.listKeys().key1
      }

and installed bing search 7 manually from azure and applied the keys to the config (in azure). However, despite doing so, I could not get the app to reach a healthy state.

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: N/A
 - Source: main branch (latest as of 10/12/2023)

**Additional context**
Deploying to eastUS. Successfully deployed many times prior September 28, 2023. Willing to try workarounds on new RGs if suggested.

**Comment by TaoChenOSU** [comment]
Hello @threegitty350,

Thanks for posting the issue!

To help us assist you better, could you let use know if you can manually create a Bing Search resource manually?
![image](https://github.com/microsoft/chat-copilot/assets/12570346/40fb28ab-a6e9-439d-af55-3980a650baf2)

And when you say you cannot get the app to reach a healthy state, could you provide us with any errors or logs (if there are any)?

**Comment by threegitty350** [comment]
> Hello @threegitty350,
> 
> Thanks for posting the issue!
> 
> To help us assist you better, could you let use know if you can manually create a Bing Search resource manually? ![image](https://user-images.githubusercontent.com/12570346/274712744-40fb28ab-a6e9-439d-af55-3980a650baf2.png)
> 
> And when you say you cannot get the app to reach a healthy state, could you provide us with any errors or logs (if there are any)?

Yes, I was able to created it manually. I assigned the key to the configuration as a new value but it cannot start the service. Perhaps it's incorrect?

![image](https://github.com/microsoft/chat-copilot/assets/147629973/9f56a1cb-0bca-4e28-a2a1-b4daed65806c)

Unfortunately, I am not familiar enough with azure to provide a log.

**Comment by TaoChenOSU** [comment]
Hi @threegitty350,

Where did you set the new value to? The setting is consumed by the function app not the WebApi.

Linking this issue here to assist you further: https://github.com/microsoft/chat-copilot/issues/498. Could you also let us know your bicep version?

**Comment by threegitty350** [comment]
I think we should close this issue and resume in the other thread, it seems very much the same. #498 

As mentioned in the other thread:
Bicep CLI version 0.21.1 > upgraded to > Bicep CLI v0.22.6 Did not result in a different outcome

**Comment by TaoChenOSU** [comment]
Closing as described above.
