### ISSUE TITLE
Semantic Memory OCR configuration is not falling through.

### ISSUE THREAD

**Issue by GryBsh** [microsoft/chat-copilot#492]
**Describe the bug**
Configuring copilot to use Azure Form Recognizer produces no calls to Form Recognizer when uploading documents.
It appears in the config extensions where the code is expecting Semantic Memory to configure itself doesn't produce the desired result. It also produces no errors and semantic memory doesn't list an available text extractor when it starts.

**To Reproduce**
1. Configure Copilot with OCRType: `AzureFormRecognizer` and configure that service with the appropriate endpoint and apikey
2. Upload a PDF document without any embedded OCR information or embedded text
3. The document will produce an underwhelming number of vectors and attempts to ask questions about it will yield no useful results.

**Expected behavior**
That a call would be made to Azure Form Recognizer would be made to perform OCR on the uploaded document.

**Screenshots**

**Platform**
 - OS: Linux
 - IDE: VS Code
 - Language: C#
 - Source: Main branch

**Additional context**

**Comment by TaoChenOSU** [comment]
Hello @GryBsh,

Thanks for posting the issue!

If you are uploading a PDF file, it won't invoke the OCR engine, as PDFs are parsed by a PDF parser.

**Comment by GryBsh** [comment]
I'll try that, but it really should use OCR on PDFs. Especially when Forms Recognizer, ime, is worlds better than whatever may have processed the PDF before hand.

**Comment by TaoChenOSU** [comment]
Thank you for your suggestion! [Semantic Memory](https://github.com/microsoft/semantic-memory) is under active development to improve document parsing and chunking.

**Comment by TaoChenOSU** [comment]
Closing. Feel free to reopen if there are further questions.
