### ISSUE TITLE
Simplify and Modularize Azure Deployment Scripts

### ISSUE THREAD

**Issue by douglasware** [microsoft/chat-copilot#494]
The default should be minimal. Extra features should be separate and modular.
Having it default to turning on everything makes it extremely fragile. 
I am spending hours on a deployment script that doesn't work for features I didn't even want in the first place.
The resulting deployment is very expensive and burns through the average developer's monthly MSDN credits in a couple days.

**Comment by victor-v-rad** [comment]
I second that and created a similar issue.
https://github.com/microsoft/chat-copilot/issues/487

Plus more e2e and performance autotests would be great to have.

**Comment by glahaye** [comment]
This has been done for the most part now.
