### ISSUE TITLE
Create a stable and deployable branch

### ISSUE THREAD

**Issue by douglasware** [microsoft/chat-copilot#496]
I appreciate that you are moving fast, but breaking the Azure deployment scripts on the main branch over a week ago was not a nice thing to do. Pulling such big and unstable changes into main is a choice. Please, if you know that the main branch has significant issues, at least say something in the readme.

**Comment by TaoChenOSU** [comment]
Hello @douglasware,

Thank you for reporting the deployment issues on the main branch!

We are actively working on improving the developer experience for Chat Copilot. Stay tuned!

**Comment by glahaye** [comment]
@douglasware As of now, every release comes with a release branch. For instance release 0.8 comes with a branch called simply 0.8.

Once a release is out, its branch will no longer be updated. The exception to this is the latest release branch, which will only receive bug fixes.
