### ISSUE TITLE
Bump SK to beta?

### ISSUE THREAD

**Issue by Ryangr0** [microsoft/chat-copilot#497]
I'd just like to know if there is currently any effort to bump to [dotnet-1.0.0-beta1](https://github.com/microsoft/semantic-kernel/releases/tag/dotnet-1.0.0-beta1)? If not I'd be happy to try and help.

**Comment by TaoChenOSU** [comment]
Hi @Ryangr0.

Yes, you are more than welcome to contribute!

**Comment by crickman** [comment]
Visibility: SK has been bumped to beta2, but we're going to wait for the next beta release.

**Comment by crickman** [comment]
@Ryangr0 - Thank you for your patience 

https://github.com/microsoft/chat-copilot/pull/581
