### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_REFUSED WebSocketTransport.ts:81  WebSocket connection to 'wss://localhost:40443/messageRelayHub' failed: 

### ISSUE THREAD

**Issue by howard2019007** [microsoft/chat-copilot#502]
ailed to load resource: net::ERR_CONNECTION_REFUSED
WebSocketTransport.ts:81  WebSocket connection to 'wss://localhost:40443/messageRelayHub' failed: 
(anonymous) @ WebSocketTransport.ts:81
Utils.ts:185  [2023-10-16T03:40:06.797Z] Error: Failed to start the connection: Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.
value @ Utils.ts:185
signalRHubConnection.ts:112  SignalR Connection Error:  Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.
    at Wd.mark.Wd.wrap.e.abrupt.a.onclose (WebSocketTransport.ts:136:28)

**Comment by glahaye** [comment]
@TaoChenOSU The code that uses websockets should work locally, right?

**Comment by howard2019007** [comment]
I found that local http://localhost:3000 work fine, but if I use http://ip:3000 I don't, the same problem when I deployed to Azure

**Comment by crickman** [comment]
@howard2019007 - is this related to https://github.com/microsoft/chat-copilot/issues/527?  (Have you gotten past the issue described in this ticket?)
