### ISSUE TITLE
Support S2S auth for custom plugin

### ISSUE THREAD

**Issue by sarahxrm** [microsoft/chat-copilot#515]
Hi team, I am wondering if S2S auth token is supported for custom plugins? If so, what would be the config to enable it. Thanks!

**Comment by glahaye** [comment]
@TaoChenOSU Do you have any information regarding server-to-server auth token support for custom plugins?

**Comment by alliscode** [comment]
Hi @sarahxrm, thanks for your question.

We support `Bearer` token authentication. For ChatGPT plugins loaded from within the app UI,, we only support it if they are configured with an auth type of `user_http`. In this case, when you load the plugin you will see a text field where you can enter your key/token and this will be used in the auth header for calls made to the plugin. This works well for things like PAT tokens or fixed secret keys, for OAuth it will only work until the token expires as chat-copilot does not handle refreshing the token.

Does that answer your question?

**Comment by sarahxrm** [comment]
Thanks a lot! That answers my question.
