### ISSUE TITLE
OpenAI Deployment is Broken

### ISSUE THREAD

**Issue by victor-v-rad** [microsoft/chat-copilot#516]
**To Reproduce**
1. Go to https://github.com/microsoft/chat-copilot/tree/main/scripts/deploy
2. Click on "Deploy to Azure" button
3. Enter OpenAI in Ai Service field (screenshot provided)
4. Deploy
5. Open deployed Web App Configuration 
7. See api keys are set to AzureOpenAl but not to OpenAl (screenshot provided)
8. Open webapi website and see the error  (screenshot provided)
9. Open Application Event Logs and see APIKey error

**Expected behavior**

- api keys should be set for OpenAl
- frontend should open without the errors

**Screenshots**
<img width="646" alt="Screenshot 2023-10-17 at 1 19 53 PM" src="https://github.com/microsoft/chat-copilot/assets/106504/11d5918d-eadc-4738-a4be-7c7a47099ccc">
<img width="643" alt="Screenshot 2023-10-17 at 1 20 02 PM" src="https://github.com/microsoft/chat-copilot/assets/106504/6aa96f30-cb4c-42af-a9e9-3f0a304d51c2">
___________________

<img width="943" alt="image" src="https://github.com/microsoft/chat-copilot/assets/106504/3dc3a9a0-f715-4a06-a7fc-6bab0d5259db">

___________________

<img width="707" alt="image" src="https://github.com/microsoft/chat-copilot/assets/106504/4211ee69-1b4b-4e2a-b521-a6733d5514de">

___________________

<img width="1208" alt="image" src="https://github.com/microsoft/chat-copilot/assets/106504/251da862-9280-4945-b1a2-d67b2ecc243a">

___________________

**Platform**
 - Language: C#
 - Source: Latest code and latest released Chat Copilot version

**Comment by glahaye** [comment]
Thanks for bringing this issue to our attention.

Please see PR #519 addressing it.

**Comment by glahaye** [comment]
@victor-v-rad Closing this as fixed now.

If ever you hit any further problems, please let us know again!

Thanks.

**Comment by victor-v-rad** [comment]
Wow, fixed in several hours after I reported it! Thank you @glahaye, greatly appreciated.
