### ISSUE TITLE
The image compiled by dockerfile.nginx cannot run through.

### ISSUE THREAD

**Issue by mikey5656** [microsoft/chat-copilot#520]
**Describe the bug**

Image compiled by dockerfile.nginx, page displayed blank when running, error reported
![image](https://github.com/microsoft/chat-copilot/assets/142763736/c7f5785c-df90-4d57-bb20-dc0f3a55cc63)

**Comment by huangyingting** [comment]
@mikey5656 you need to create .env file at webapp directory to set environment variable REACT_APP_BACKEND_URI, or you could run `docker compose build` directly

**Comment by glahaye** [comment]
@mikey5656 PR #501 is now in.  This should be addressed now.
