### ISSUE TITLE
Reduce the horizontal space between prompt and response chats

### ISSUE THREAD

**Issue by Azzeo** [microsoft/chat-copilot#522]
There is a lot of margin between the (user's) prompt and the bot's response. Whereas this space can be better utilised by having wider chat "containers", and thus allowing for the prompt and the response to take up fewer lines. One could think of drastically/completely remove this margin and have another way to show a distinction between the user and the chat (e.g., a slightly different background)

The current layout is, for example, when the user/bot provides a long piece of code or a long text, problematic since it creates a lengthy chat containers on the Y axis. Other LLM interfaces don't have any (noticeable) horizontal margins between the user and the bot: ChatGPT, Bard, Cohere. Although i.e., ChatGPT doesn't have a drastically wider Chat "container", they have a very small header that disappears when scrolling, allowing them to show more content this way.

**Comment by crickman** [comment]
Thank you for reporting this.  Are you referring to this gap:

![image](https://github.com/microsoft/chat-copilot/assets/66376200/72647b62-9acd-45fa-b14e-9cc0502fe24d)

**Comment by Azzeo** [comment]
Sorry for being unclear. Hope this screenshot helps with some ideas (a combination of these two ideas would also be a viable option in my humble opinion): 

<img width="1244" alt="Screenshot 2023-10-23 at 20 13 20" src="https://github.com/microsoft/chat-copilot/assets/55406706/939415fb-12f5-4e54-a729-0bc7783d5eaa">

As copilot also has a pretty sizeable header, there is little room left currently for the chat to be displayed. Other chats (e.g. ChatGPT) either use a combination of a different background for user-bot and/or hiding the header when scrolling. Hiding/collapsing the header is also a viable option but I think increasing the width of the chatbox is the easiest solution right now.

**Comment by crickman** [comment]
Ok, got it.  Thank you for the clarification.  I do understand that messaging apps (such as teams) do offer various layouts (some more compact than others).  There is certainly an opportunity here.   Looking at this on a large monitor, I'm seeing more wasted space.  The UX here could be certainly be more reponsive.

![image](https://github.com/microsoft/chat-copilot/assets/66376200/69d7a4b7-b966-465e-89ba-e7f68e654be1)
