### ISSUE TITLE
Looking for your backend

### ISSUE THREAD

**Issue by howard2019007** [microsoft/chat-copilot#523]
Once deployed to Azure, it cannot be used
./deploy-webapi.ps1 -Subscription {YOUR_SUBSCRIPTION_ID} -ResourceGroupName {YOUR_RESOURCE_GROUP_NAME} -DeploymentName {YOUR_DEPLOYMENT_NAME}
![image](https://github.com/microsoft/chat-copilot/assets/49265228/ecceb9e3-b7cc-49ad-8c70-ba8bc22ff87c)

**Comment by glahaye** [comment]
It's suspicious that it's looking for the backend at https://localhost:40443/...

Do you have a ..\webapp\.env file on your machine?  If so, make sure that there are NO DEFINITION of REACT_APP_BACKEND_URI in it.  Otherwise, you might end up with the problem you are describing.

Let me know whether this addresses your issue.

**Comment by howard2019007** [comment]
![image](https://github.com/microsoft/chat-copilot/assets/49265228/295950b5-90e2-493f-a2f0-031cb66b113c)
There will still be an error

**Comment by glahaye** [comment]
I can't reproduce the problem on my side...

Let me verify the steps you took to get to this problem.

First, did you get the latest commits from the repo?  Make sure you have the "Make deploy-webapi do all it needs to by default (#524)" change on your computer.

Than, did you run package-webapi.ps1 again?

**Comment by howard2019007** [comment]
My steps: 1. Download the latest GitHub library, then import Azure OpenAI and AAD authentication ID, the local execution is running normally. 2. Use the package-webapi.ps1 packager and encounter the above problems after performing deployment to Azure

**Comment by crickman** [comment]
Can you check if you've hit the maximum number of indexes?  Migration won't be able to proceed unless there is room to create two new indexes.

**Comment by howard2019007** [comment]
https://github.com/microsoft/chat-copilot/issues/523#issuecomment-1772125482  
I've fixed the error, but a new problem has arrived, and there is still no way to log in, enter the username and password and stay in the looking for the backend
![image](https://github.com/microsoft/chat-copilot/assets/49265228/ca06bf60-4a56-4eed-b740-ff075a52cc28)

![image](https://github.com/microsoft/chat-copilot/assets/49265228/1b29f4b6-2d0f-4eb9-bc06-866c2ebee1e6)
![image](https://github.com/microsoft/chat-copilot/assets/49265228/94cc4d3b-367d-452e-84e0-fd035f23bcc7)

**Comment by howard2019007** [comment]
> 我无法在我这边重现问题...
> 
> 让我验证一下您为解决此问题而采取的步骤。
> 
> 首先，您是否从存储库中获得了最新的提交？确保计算机上有“默认情况下使 deploy-webapi 执行其需要的所有操作 （#524）”更改。
> 
> 比，你又运行了package-webapi.ps1吗？

This issue has been resolved, thanks
