### ISSUE TITLE
Memorypipeline (Distributed) does not delete memories from AzureCognitiveSearch

### ISSUE THREAD

**Issue by KossiH** [microsoft/chat-copilot#525]
**Describe the bug**
Memorypipeline (Distributed) does not delete memories from AzureCognitiveSearch
- When user use the "upload document" it will be saved to AzureCognitiveSearch. When eventually the session will be deleted, the memorypipeline destroy everything else but not AzureCognitiveSearch memories..
- It tries to find an index but does not use the common chatmemory 

**To Reproduce**
1. Use Distributed memorypipeline
2. User creates sessions and save documents / memories
3. After discussions, session will be deleted
4. Everything else is destroyed but not the AzureCognitiveSearch memories / document embedings..

**Expected behavior**
If user deletes the session > it should also delete memories from AzureCognitiveSearch

**Comment by glahaye** [comment]
@TaoChenOSU and / or @crickman can you take a look at this?

**Comment by crickman** [comment]
Thank you for reporting this.  Memory are indeed intended to be deleted along with the chat.  I'll dig into what is going on here.

**Comment by KossiH** [comment]
Hi @crickman, as much as I have researched the matter myself.. The memorypipeline switch / forgets the "chatmemory" index name when pipeline goes to private-delete-document queue > ether it does not  Respect the given index value or given index value is not the correct value (mixed at some point)

**Comment by crickman** [comment]
Thank you.  Looks like we were passing in the wrong id...pr incoming.
