### ISSUE TITLE
Unable to generate bot response. Details: Error: 500: Internal Server Error

### ISSUE THREAD

**Issue by howard2019007** [microsoft/chat-copilot#527]
I deployed to azure chat with the error: unable to generate bot response. Details: Error: 500: Internal server error
![image](https://github.com/microsoft/chat-copilot/assets/49265228/578e5a3b-8765-4a9d-8546-30e58358ceab)

**Comment by howard2019007** [comment]
我已经解决该问题

**Comment by crickman** [comment]
@howard2019007 - If you use the browser dev-tools, you can surface more detailed information on the failed request from the client perspective.  As an http500 failure, I suspect there's a corresponding exception being logged in the webapi.  Locating this exception in log would provide more information.
