### ISSUE TITLE
WARNING: TCP connect to (::1 : 40443) failed

### ISSUE THREAD

**Issue by AliRaza190** [microsoft/chat-copilot#537]
I am trying to run it locally but face this error. When I tried to compile front and back separately, the front-end compiled successfully but not the backend.

**Comment by crickman** [comment]
If the back-end isn't running then the front-end won't be able to connect to it.  I think the core issue here might be that your webapi project isn't building/running.  Are you able to capture any error information around this?

Try running `dotnet build` from the `webapi` folder.
