### ISSUE TITLE
Chat Copilot resets to the "first" chat when refreshed/reloaded

### ISSUE THREAD

**Issue by crickman** [microsoft/chat-copilot#540]
**Describe the bug**

**To Reproduce**
1. Open co-pilot chat
2. Click"Add a chat" (+) > Chat Session
3. Refresh window

**Expected behavior**
Current chat still current

**Screenshots**
"First" chat selected (after sessions re-ordered alphabetically - which seems fine)

**Comment by dehoward** [comment]
@crickman this isn't a bug, per se, since we do not currently save a user's selected chat to the DB. 
instead, we just default to the first chat in the list:
![image](https://github.com/microsoft/chat-copilot/assets/52973358/968b684f-fc86-427b-98e2-db11876fd226)

**Comment by crickman** [comment]
Its a UX bug, specifically because this isn't intentionally addressed or considered and runs counter to a reasonable expectation.
