### ISSUE TITLE
The chat response is slow and it takes three minutes to give a result, what is the problem

### ISSUE THREAD

**Issue by howard2019007** [microsoft/chat-copilot#543]
The chat response is slow and it takes three minutes to give a result, what is the problem

**Comment by howard2019007** [comment]
@Gil LaHaye

**Comment by howard2019007** [comment]
Is this running hosted azure
Are you using Azure Open AI models/endpoints
Are you using gpt-3.5-turbo model
Is the result an is it a valid response

获取Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
发件人: Chris ***@***.***>
发送时间: 星期五, 十月 27, 2023 12:22:21 上午
收件人: microsoft/chat-copilot ***@***.***>
抄送: howard2019007 ***@***.***>; Author ***@***.***>
主题: Re: [microsoft/chat-copilot] The chat response is slow and it takes three minutes to give a result, what is the problem (Issue #543)


Thank you for calling this out. Your timing is impeccable...I was just trying to raise awareness for a performance sweep!

To help, can you please provide some additional information about your environment:

  *   Is this running local or hosted?
  *   Are you using Open AI or Azure Open AI models/endpoints?
  *   Are you using gpt-3.5-turbo or gpt-4 model?
  *   Are you seeing any exceptions or timeouts on the api/server logs?
  *   Is the result an exception/failure or is it a valid response?

―

**Comment by crickman** [comment]
Thank you for your response.  This looks like it might be related to the SignalR hub.  Can you zoom into that?

**Comment by howard2019007** [comment]
![image](https://github.com/microsoft/chat-copilot/assets/49265228/c5361fde-39d6-4ed3-8f4a-5ea71e19b0a2)
![image](https://github.com/microsoft/chat-copilot/assets/49265228/83847cb0-4fcd-45fe-a7bf-b876104b6fdf)
![image](https://github.com/microsoft/chat-copilot/assets/49265228/e6c49e09-445d-4ec6-bf51-947bb6a129ed)

**Comment by howard2019007** [comment]
> 感谢您的回复。这看起来可能与 SignalR 中心有关。你能放大一下吗？
Is the information I provide sufficient?

**Comment by anilaltuner** [comment]
I can verify the issue, no exception or any log. Its just like hang and that happens often.

I am using gpt-3.5-turbo.

**Comment by howard2019007** [comment]
I've had the same issue with my attempts to add Azure resources and redeploy, with long delays and fast on-premises

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anilaltuner** [comment]
Convert to Langchain. They are faster somehow

**Comment by howard2019007** [comment]
Very interested, how to convert, where there are tutorials

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cm-mjolner** [comment]
I can confirm this issue as well. I did some profiling and it seems to just run consistently slow across the board. Running it locally it seems to run fine. I've tried deploying it with default parameters and even with the beefiest App Service plan I'm seeing long delays and response times.

I'm using `gpt-3.5-turbo` as well.

**Comment by crickman** [comment]
Thanks for the feedback.  I'm actively engaged this week in this analysis as well.   Appreciate sharing the local versus deployed experience.

**Comment by howard2019007** [comment]
新的版本已解决此问题，感谢

**Comment by howard2019007** [comment]
已解决
