### ISSUE TITLE
Wrong default value for RUNTIME in package-webapi.sh

### ISSUE THREAD

**Issue by Rsimk** [microsoft/chat-copilot#544]
**Describe the bug**
webapi package script has default value for RUNTIME set to "linux-x86", but webapi is Windows application. App packaging and app deployment scripts work without error, but webapp would fail with no indications about wrong runtime. Only changing RUNTIME to "win-x64" solves the problem.

**To Reproduce**
1. run ./package.sh in WSL
2. run ./deploy.sh
3. open webapi web app.
4. pages opens with error ""Server Error in '/' Application."

**Expected behavior**
webapi URL should open copilot start page.

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/56922442/a9f4f88b-cea0-4e1f-a62d-5ff7888d7e87)

**Platform**
 - OS: [WSL]
 - IDE: [VS Code]

**Comment by gormaar** [comment]
I am experiencing the same issue

**Comment by gormaar** [comment]
I was at least able to access the frontend by changing the path from `site\wwwroot` to `site\wwwroot\wwwroot\build` where the app is mounted. But the frontend is still unable to access the API


![image](https://github.com/microsoft/chat-copilot/assets/35703118/bb8b5584-0b2c-45d6-8f64-e940e34a44c3)

**Comment by crickman** [comment]
Hi @Rsimk, until recently the deployed version of the API didn't have a start page (other than /healthz).  Now that the react app is no longer deployed as a static web app it, the start page should render (if deployed).

Can you confirm that you have deployed the webapp from a recent version of the repo?

**Comment by Rsimk** [comment]
> Hi @Rsimk, until recently the deployed version of the API didn't have a start page (other than /healthz). Now that the react app is no longer deployed as a static web app it, the start page should render (if deployed).
> 
> Can you confirm that you have deployed the webapp from a recent version of the repo?

webapp was deployed from Oct 23, commit e1395550d9645074b4ec67f1254eae7f51429c50.

**Comment by crickman** [comment]
Are you able to access the /heathz route?

**Comment by Rsimk** [comment]
I assume you where asking about "healthz", not "heathz". /healthz return 404.
webapp/webapi is deployed from script. Return code was 202. In Deployment center logs - "Deployment successful.". Looking in file system. Files are actually there.
I redeployed from scratch and now website main page responses with simple text message ""Memory pipeline is running. Uptime: 907 secs."". Although I haven't packaged or deployed it. /healthz still doesn't work.

**Comment by crickman** [comment]
Thank you for the follow-up.  (Yes: healthz, apologies)

**Comment by glahaye** [comment]
@Rsimk Yes, you are right.  I changed the default to win-x64 in the following PR: #606
