### ISSUE TITLE
More Tests

### ISSUE THREAD

**Issue by karstenjMSFT** [microsoft/chat-copilot#548]
There is a dearth of tests in this project. Is it on the roadmap to add additional tests, either unit tests or integration test?

**Comment by crickman** [comment]
Thank you for this question.  I've included a couple people that have been involved with this testing layer who may be able to provide more detail.

**Comment by glahaye** [comment]
@karstenjMSFT Yes, some integration tests are already written and will make their way in soon.  More will follow and I plan on adding unit tests too.

More to follow...

**Comment by glahaye** [comment]
See #474 

Closing this issue in favor of #474.
