### ISSUE TITLE
Speech to Text input using Whisper API

### ISSUE THREAD

**Issue by raffertyuy** [microsoft/chat-copilot#560]
Can we make chat copilot more accessible by adding a microphone speech-to-text input, ideally using OpenAI's Whisper API?

**Comment by crickman** [comment]
Chat copilot can be configured for speech input; although, its designed to target Azure Speech Services:

![image](https://github.com/microsoft/chat-copilot/assets/66376200/076ae452-6125-41fb-bd97-06e937baf388)

**Comment by raffertyuy** [comment]
Just saw it thanks. Too bad it only works with English at the moment, but good enough for now.
