### ISSUE TITLE
How does voice input support multiple languages, currently the test can only support English

### ISSUE THREAD

**Issue by howard2019007** [microsoft/chat-copilot#566]
How does voice input support multiple languages, currently the test can only support English

**Comment by crickman** [comment]
Hi, thanks for this question.  I really appreciate that you've been pushing non-english cases.

I'll dig in a bit and see what I find.

**Comment by crickman** [comment]
Hi, I believe this is a duplicate of https://github.com/microsoft/chat-copilot/issues/568 (which has been closed).
