### ISSUE TITLE
It is recommended to add the multi-Chinese function and text-to-speech dialogue function to facilitate use in different language environments

### ISSUE THREAD

**Issue by howard2019007** [microsoft/chat-copilot#568]
How to implement multi-Chinese language function, such as automatically switching based on the browser language or system language, or the user can select the language ...

**Comment by matthewbolanos** [comment]
Thanks for reaching out. Today's chat copilot is just a reference application, so we currently don't have plans to investigate multi-language support. Feel free to create a fork of the repo and share the results of your investigation.
