### ISSUE TITLE
Switch from react-scripts to vite based spa

### ISSUE THREAD

**Issue by luko0610** [microsoft/chat-copilot#571]
Due to cra being deprecated a switch to a vite based frontend would be nice.
If there is any interest I would be willing create a PR for this.

**Comment by matthewbolanos** [comment]
Thanks for expressing interest in providing a PR for Vite. Unfortunately, we likely wouldn't be able to support it. Feel free to create a fork of this project with Vite support.

**Comment by luko0610** [comment]
@matthewbolanos What do you mean by would not be able to support this? Vite is the recommended way to go with for React single page applications.

If this project is supposed to act as an entry point for people who want to implement something similar or get started with Semantic Kernel improvements should be accepted.
