### ISSUE TITLE
When using Qdrant as a vector database, an error was raised when deleting the Chat Session

### ISSUE THREAD

**Issue by xsoutline** [microsoft/chat-copilot#579]
**Describe the bug**
当使用Qdrant作为向量数据库，在删除Session时引发错误，并且页面提示了错误信息，而Chat Session在交互界面上并没有删除，但是刷新窗口时Chat Session事实已经被删除，引用错误的原因是调用Qdrant接口时引发404错误.
English translation:When using Qdrant as a vector database, an error was raised when deleting the Chat Session, and the page displayed an error message. However, the Chat Session was not deleted on the web page, but when refreshing the window, the Chat Session was actually deleted. The reason for the reference error was the 404 error caused by calling the Qdrant API.
Configuration 
```
//appsettings.Development.json
{
  "SemanticMemory": {
    "Retrieval": {
      "VectorDbType": "Qdrant"
    },
    "DataIngestion": {
      "VectorDbTypes": [
        "Qdrant"
      ]
    }
  }
}

```
Click to delete screenshot of chat session
![image](https://github.com/microsoft/chat-copilot/assets/31274694/cfdef5ea-5587-4e88-bfdd-7c178c0db630)
error message
```
fail: Microsoft.SemanticMemory.MemoryStorage.Qdrant.Client.QdrantClient[0]
      GetListAsync failed: Response status code does not indicate success: 404 (Not Found).,
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.SemanticMemory.MemoryStorage.Qdrant.Client.QdrantClient`1.ValidateResponse(HttpResponseMessage response, String content, String methodName) in \CoreLib\MemoryStorage\Qdrant\Client\QdrantClient.cs:line 351

```
The error code location found is project[https://github.com/microsoft/kernel-memory](https://github.com/microsoft/kernel-memory)Code for：
https://github.com/microsoft/kernel-memory/blob/aee57008034f12bfa16b440f4ea58a258c6f0e00/dotnet/CoreLib/MemoryStorage/Qdrant/Client/QdrantClient.cs#L277
**To Reproduce**
1. Start the chat session with a simple conversation and wait for complete completion
2. Click on 'Delete chat session'
3. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/31274694/fec1dc2c-82fa-4bee-a4e0-54cf82589a78)

**Platform**
 - OS: Windows 10 22H2 19045.3570
 - IDE: vs 2022
 - Language: C#
 - Source: tag [0.7](https://github.com/microsoft/chat-copilot/commit/3cde0ef9fb66aa35f2a3442519b4bb1c9418d213)

**Additional context**

**Comment by crickman** [comment]
Thank you for the clear report on this issue.

**Comment by TaoChenOSU** [comment]
Tracked by https://github.com/microsoft/chat-copilot/issues/512. Will see when this will be ready in the kernel memory.

**Comment by TaoChenOSU** [comment]
Verified that this had been fixed by https://github.com/microsoft/chat-copilot/pull/585.
