### ISSUE TITLE
Integrate with flow orchestrator

### ISSUE THREAD

**Issue by yan-li** [microsoft/chat-copilot#582]
## Summary
In recent SK release, an experimental flow orchestrator is introduced.
https://github.com/microsoft/semantic-kernel/issues/2164

Creating this issue to track the effort of providing flow orchestration options.

## Goal
1. Make flow orchestrator an option for planning/orchestration
2. Ability to visualize the flows on frontend
3. Easy to onboard and configure more customized flows, with some sample flows

**Comment by crickman** [comment]
Thank you for this suggestion, we look forward to show-casing SK features.

**Comment by crickman** [comment]
This looks like a compelling feature.  I noticed it is currently in the Experimental folder.  The team would like some time to allow for stabilization and further evaluation.

**Comment by evchaki** [comment]
We will not be doing this at this time.
