### ISSUE TITLE
how to deploy in docker?

### ISSUE THREAD

**Issue by win4r** [microsoft/chat-copilot#591]
how to deploy in docker?

**Comment by crickman** [comment]
Thank you for this question. 

Docker deployment definitions are currently defined under the `docker` folder:

https://github.com/microsoft/chat-copilot/tree/main/docker

This was a community contribution and additional insight might be available from the community.

We have not performed a docker deployment internally.

**Comment by win4r** [comment]
Could you please push it to Docker Hub?

**Comment by crickman** [comment]
I'm not sure we'dwill be able to manage that surface area.  Thank you for the suggestion, I'll run it by PM.

**Comment by matthewbolanos** [comment]
Thanks for looping me in @crickman. @win4r, unfortunately we won't be able to support this on Docker Hub, so for the time being, we won't be pushing it there.

**Comment by momuno** [comment]
Closing as response/answer from @matthewbolanos provided
