### ISSUE TITLE
Allow relative paths when importing custom OpenAI plugins

### ISSUE THREAD

**Issue by dehoward** [microsoft/chat-copilot#611]
**Describe the bug**
currently the URL path when importing a plugin is hard-coded to `.well-known/ai-plugin.json`.

**Expected behavior**
a plugin hosted at any path (e.g. `https://localhost:3001/ai-plugin.json`) can be uploaded.

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by DarthCodingMaster** [comment]
Read the documentation on plugins at [ChatGPT Plugins documentation](https://platform.openai.com/docs/plugins/getting-started): _The /.well-known folder is required and must exist on your domain in order to connect with your plugin_
