### ISSUE TITLE
Backend not reachable

### ISSUE THREAD

**Issue by abidur** [microsoft/chat-copilot#614]
**Describe the bug**
I am on Windows 10. Setup went without any issues. when I run the Start.ps1 script, the backend starts, however it's not reachable. I get the following error. Frontend starts and it keeps searching for backend as expected. 

WARNING: TCP connect to (127.0.0.1 : 40443) failed
WARNING: TCP connect to (::1 : 40443) failed
*************************************************
Backend is not running and we have exceeded                                                                                     
the maximum number of retries.

Therefore, we are exiting.
*************************************************

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/421514/9349fc42-074d-451b-bc0f-f9091bb4ca19)

**Platform**
 - OS: Windows 10
 - IDE:  VS Code

**Comment by crickman** [comment]
Thank you for reporting this.  We will verify the process locally and then may request additional details.

**Comment by momuno** [comment]
Hi @abidur can you please confirm if you are running your PowerShell as administrator, and what PowerShell version are you using?  Thank you.

**Comment by abidur** [comment]
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Using PowerShell as an Administrator. please see screenshot below.
![image](https://github.com/microsoft/chat-copilot/assets/421514/77e83ce1-9720-496a-9e0c-05a6c1f27857)


The end result is the backed is not reachable by the web app.
![image](https://github.com/microsoft/chat-copilot/assets/421514/8819e599-2b8c-4a43-bbf5-b8d124406073)

**Comment by momuno** [comment]
Please take a look at https://github.com/microsoft/chat-copilot#troubleshooting Issue No. 3.  "Your browser may be blocking the frontend access to the backend while waiting for your permission to connect."  Please check your firewall settings.  You must "acknowledge the risks of visiting an insecure website" before the frontend can connect to a backend server.
