### ISSUE TITLE
Planner: Setting to Always Proceed / Skip Confirmation

### ISSUE THREAD

**Issue by raffertyuy** [microsoft/chat-copilot#623]
Looking for a way to always proceed with the planner, without even showing the plan in the chat prompt.
This allows me show a good and continuous chat conversation (for demo, presentations, and even actual use).
Besides, the plans can be reviewed in the plans tab.

Please let me know if this setting already exists.

**Comment by threegitty350** [comment]
This would be nice to see. Maybe it would be better to have a setting that lets you decide whether to toggle it on/off, maybe on a granular level. Web search shouldn't need confirmation but e-mails yes.

Example:
    [FeatureKeys.AzureCognitiveSearch]: {
        enabled: true,
        label: 'Azure Cognitive Search',
        inactive: false,
        autoproceed: true
    },

**Comment by momuno** [comment]
Hi @raffertyuy, looking into this.  Thanks for the question.

**Comment by momuno** [comment]
Please try adding a useEffect into the PlanViewer (see PlanViewer.tsx) to auto approve the plan when it's returned to the UI.  Possibly something like the following:

```
useEffect(() => {
        // Bypass plan approval and execute plan
        if (planState === PlanState.PlanApprovalRequired) {
            void onPlanAction(PlanState.Approved);
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [selectedId, planState]);
```

**Comment by raffertyuy** [comment]
> It is not a setting accessible via UI. However please try adding a useEffect into the PlanViewer (see PlanViewer.tsx) to auto approve the plan when it's returned to the UI. Possibly something like the following:
> 
> ```
> useEffect(() => {
>         // Bypass plan approval and execute plan
>         if (planState === PlanState.PlanApprovalRequired) {
>             void onPlanAction(PlanState.Approved);
>         }
>         // eslint-disable-next-line react-hooks/exhaustive-deps
>     }, [selectedId, planState]);
> ```

Thank you for the advise! Saw the code and will modify it for my local use.
I'll submit a pull request if/when I have time to make it configurable :)
