### ISSUE TITLE
Webapp: create a plan model

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/chat-copilot#63]
Create a plan model to be parsed from Json in Webapp to avoid unsafe assignment.

**Comment by matthewbolanos** [comment]
@TaoChenOSU, do you have additional details? Is this from a TODO in the code?

**Comment by TaoChenOSU** [comment]
This is the TODO in the code: https://github.com/microsoft/chat-copilot/blob/main/webapp/src/components/chat/tabs/PlansTab.tsx#L131
