### ISSUE TITLE
Search filter does not work "Filter by name"

### ISSUE THREAD

**Issue by threegitty350** [microsoft/chat-copilot#637]
The search filter does not work.

**Steps:**
1. Disable simple chat experience
2. Click on filter box at the top of the thread list "Filter by name"
3. Search for keyword
4. No results

**Comment by momuno** [comment]
Hi @threegitty350 , Could you please provide information on what release of CC or commit hash you are using?

**Comment by threegitty350** [comment]
I was never able to get it to work, currently on the latest as of now: 6403cc6

**Comment by momuno** [comment]
Fixing conversation filtering #642 corrects this.  Thank you for bringing it to our attention @threegitty350 !
