### ISSUE TITLE
GET https://localhost:40443/maintenanceStatus net::ERR_FAILED

### ISSUE THREAD

**Issue by RuslanKain** [microsoft/chat-copilot#641]
Frontend does not connect to the backend, it continuously shows this: "Looking for your backend"

Looking at the browser's console, the following message appears:

Access to fetch at 'https://localhost:40443/maintenanceStatus' from origin 'http://localhost:34953' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
 
GET https://localhost:40443/maintenanceStatus net::ERR_FAILED  BaseService.ts:59 

![chat-copilot-error](https://github.com/microsoft/chat-copilot/assets/34857883/b612ce40-7860-4be5-b2bb-d5eab28b5f96)

 - OS: Ubuntu Ubuntu 20.04.6 LTS
 - Browser: Google Chrome

**Comment by momuno** [comment]
Please take a look at https://github.com/microsoft/chat-copilot#troubleshooting.  No. 3 covers Localhost SSL certificate errors / CORS errors and provides a solution.

**Comment by RuslanKain** [comment]
I tried the solution suggested in No. 3, however, it did not work for my situation. I think the issue comes from using a different port because I had something running on port 3000. So, I stopped what I had running there and ran the frontend on port 3000 and then it worked. Anyway, thank you!

**Comment by crickman** [comment]
Hi @RuslanKain - Since you've changed the front-end port, can you look at the appsettings.json under webapi and see if `AllowedOrigins` needs updating also (CORS):

```
  "AllowedOrigins": [
    "http://localhost:3000",
    "https://localhost:3000"
  ],```

**Comment by crickman** [comment]
`3000 `is generally the default port for react.  I guess I don't quite understand why this would vary.  Maybe you could try specifying it explicitly?

https://medium.com/@obieri.grace/a-simple-way-to-change-react-app-default-port-b8c32d8e0ef0

As a bothersome hack, you could start the `webapp `first...update the appsettings for the `webapi`, and then start that.

**Comment by selfishark** [comment]
> bothersome
https://github.com/microsoft/chat-copilot/issues/641#issuecomment-1837229867

Hello Everyone,

I find myself in the same situation (I don't have any other app running on the port) and while trying to implement the suggestion in your comment above it raised other questions: 

1. Could you please clarify the files that are impacted by the change of react default port, such as does the .env in the webapp folder needs updating too, if yes how, please? 

2. I tried to follow the setup of the webapp executing ```yarn build``` in the webapp folder, followed by ```yarn global add serve``` and ```serve -s build``` which allowed me to use ``` http://localhost:55193``` but still the same problem comes up.

![Screenshot 2023-12-07 014915](https://github.com/microsoft/chat-copilot/assets/105219120/efb52e58-81ae-4d7b-8e7c-d529a793e982)

Do you guys have solutions or workarounds for this, please? @RuslanKain @momuno

**Comment by pankajsurti** [comment]
I changed the PORT and did all the above recommended but never was able to get this issue resolved.

![image](https://github.com/microsoft/chat-copilot/assets/108044/a1c95632-4cd1-4b39-94d8-63749413215f)

**Comment by crickman** [comment]
> Hi all,
> 
> I managed to change the REACT default port in the package.json file, as pointed out by [the medium link above](https://medium.com/@obieri.grace/a-simple-way-to-change-react-app-default-port-b8c32d8e0ef0) see attachment.
> 
> I can now launch the webapp on the `http://localhost:3000/` the issue remains the same. I even allowed all the permissions on the page, but still nothing.
> 
> ![Screenshot 2023-12-08 014625](https://private-user-images.githubusercontent.com/105219120/288939643-c9eb8f3d-2d1b-4b2d-9dc3-79165057ac77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjIxNjEsIm5iZiI6MTcwMjY2MTg2MSwicGF0aCI6Ii8xMDUyMTkxMjAvMjg4OTM5NjQzLWM5ZWI4ZjNkLTJkMWItNGIyZC05ZGMzLTc5MTY1MDU3YWM3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxNzM3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjI3MTIzZjdhNTAyNWFjODAwZTY1NWYyODg2N2NhMzY4ZDhjMTliYzQ4MDYyMDEzZDcyMTUwM2QxNDNjNzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gkjx-XUBixnOvpTlHn-Px6VeBe-AsB5m4ijlIH1TGFw)

What happens when you manually navigate to `https://localhost:40443`?  If the front end isn't connecting, can you please validate that the webapi service is running.  Both services must be running locally, but it is unclear with the provided information what teh verified state of the webapi service might be.

**Comment by selfishark** [comment]
Thank you 

> > Hi all,
> > I managed to change the REACT default port in the package.json file, as pointed out by [the medium link above](https://medium.com/@obieri.grace/a-simple-way-to-change-react-app-default-port-b8c32d8e0ef0) see attachment.
> > I can now launch the webapp on the `http://localhost:3000/` the issue remains the same. I even allowed all the permissions on the page, but still nothing.
> > ![Screenshot 2023-12-08 014625](https://private-user-images.githubusercontent.com/105219120/288939643-c9eb8f3d-2d1b-4b2d-9dc3-79165057ac77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjIxNjEsIm5iZiI6MTcwMjY2MTg2MSwicGF0aCI6Ii8xMDUyMTkxMjAvMjg4OTM5NjQzLWM5ZWI4ZjNkLTJkMWItNGIyZC05ZGMzLTc5MTY1MDU3YWM3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxNzM3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjI3MTIzZjdhNTAyNWFjODAwZTY1NWYyODg2N2NhMzY4ZDhjMTliYzQ4MDYyMDEzZDcyMTUwM2QxNDNjNzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gkjx-XUBixnOvpTlHn-Px6VeBe-AsB5m4ijlIH1TGFw)
> 
> What happens when you manually navigate to `https://localhost:40443`? If the front end isn't connecting, can you please validate that the webapi service is running. Both services must be running locally, but it is unclear with the provided information what teh verified state of the webapi service might be.

Dear @crickman thank you for your reply.  

I believe I successfully run the webapi too, my ```https://localhost:40443/healthz``` respond : healthz and I can access ```https://localhost:40443/swagger/index.html``` successfully.
