### ISSUE TITLE
copilot

### ISSUE THREAD

**Issue by tanxiaoling1** [microsoft/chat-copilot#643]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by momuno** [comment]
Hi @tanxiaoling1 , I am closing this issue due to lack of relevancy.
