### ISSUE TITLE
Integration with Azure API Management

### ISSUE THREAD

**Issue by abKrazy** [microsoft/chat-copilot#644]
Many customers need to front AOAI with Azure API Mgmt to implement rate limiting, track per user token usage to implement chargebacks etc. This is a significant blocker for such customers in utilizing this quickstart. Are there plans to integrate APIM?

**Comment by momuno** [comment]
Hi @abKrazy, CC does not have integration support pre-coded for Azure API Management and there are no plans for the team to add it.  However, this is a great idea and we welcome PRs from the community that add features to CC!  Thank your for your question.
