### ISSUE TITLE
Custom Plugins not working

### ISSUE THREAD

**Issue by kuppan4109** [microsoft/chat-copilot#645]
After enabling plugins (tried with Klarna Shopping and my working custom plugin), and typing in the chat, chat will show this error

> Unable to generate bot response. Details: Error: 500: Microsoft.SemanticKernel.Diagnostics.SKException: AcquireExternalInformationAsync failed. ---> System.Collections.Generic.KeyNotFoundException: The given key 'stepsTaken' was not present in the dictionary. at System.Collections.Generic.Dictionary`2.get_Item(TKey key) at CopilotChat.WebApi.Plugins.Chat.ExternalInformationPlugin.RunStepwisePlannerAsync(String goal, SKContext context, CancellationToken cancellationToken) in D:\LLM Research\copilot_updated_latest\chat-copilot\webapi\Plugins\Chat\ExternalInformationPlugin.cs:line 229 at CopilotChat.WebApi.Plugins.Chat.ExternalInformationPlugin.InvokePlannerAsync(String userIntent, SKContext context, CancellationToken cancellationToken) in D:\LLM Research\copilot_updated_latest\chat-copilot\webapi\Plugins\Chat\ExternalInformationPlugin.cs:line 105 at CopilotChat.WebApi.Plugins.Chat.ChatPlugin.AcquireExternalInformationAsync(SKContext context, String userIntent, Int32 token...

**Reproduce**

1. Go to Plugins
2. Enable Klarna Shopping and your local plugin
3. Type message I'm looking for shoes, size 10 or question relevant to your plugin 
4. See error the above error

**Tried with different sets of behaviour**

1. Action Planner
2. Stepwise - ( Above error is taken when executing stepwise planner)
3. Sequential 

Observed same error with all planners

**Platform**

1. OS: Windows
4. IDE: VS Code
5. Language: C#,Custom plugin (Created with Python)
6. Source: Latest code as of this issue creation date.

Additional context

1. Running locally, with ./start.ps1

**Comment by momuno** [comment]
hi @kuppan4109 we are taking a look into this.  Thanks for bringing it up.

**Comment by glahaye** [comment]
@kuppan4109 Do you have the very latest version of the code.  A fix related to a similar issue went in yesterday. This might already be fixed!

If you have the latest code, let us know and we'll see what's going on.

**Comment by kuppan4109** [comment]
@glahaye, Have pulled the latest code from repository and tried executing but facing the same issues. 

> @kuppan4109 Do you have the very latest version of the code. A fix related to a similar issue went in yesterday. This might already be fixed!
> 
> If you have the latest code, let us know and we'll see what's going on.

**Comment by kuppan4109** [comment]
@glahaye , any updates on this?


> @glahaye, Have pulled the latest code from repository and tried executing but facing the same issues.
> 
> > @kuppan4109 Do you have the very latest version of the code. A fix related to a similar issue went in yesterday. This might already be fixed!
> > If you have the latest code, let us know and we'll see what's going on.

**Comment by rvermeire** [comment]
> I tried to test it using the [OpenAI FastAPI sample plugin ](https://github.com/Azure-Samples/openai-plugin-fastapi)(running as an API server), which works. However, when enabled I get the following error:
> 
> ```
> docker-chat-copilot-webapi-1  | fail: Microsoft.SemanticKernel.Kernel[0]
> docker-chat-copilot-webapi-1  |       Plugin SequentialPlanner_Excluded function funcba45b9f92f21439d8192e6337f66522c call fail during pipeline step 0 with error The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
> docker-chat-copilot-webapi-1  |       Status: 404 (Not Found)
> docker-chat-copilot-webapi-1  |       ErrorCode: DeploymentNotFound
> docker-chat-copilot-webapi-1  |
> docker-chat-copilot-webapi-1  |       Content:
> docker-chat-copilot-webapi-1  |       {"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}
> And: docker-chat-copilot-webapi-1  |       Semantic function SequentialPlanner_Excluded.func37fece6a35d3407e96cd04ed2e0de16e execution failed with error The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
> ```
> 
> Running CC in WSL/Docker and the FastAPI plugin. I do not get this error when the plugin is disabled.

This is a completely different error @kuppan4109 reported.

**Comment by Azzeo** [comment]
> rvermeire

You are right. I forgot to change the model to my custom deployment name in appsettings.json.

**Comment by crickman** [comment]
We are taking the SK RC1 package early next week which contains all sort of fixes and enhancements for plugins.  This _should_ address the (previously resported) issue with WebSearcher plugin and we will re-assess/validate the state of the plugin and planner ecosystem within chat-copilot at this time.

**Comment by madushann** [comment]
any update on this?

**Comment by samleegithub** [comment]
I'm getting the same problem.
