### ISSUE TITLE
How can I deploy with my own domain on IIS?

### ISSUE THREAD

**Issue by paraggin** [microsoft/chat-copilot#652]
We would like to deploy the project on IIS using a specified port and our own domain. Could you please provide detailed steps for this process? Additionally, we need clarification on whether the frontend and backend should run on the same port or have separate domains.

**Comment by glahaye** [comment]
Please see https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-8.0

By default, both the frontend and backend are served from the same port.  Although, if you prefer, you can host the static JS files at any other location than in the backend's wwwroot folder.
