### ISSUE TITLE
I configured the GPT432K with .\Configure.ps1, but when I asked, the answer was still GPT3, what do I need to change?

### ISSUE THREAD

**Issue by howard2019007** [microsoft/chat-copilot#657]
I configured the GPT432K with .\Configure.ps1, but when I asked, the answer was still GPT3, what do I need to change?
![image](https://github.com/microsoft/chat-copilot/assets/49265228/91f94021-8553-4654-adfe-b8b639a5c3bd)

**Comment by DarthCodingMaster** [comment]
Edit the value under Settings, Configuration of the WebApi service that you deployed to in the Azure Portal.

**Comment by howard2019007** [comment]
感谢，已经解决

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by crickman** [comment]
Had to pull out my translator.  Apologies for the late engagement and big thanks to @DarthCodingMaster for the community engagement!
