### ISSUE TITLE
The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

### ISSUE THREAD

**Issue by kjellmoens** [microsoft/chat-copilot#682]
**Describe the bug**
I receive the following error : The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

I configured the API with the following command

.\Configure.ps1 -EndPoint https://pronect-it-sam-lite-aoa.openai.azure.com -AIService AzureOpenAI -APIKey XXXXXXXXXX
which renders this output

The name of the deployment is pronect-it-sam-aoa-model

![image](https://github.com/microsoft/chat-copilot/assets/8494608/91efc152-0a72-4236-ba80-230edb130e22)

**To Reproduce**

**Screenshots**

![image](https://github.com/microsoft/chat-copilot/assets/8494608/5369fb86-2525-4523-91d8-c05cdddeac1f)

**Platform**
 - OS: Windows
 - Language: [e.g. C#, Python]
 
**Additional context**

**Comment by dehoward** [comment]
hi @kjellmoens, thanks for submitting this! I was able to find [another issue](https://github.com/microsoft/chat-copilot/issues/111) with this same error and the suggestion there was to make sure that you have the two required models installed (gpt-35-turbo and text-embedding-ada-002) deployed to your Azure Open AI.

if you have the models deployed as different names then you'll want to change the values in `main.bicep` or `main.json` depending on how you're deploying.

I also think I've seen this error when trying to deploy with the same name of a recently deleted deployment.

let me know if you're still running into this and we can debug further.

**Comment by EvangelosManavis** [comment]
@glahaye , how did you manage to solve it?

**Comment by glahaye** [comment]
@EvangelosManavis You just need to make sure that the deployment names in your settings (e.g. appsettings.json) match those in your AOAI instance!
