### ISSUE TITLE
Integration tests workflow pipeline issue

### ISSUE THREAD

**Issue by tushardhadiwal** [microsoft/chat-copilot#698]
**Describe the bug**
Hello,

I am having trouble setting up the copilot-run-integration-tests.yml GitHub actions pipelines in my fork for chat-copilot. 
Can you please point me to documentation or share some details on what should I set for values of these secrets? 
Should I create an app registration in Azure and create a dummy username and password that can be used for testing ?

https://github.com/microsoft/chat-copilot/blob/583f2c3a9280977c51ddd04bcfbc989427444b57/.github/workflows/copilot-run-integration-tests.yml#L32C1-L32C1

          TenantId: ${{ secrets.COPILOT_CHAT_TEST_TENANT_ID }}
          WebApiClientId: ${{ secrets.COPILOT_CHAT_TEST_APP_AAD_WEBAPI_CLIENT_ID }}
          WebAppClientId: ${{ secrets.COPILOT_CHAT_TEST_APP_AAD_WEBAPP_CLIENT_ID }}
          Username: ${{secrets.COPILOT_CHAT_TEST_USER_ACCOUNT1}}
          Password: ${{secrets.COPILOT_CHAT_TEST_USER_PASSWORD1}}

**To Reproduce**
1. Run copilot-run-integration-tests pipeline.

**Expected behavior**
Documentation or comments required to understand the expected values for secrets.

**Screenshots**

**Platform**
- Github actions
**Additional context**

**Comment by tushardhadiwal** [comment]
If I don't wish to put my own AAD credentials in secrets, is there a way to create a temporary user in the app registration that would work? What do you do ?

**Comment by dehoward** [comment]
@tushardhadiwal this is what we have done. we have a test user created that has access to the app. you should be able to [create a user](https://learn.microsoft.com/en-us/entra/fundamentals/add-users#add-a-new-user) under the same tenant and then use that user's credentials in in the secrets.
