### ISSUE TITLE
Chat copilot wont install on Azure cloud tenant

### ISSUE THREAD

**Issue by jackmealin** [microsoft/chat-copilot#699]
Sent: Tuesday, December 5, 2023 10:32 AM
Subject: RE: Quota request for Alerts - TrackingID#2312040030001003

 

Hi Michael,

 

This is Ying from Azure OpenAI support team. 

 

May I know the resource ID that you used to configure chat-copilot? 

 

Could you please raise a new issue through github: Issues · microsoft/chat-copilot · GitHub ? Engineers that supports this project will work on it.

 

Please feel free to contact me if you have any questions.

 

Best Regards,
Ying Zhang
Support Engineer | Azure AI/IoT Support Team                                      
Working Hours: Mon-Fri 9:00-18:00 (GMT+8)

 

 

------------------- Original Message -------------------
Received: Mon Dec 04 2023 13:57:25 GMT+0800 (China Standard Time)
Subject: Quota request for Alerts - TrackingID#2312040030001003

Hello Michael,

 

Thanks for contacting Microsoft Support! This is Chuck from APAC Azure Monitor & Automation team, and I will work with you on ticket # 2312040030001003. You can reach me using the contact information in my signature referencing support request ID # 2312040030001003.  

 

I called you over the phone a moment ago, but you might be busy so I'm writing you this email. 

 

I want to ensure I have a clear understanding of your situation, so please don't hesitate to correct me if I've misconstrued any details. 

 

Issue: 

Per the request, you received the following error when setting up Chat Copilot program from Github instructions.

 

{'code':'InvalidTemplateDeployment','details':[{'code':'InsufficientQuota','message':'Insufficient quota. Cannot create/update/move resource 'cog-ocr-copichat-zzywy3wzyhc56'.'}],'message':'The template deployment 'Microsoft.Template-20231204134345' is not valid according to the validation procedure. The tracking id is 'edfd27b7-4cde-4c4a-8d14-9d33b593aede'. See inner errors for details.'}

 

Initial Checking/Information: 

May I know the Github link/doc you followed to set up the Chat Copilot program? 

 

Unfortunately, the Monitor team has very limited knowledge on this subject, but rest assured I'll engage the related team to help once I have the Github link/doc from you. Sorry for the inconvenience caused. 

 

Please feel free to contact me anytime if you have anything that you would like to call out. I will always be here to support you. 

 

Thanks and look forward to hearing back from you! 

 

 

Best Regards,    

Che Li 

Azure Monitor & Automation 

Customer Service & Support       Mon-Fri 09:00-18:00 UTC+8 (China Standard Time) 

Contact https://support.microsoft.com/help/13948/global-customer-service-phone-numbers if any support needed. 

Delighting our customers is our #1 priority!

**Comment by threegitty350** [comment]
I don't know the policies of this group but you may want to remove all personal information in your original post (such as emails), I would request that you edit it as soon as you can.

"InvalidTemplateDeployment" likely means that you are trying to re-deploy to an existing resource group but it can't find the template name that you provided. You will need to go to your resource group and verify the name of the template that is there. Click on your resource group and then deployments. You will see a list of templates there. When you run the deploy to azure command, you will need to provide the correct template name.

**Comment by dehoward** [comment]
hi @jackmealin, thanks for submitting this. I see that you're getting an `InsufficientQuota` error for the Speech Services deployment, so I'm wondering if you have too many of those deployed given your subscription.

**Comment by jackmealin** [comment]
I am new to this, how do i check if I have already deployed that template?

**Comment by dehoward** [comment]
@jackmealin when going to your resource group you'll see the Deployments tab:
<img width="203" alt="image" src="https://github.com/microsoft/chat-copilot/assets/52973358/265163c9-32eb-4318-9f45-4a072744eb1e">

and then clicking on a deployment will show you the Template:
<img width="1061" alt="image" src="https://github.com/microsoft/chat-copilot/assets/52973358/f340863b-c4b2-416e-ba92-6145b97cd19c">

**Comment by ipac2** [comment]
![image](https://github.com/microsoft/chat-copilot/assets/48156727/3942afad-e4a1-4243-bdd2-3479dfaa7398)

This is the screen cap for the deployment script. It doenst look like there are any templates deployed to me....

**Comment by ipac2** [comment]
<img width="2130" alt="Chatcopilot screen cap" src="https://github.com/microsoft/chat-copilot/assets/48156727/c28ada70-368e-4c03-8558-b726701d8205">

This is the screen cap I have when I check the deployment, I am the original poster, just signed in with a different account.

**Comment by dehoward** [comment]
@ipac2 can you try a fresh deployment with a unique name to see if it fixes your issue? using either the Deploy to Azure button or the scripts mentioned in the [instructions](https://github.com/microsoft/chat-copilot/blob/main/scripts/deploy/README.md#deploying-chat-copilot).
