### ISSUE TITLE
Any user can delete chats in group chat

### ISSUE THREAD

**Issue by threegitty350** [microsoft/chat-copilot#704]
**Issue:**
Any user using group chat has permission to delete the chat making the chat unavailable for everyone.

**Frequency:**
Always

**Suggestion:**
Only the owner should be the one with this ability. Perhaps "guests" in the chat room should be able to leave instead?

**Comment by crickman** [comment]
Thank you for this suggestion.  Currently there is no concept of a chat owner.  I've flagged this as an issue for the team to review and address.

**Comment by evchaki** [comment]
We will not be currently adding additional functionality at this time.  You can fork the code and add a delete feature to remove the chat history from the database or local memory.
