### ISSUE TITLE
Unsuccessful Authentication when using Chat-Copilot in Docker - webpage at https://www.microsoft365.com/0?auth=1&client-request-id=... might be having issues or it may have moved permanently to a new web address.

### ISSUE THREAD

**Issue by selfishark** [microsoft/chat-copilot#719]
**Describe the bug**
There seem to be an issue when login in Chat-Copilot, using Docker. - With the new  repo update on Dec 9, 2023, I could install Chat-Copilot but could not log in on ``` localhost:3000``` it says the following (see screenshot). 

Besides the webapi seems to be unresponsive. It says HTTP ERROR 404 (see screenshot). 

Would you be able to point  me in the right direction, please? - What I am doing wrong? - Thank you in advance. 

**To Reproduce**
1. Go to the Docker Folder and run the ```docker-compose up --build``` as describe in the yaml file.
2. Start your docker once the build is complete (all the container are inside a unique main docker container)
- - chat-copilot-webapp : ```http://localhost:3000/```
- - chat-copilot-memory : ```http://localhost:3280/```
- - chat-copilot-webapi : ```http://localhost:3080/```
- - rabbitmq:management : ```http://localhost:15672/```
- - qdrant/qdrant : ```http://localhost:6333/```
- - web-search
4. Got to ```http://localhost:3000/``` and,
5. Connect with your Microsoft Account.

**Expected behavior**
I presume:
- the webapp should connect normally and redirect you to the localhost, but seem to happen.
- the webapi should show healthz when accessing: https://localhost:3080/healthz or we should be able to access  https://localhost:40443/swagger/index.html

**Screenshots**
webapp:
![Screenshot 2023-12-12 213834](https://github.com/microsoft/chat-copilot/assets/105219120/1df3f0e6-68c9-42d6-a7a2-c03abd316e0a)

webappi:
![Screenshot 2023-12-12 214433](https://github.com/microsoft/chat-copilot/assets/105219120/66b6aad8-3f1d-4526-b5e1-f6556079a460)

**Platform**
 - OS: Windows 11, 23H2
 - IDE: Visual Studio, VS Code, Docker Desktop
 - Language: Python
 - Source: https://github.com/microsoft/chat-copilot/commit/8e8e284f814e957070ec323dde8f847a1a48bcc2

**Additional context**
![Screenshot 2023-12-13 200954](https://github.com/microsoft/chat-copilot/assets/105219120/85284d90-5805-4d6f-8ac1-a47cda876c1e)

**Comment by win4r** [comment]
how to run it in docker?

**Comment by selfishark** [comment]
> how to run it in docker?

I tried to explain the steps I followed in the 'to reproduce' section in the issue description above. 

Unless you mean something else?

**Comment by glahaye** [comment]
@selfishark  I haven't been able to reproduce this with the latest version of the code.  Do you still get this problem?

**Comment by selfishark** [comment]
I have not tried since then.  Any suggestions ?

**Comment by selfishark** [comment]
> @selfishark  I haven't been able to reproduce this with the latest version of the code.  Do you still get this problem?

I have not tried since then. Any suggestions, please  ?

**Comment by glahaye** [comment]
@selfishark It should just work now.
