### ISSUE TITLE
Planner showing incorrect steps

### ISSUE THREAD

**Issue by saiabhilash** [microsoft/chat-copilot#754]
**Describe the bug**
Planner seems to be invoking Klarna plugin every time without depending on user query

**To Reproduce**
1. Without Klarna plugin enabled - **Query**: What is our galaxy name? **Answer:** The name of our galaxy is the Milky Way.
2. With Klarna plugin enabled - **Query**: What is our galaxy name?  **Answer:** Planner is showing the Klarna plugin. Screenshot attached.
![image](https://github.com/microsoft/chat-copilot/assets/5492462/cd009250-1754-412f-a71b-f711ba6b1830)

**Expected behavior**
Not sure how Klarna will help to determine the name of the galaxy? Also, if i enable another custom plugin along with Klarna, i see two  steps showing up (one from Klarna and another from custom plugin)

**Screenshots**
Attached screenshots in step 2

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: C#
 - Source: Latest repo
 - Using GPT 3.5 Turbo
 - Planner configuration in Appsettings.json (for webapi) 
![image](https://github.com/microsoft/chat-copilot/assets/5492462/1db63a6c-d80f-41ea-a8dd-1f9d7805a4df)

**Comment by evchaki** [comment]
@saiabhilash this should be working now, please try it again on the latest build.
