### ISSUE TITLE
Unable to get plugin to be used

### ISSUE THREAD

**Issue by mrochon** [microsoft/chat-copilot#760]
No matter how I modify the definition of my little plugin, I cannot get the Copilot to use it. I can Add and enable it. I just never see it used, displayed in plan. What am I missing?

**To Reproduce**
1. Add an enable plugin defined here: https://mraiplugins.azurewebsites.net/swagger/index.html
2. Tried prompts like 'Where can I fly to from Seattle?', 'Where does Alaska Airlines fly to from Seattle?'

**Expected behavior**
Show use of the plugin in plan displayed when prompt is entered

**Comment by damienaicheh** [comment]
Hi @mrochon I had the same problem and I found that I forget to define the **operationId** on my endpoint in my open api definition.
In csharp for instance I just had to put this anotation on top of my endpoint:

` [HttpGet("flight-discover", Name= "Flight discover by city")]`

It's the property `Name` which does the tricks.
