### ISSUE TITLE
SK 1.0.1

### ISSUE THREAD

**Issue by NicolasHumann** [microsoft/chat-copilot#761]
Hello, Any release date of copilot chat with SK 1.01?

**Comment by geffzhang** [comment]
https://github.com/microsoft/chat-copilot/pull/703

**Comment by philiphuynh-vlg** [comment]
> Update SK to 1.0.1 #703

When will this pull request be merged?
I'm waiting for the code to be upgraded to SK V1.01 to improve the planner.

**Comment by UTMark** [comment]
Same, looking forward to this implementation. :)

**Comment by evchaki** [comment]
This is now released to C# Kernel 1.0.4
