### ISSUE TITLE
Using a in a Javadoc question causes Copilot to close the topic

### ISSUE THREAD

**Issue by cowwoc** [microsoft/chat-copilot#775]
**Describe the bug**

**To Reproduce**
1. Go to https://www.bing.com/chat
2. Ask this question: `Clean up this Javadoc: The only time you should invoke this method is if the validator contains {@link Configuration#context() additional contextual information} that the built-in NullPointerException handler would not provide.`
3. See error

**Expected behavior**
I expect Copilot to revise the text for clarity

**Actual behavior**
"Hmm…let’s try a different topic. Sorry about that. What else is on your mind?"

**Screenshots**
N/A

**Platform**
 - OS: Windows
 - IDE: N/A
 - Language: Java
 - Source: N/A

**Additional Context**
Remove the hash (#) symbol results in a normal answer.

**Comment by evchaki** [comment]
@cowwoc this is the Chat Copilot example code for Semantic Kernel, not the Bing Chat Copilot.  Closing issue.
