### ISSUE TITLE
401 issue on /chats /info and /maintenanceStatus

### ISSUE THREAD

**Issue by skrishnagiri** [microsoft/chat-copilot#783]
On deployment, the landing page throws 401 errors on the above resources. Likely indicates a permissions issue, but I cannot figure out where and what needs to change.

**Comment by rajeshkumar1130** [comment]
@skrishnagiri 
I did following changes to get this app running
in MaintenanceMiddleware.cs changed IReadOnlyList to IEnumerable in line no 22 and 31
in ChatPlugin.cs line no 615 changed citationMap.Values to citationMap?.Values
in appsetting.json 
changed 
"SimpleVectorDb": {
  "StorageType": "Disk",
  "Directory": "../tmp/database"
}

to

 "SimpleVectorDb": {
   "StorageType": "Volatile",
   "Directory": "../tmp/database"
 },

updated apikey and orgid in 

 "OpenAI": {
   "TextModel": "gpt-3.5-turbo",
   "EmbeddingModel": "text-embedding-ada-002",
   //"APIKey": "", // dotnet user-secrets set "KernelMemory:Services:OpenAI:APIKey" "MY_OPENAI_KEY"
   "OrgId": "",
   "MaxRetries": 10
 },
