### ISSUE TITLE
Deploy webapi package that matches memories selection in ARM template

### ISSUE THREAD

**Issue by alliscode** [microsoft/chat-copilot#79]
Currently the Deploy to Azure buttons use an ARM template that defaults the memories selection to "Volatile" but does allow the user to change this to Qdrant or ACS. The problem is that the webapi package that is deployed is configured to use volatile memories and so changing this in the ARM deployment results in a resource that is deployed but is not being used.

One option to fix this is to publish webapi artifacts with all configurations in the pipeline, and then use the memories selection in the ARM template to pick the correct one.

**Comment by glahaye** [comment]
Spoke with @alliscode - The problem description does not actually occur.

Not a bug.
