### ISSUE TITLE
Is this repository still active?

### ISSUE THREAD

**Issue by NicolasHumann** [microsoft/chat-copilot#790]
Hello,

Could you please share if this project is still being actively maintained? 

Are there any future updates or roadmap items that you are considering at the moment? 

Thank you

**Comment by ezar** [comment]
Good question!

**Comment by lgmorand** [comment]
asking the same. just downloaded the sample, updated the packages and nothing builds correctly. I'll be noisy internally :)

**Comment by glahaye** [comment]
Hi all,

@NicolasHumann this project is no longer **actively** maintained. For reasons into which I don't have complete visibility, we're seeking to have another team take it over. In the meantime, the project is in limbo.

@lgmorand the project is currently not compatible with the latest versions of the SK libraries, as you discovered for yourself. Let me see if I can take some time to finish the migration of the code. In the meantime, revert the libraries to their former versions to get things going.

**Comment by lgmorand** [comment]
oh no :'( this project was so great

**Comment by dipteshbosedxc** [comment]
This Copilot app was such a nice way to visually test SK and Plugins. Any reason why this is not being maintained? At least keep a working version in the repo.

**Comment by lgmorand** [comment]
not a good news, but a GREAT news :D

**Comment by plabadaris** [comment]
Thanks for upgrading to SK 1.4
There is also a need to upgrade the semantic-kernels-starters repo.

**Comment by lgmorand** [comment]
once again, huge thanks @glahaye for the update

![respectez-deux-poings-avec-le-texte-respect-autocollant](https://github.com/microsoft/chat-copilot/assets/6757079/5c4a0182-2cac-47f2-a502-bca278c18e82)
