### ISSUE TITLE
Can we have Blazor(WASM or Server) version of this code.

### ISSUE THREAD

**Issue by nssidhu** [microsoft/chat-copilot#804]
We have under taken Tachnical stack simplication at our company and decided to use Blazor (both WAM & Server) for UI.
We don't have developers on team with React or other related skills.
It will be appreciated that if this application can be created in Blazor  and would like to know if there is any plans for this and if so when can we expect it ?

**Comment by evchaki** [comment]
@nssidhu we do not currently have any plans to convert this to Blazor.  However, you should be able to feed the repo into an AI Agent and see if it can convert the code to a Blazer app for you.
