### ISSUE TITLE
 "Insert into Notebook" in Github Copilot in VSCode is not converting response data correctly into separate Markdown and Code cells

### ISSUE THREAD

**Issue by TatianaPrevalla** [microsoft/chat-copilot#822]
**Describe the bug**
The function "Insert into Notebook" in Github Copilot in VSCode is not converting response data correctly into separate Markdown and Code cells before it sends it over the Jupyter Notebook. It is not clear whether the bug is in Copilot, VSCode, or Jupyter NB in VSCode. What VScode or Github Copilot configuration can I change to fix this?

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/microsoft/chat-copilot/assets/160190597/fdcab3e9-ddf9-429a-8fc6-eaddf6f77f27)

**Platform**  See screenshot !! 
 - OS: [Windows 11 Pro]
 - IDE: [VS Code]
 - Language: [Python]

**Additional context**

**Comment by evchaki** [comment]
@TatianaPrevalla this is not the GitHub Copilot repo.
