### ISSUE TITLE
MemoryPipeline and webapi not working in distributed mode using Qdrant and RabbitMQ

### ISSUE THREAD

**Issue by martinhosebastiao** [microsoft/chat-copilot#837]
When I make the settings in the **appsetting.jso**n of the two projects as indicated in the readme, I initialize the two projects, it is visible in the output that several exceptions are generated in both projects and does not create or register anything in the **collection** memory of the **qdrant** and the chat stops working, returning exception and unavailability of the backend. But I can see that there is a connection between the two projects and **RabbitMq**, despite the many exceptions.

I changed it to use **SimpleQueues**, **SimpleVectorDb** but it still doesn't work in a distributed way, the chat continues to show errors and the exceptions are visible. If I switch to Inprocess everything works normally.

Can you please help me to configure the distributed mode correctly or to correct this error?

**MemoryPipeline Outout**
<img width="522" alt="Captura de ecrã 2024-03-04 162750" src="https://github.com/microsoft/chat-copilot/assets/20699228/c4913b97-4a5d-4389-9ee5-c139f5f11b63">

**Chat-Copilot**
<img width="878" alt="Captura de ecrã 2024-03-04 163342" src="https://github.com/microsoft/chat-copilot/assets/20699228/a9f191bc-c3b7-4f25-8cf9-949cab9a5c29">

**Comment by aaronba** [comment]
Hey @martinhosebastiao ,

The error looks like the appsettings.json for the CopilotChatMemoryPipeline are not set correctly.
The error mentions that the AzureOpenAIEmbedding settings aren't referencing the correct "Deployment"

"AzureOpenAIEmbedding": {
  "Auth": "ApiKey",
  // "APIKey": "", // dotnet user-secrets set "SemanticMemory:Services:AzureOpenAIEmbedding:APIKey" "MY_AZUREOPENAI_KEY"
  "Endpoint": ".openai.azure.com/",
  "Deployment": "text-embedding-ada-002" // <--- check this value and compare with the Azure OpenAI Portal.
},

**Comment by glahaye** [comment]
I concur with aaronba.
