### ISSUE TITLE
Localhost refused to connect error - New Copilot Chat window did not come up

### ISSUE THREAD

**Issue by moushumig** [microsoft/chat-copilot#844]
**Describe the bug**
Followed the steps described in the https://github.com/microsoft/chat-copilot/blob/main/README.md to install the chat-copilot. 
1. https://[localhost:40443/healthz](https://localhost:40443/healthz) showed "Healthy"
2. My VPN was connected. 
3. Build was successful.
But http://[localhost](http://localhost:3000/):3000/ showed "localhost refused to connect". 

_A clear and concise description of what the bug is:_

It would be valuable to get some more details of the networking issue that is happening between the front end and the backend. This is the error that is currently provided.

"WARNING: TCP connect to (::1 : 40443) failed
WARNING: TCP connect to (127.0.0.1 : 40443) failed
*************************************************
Backend is not running and we have exceeded
the maximum number of retries.

Therefore, we are exiting.
*************************************************"

**To Reproduce**
Follow the steps in the readme provided above. I was installing on Windows Machine using VSCode and Powershell.

**Expected behavior**
A new window was supposed to come up a browser should automatically launch and navigate was the expected result. This didn't happen.

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac] : Windows
 - IDE: [e.g. Visual Studio, VS Code] : VS Code with Powershell
 - Language: [e.g. C#, Python] : Python
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository] Openai version ==1.2.0

**Additional context**
If you need more information please reach out to me.

**Comment by glahaye** [comment]
@moushumig  Do you have a .env file in the webapp folder?  What is its contents?

It should contain something like the following:
REACT_APP_BACKEND_URI=https://localhost:40443/
