### ISSUE TITLE
An error was encountered for the on-premises IIS deployment

### ISSUE THREAD

**Issue by howard2019007** [microsoft/chat-copilot#848]
![image](https://github.com/microsoft/chat-copilot/assets/49265228/ceb4914a-72f6-4ff7-9586-9428c8563073)
![image](https://github.com/microsoft/chat-copilot/assets/49265228/ecd81713-e07a-4421-a912-916aa140946a)

**Comment by evchaki** [comment]
@howard2019007 it looks like the web server did not start, make sure you follow the readme instructions here - https://github.com/microsoft/chat-copilot/blob/main/README.md
