### ISSUE TITLE
relevanceThreshold is not utilized preventing additional memory items

### ISSUE THREAD

**Issue by habanoz** [microsoft/chat-copilot#851]
**Describe the bug**
ISemanticMemoryClientExtensions.SearchMemoryAsync does not utilize relevanceThreshold parameter provided. As a result, memory check for similar items always returns the first inserted item and subsequent items are not added to the memory.  

**To Reproduce**
Chat using the UI and check for LongTermMemory and WorkingMemory. It does not accumulate. 

**Expected behavior**
Working and Long term memory should accommodate as chat history expands.

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/6825980/dbe92562-1896-4275-a219-3809dc406541)

**Comment by habanoz** [comment]
Would you like me to generate a PR?

**Comment by glahaye** [comment]
@habanoz Hi! Thanks for reporting this problem,

Yes, if you have code that fixes the issue, please send in a PR.

**Comment by habanoz** [comment]
> @habanoz Hi! Thanks for reporting this problem,
> 
> Yes, if you have code that fixes the issue, please send in a PR.

PR #920 is sent to fix the situation.

**Comment by habanoz** [comment]
PR is merged. Closing...
