### ISSUE TITLE
Rename everything from Skills -> Plugins

### ISSUE THREAD

**Issue by teresaqhoang** [microsoft/chat-copilot#86]
Since MS aligned on Plugins, we need to rename everything with "Skill" in it to "Plugin"

No dependency on core team but here's an item to track the work on their side: https://github.com/microsoft/semantic-kernel/issues/2119 
```[tasklist]
### Tasks
- [ ] Chat Copilot: Skill->Plugins
```

**Comment by hacker01111000** [comment]
Skills was a better name. 👎

**Comment by crickman** [comment]
I was kind've fond of `skill `as awell, but OpenAI has introduced a `plug-in` model and conflating the two terms is expexted to be a point of potential confusion.
