### ISSUE TITLE
how use chat-copilot  in china

### ISSUE THREAD

**Issue by kill136** [microsoft/chat-copilot#863]
in same reason，we cant  request open-ai  url，so we  need change httpclient BaseAddress 
i  change the code   in Program.cs，but  it did't work, why? what should i do?
  
![1710250984155](https://github.com/microsoft/chat-copilot/assets/22001343/82a8aaa1-8737-4698-b11c-b6ab5d349dc3)

**Comment by glahaye** [comment]
I am not sure I understand your problem.  Are you saying openai.com is blocked in China??

If you can't access openai.com, maybe you could try accessing the language models from Azure instead?
