### ISSUE TITLE
 GetUserIntentAsync failed. ---> Microsoft.SemanticKernel.HttpOperationException: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

### ISSUE THREAD

**Issue by EvangelosManavis** [microsoft/chat-copilot#865]
**Describe the bug**
I deployed locally the chat-copilot following the 3 steps of the [Microsoft documentation.](https://learn.microsoft.com/en-us/semantic-kernel/chat-copilot/getting-started?tabs=Windows%2CPowershell).

I configured the chat-copilot to use AzureOpenAI service (api key and endpoint are correct) 

While the deployment is successful, when i try to use the prompt i get the following error:
![image](https://github.com/microsoft/chat-copilot/assets/159045813/ea91782c-7b59-493f-bedb-5d13d8c1a678)

Any insights here?? 

Thank you.

**Comment by EvangelosManavis** [comment]
@tdechanterac thanks for your answer.  👍 👍 

Where could i found the AzureOpenAIText:Deployment and Planner:Model settings?

If this is problem indeed, the the Configure.ps1 script is buggy, because i am sure the the model name that i used is the correct one.

**Comment by tdechanterac** [comment]
You should have them in the `app.settings.development.json` file.
If I remember well the scripts have been modified a few weeks ago so it might be something to consider.

**Comment by tdechanterac** [comment]
@EvangelosManavis , i guess in my config its a relicate of the configuration i had before the SK 1.5 migration. So no big deal.
Glad it worked.
