### ISSUE TITLE
using it with an assistant model

### ISSUE THREAD

**Issue by msi-martinsen** [microsoft/chat-copilot#875]
Hi, would it be possible to use this with the latest assistant build of chatgpt-4 with the code-interpreter enabled? That would enable use of xlsx files and allows for creation of different graphs etc or should that be in a different chat-assistant project?

**Comment by glahaye** [comment]
Chat Copilot is now receiving only minimal support so I don't foresee it using assistant functionality.

Semantic Kernel does have examples close to what you are referring to (https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example75_AgentTools.cs), though.

@crickman might have more info on the subject.

**Comment by crickman** [comment]
Switching to use Assistant API is a big shift to the app in terms of additional storage management, etc...

I don't believe chat-copilot will handle image output either.
