### ISSUE TITLE
Explanation for this spaghetti code?

### ISSUE THREAD

**Issue by Porkechebure** [microsoft/chat-copilot#880]
Yeeah, all nice, let's release a ton of code with a small readme that talks mostly about what it uses, what are the problems and links some generic documents.

Let's completely oversight the explanation of the code and let programmer re read the whole code and guess what classes like volatilecontext or whatever else do.

Genius!

Goddamn you're (as Microsoft) releasing a dozen of AI project tied to semantic kernel and azure services and the DOCS SUCK.

Stop 1 month of developement and set everyone on docs, FFS!

Provide a decent doc for this now

I quickly checked the code and it's a jurily rigged togheter hack of react effects and stuff and lot of noisy code.

Get straight to the point and explain it

**Comment by sonphnt** [comment]
@Porkechebure This repo is not supposed to be used on Production as they mentioned

NOTE: This is a sample application to help you understand how Semantic Kernel and AI can work in Web Applications. This sample is NOT FOR PRODUCTION deployments.

So lack of docs can be sympathized. this repo is to help people understand AI, Semantic Kernel. This is not a repo to show how to use React which is a front-end framework in best practices.

For me, I build and run it successfully and understand how it works then I can just skip the Front-End part. Copy some Back-End code which is pretty good in my opinion into my SK project.
