### ISSUE TITLE
Plugins not working in West Europe

### ISSUE THREAD

**Issue by H-JonathanLoise** [microsoft/chat-copilot#901]
**Describe the bug**
I created a new plugin that needs to be invoked automatically thanks to ToolCallBehavior.AutoInvokeKernelFunctions.
When I use the AzureOpenAI in West Europe that invocation never work when I switch the endpoint to the East US 2 the invocation immediatly worked.

**To Reproduce**
1. Create a West Europe AzureOpenAI service
2. Create a gpt-35-turbo distribution and the ada distribution
3. Clone the chat-copilot project and set the endpoint and the key
4. Create a new plugin. I.E. a plugin to retrieve the business information
5. Try ask: give me the business information -> copilot will ask for more informations or say he don't know where to retrieve information
6. Create a East US 2 AzureOpenAI service
7. Create a gpt-35-turbo distribution and the ada distribution
8. Clone the chat-copilot project and set the endpoint and the key
9. Create a new plugin. I.E. a plugin to retrieve the business information
10. Try ask: give me the business information -> copilot will respond with the business information

**Platform**
 - Visual Studio 2022 community

**Comment by glahaye** [comment]
This sounds like it might be related to the specific version of the gpt-35-turbo deployment at the various data centers.

If you still have your environments up, can you check which versions are in both environments?

**Comment by H-JonathanLoise** [comment]
West Europe:
![image](https://github.com/microsoft/chat-copilot/assets/160387762/56430143-09af-4b9a-91c1-5fb2f6b13e06)

East US 2:
![image](https://github.com/microsoft/chat-copilot/assets/160387762/056b7478-d13b-4468-9605-d2193f5d5f5e)

**Comment by glahaye** [comment]
Yes, that confirms my suspicion. See how your model version in West Europe is 0301 and the one in East US 2 is 0613? You need version 0613 or higher.

I don't know exactly which distributions are present in each datacenter. 0613 might not have been rolled out to Western Europe yet.  You can try to create a new deployment in that datacenter and verify whether a model with version 0613 or higher is present.

**Comment by H-JonathanLoise** [comment]
Always the same deployment:

![image](https://github.com/microsoft/chat-copilot/assets/160387762/34ea85fa-017b-4703-826d-55449297c7ed)

Only the 0301 is present in west europe
![image](https://github.com/microsoft/chat-copilot/assets/160387762/4dc859b9-e076-4980-a235-a181a20a3dbf)

**Comment by glahaye** [comment]
I'm afraid then that you have to use another datacenter if you want to use gpt-35-turbo with automatic function calling. ☹️

Alternatively, if you really want to remain on Western Europe, you could check if they have another model (like gpt-4) that supports automatic function calling.

**Comment by H-JonathanLoise** [comment]
That's not a huge problem, gpt-4 is only available in East US 2.

I will continue to use the East US 2 until the West Europe will update their versions.

Regards,
Jonathan
