### ISSUE TITLE
document import not extracting knowledge

### ISSUE THREAD

**Issue by giannik** [microsoft/chat-copilot#91]
after importing a pdf document and asking it questions about the document it has no knowledge of the content in the pdf . Is this  still under development ? I am using qdrant for embeddings and no errors appear in console.

**Comment by glahaye** [comment]
@TaoChenOSU Mind taking a look?

**Comment by alliscode** [comment]
Hi @giannik, thank you for creating this issue! The effectiveness of the document memories depends on a lot of factors, and it can sometimes be challenging to get the results you expect. One thing you can try is to examine the prompt that was sent to the model by clicking the information button in the top right corner of the response message. In the example that I'm trying with [this document](https://www.lib.uidaho.edu/digital/objects/guidedreading/guidedread087.pdf), it looks like this:

![image](https://github.com/microsoft/chat-copilot/assets/25218250/85713181-4d43-4176-a788-5b2dc38c1ca6)

If the query resulted in a close enough match to the contents of the document, then within the prompt you should see a section for _Chat Memories_ that will contain snippets from the document. For my example, this is the top bit of what I see:

![image](https://github.com/microsoft/chat-copilot/assets/25218250/7bd89508-37d8-408f-8836-681c58ca70ec)

If you don't see any document snippets in the prompt then it likely means that the query did not match the document memories with a high enough relevancy. 

If you would like to look at and play with the code related to this, the code that handles chunking and importing documents is in [DocumentImportController.cs](https://github.com/microsoft/chat-copilot/blob/main/webapi/CopilotChat/Controllers/DocumentImportController.cs), and the code that handles extracting the document memories related to a query is in [ChatSkill.cs](https://github.com/microsoft/chat-copilot/blob/main/webapi/CopilotChat/Skills/ChatSkills/ChatSkill.cs).
