### ISSUE TITLE
How do I add support for csv, ppt, and support for other document types? 

### ISSUE THREAD

**Issue by Riya-Chaudhary-dev** [microsoft/chat-copilot#929]
How do I add support for csv, ppt, and support for other document types? Is there a need to update the how these documents are saved in storage and ai search?

**Comment by Riya-Chaudhary-dev** [comment]
How can I add access level for the documents that the user can query? I have a database that has access control based on the user, how do I implement this condition in the RAG mechanism?

**Comment by glahaye** [comment]
I would suggest using the Office Copilot for this.  Chat Copilot is just a simple demo and no plans exist to provide the functionality you require in it.
