### ISSUE TITLE
Unable to generate bot response. Details: Error: 500: Internal Server Error

### ISSUE THREAD

**Issue by Gayatrimurali** [microsoft/chat-copilot#930]
**Unable to generate bot response. Details: Error: 500: Internal Server Error**

**To Reproduce**
1. Go to 'https://aka.ms/sk-deploy-existing-azureopenai-portal'
2. Click on 'Create'
3. Browse the webapi app service

**Error**
Deployed the custom deployment as per the README file, deployment is getting succeeded after adding the values for openai endpoint, api key, app registrations client id and tenant id. We are accessing the webapi app service  and browsing the webapp. The chat copilot application is up and running but we are unable to receive a response from the bot when asked a question or when greeted.

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/139850907/0882d96a-6ab5-463f-add1-564e55f03489)

**Comment by glahaye** [comment]
This should be fixed now.  Give it another spin!
