### ISSUE TITLE
Conflict between appsettings and code

### ISSUE THREAD

**Issue by stephaneey** [microsoft/chat-copilot#941]
**Describe the bug**
In the apssettings, you refer to **AzureFormRecognizer** but in the code, precisely in the following method:

```
private void ConfigureImageOCR(IKernelMemoryBuilder builder)
{
    // Image OCR
    switch (this._memoryConfiguration.DataIngestion.ImageOcrType)
    {
        case string y when string.IsNullOrWhiteSpace(y):

        case string x when x.Equals("None", StringComparison.OrdinalIgnoreCase):
            break;        

        case string x when x.Equals("AzureAIDocIntel", StringComparison.OrdinalIgnoreCase):
            builder.Services.AddAzureAIDocIntel(this.GetServiceConfig<AzureAIDocIntelConfig>("AzureAIDocIntel"));
            break;

        default:
            // NOOP - allow custom implementations, via WithCustomImageOCR()
            break;
    }
}
```
You refer to **AzureAIDocIntel**, so configuring **ImageOcrType** to **AzureFormRecognizer** leads to an exception (non-configured ocr extraction). Appsettings should suggest:

- to specify AzureAIDocIntel instead of AzureFormRecognizer for the ImageOcrType setting
- to substitute AzureFormRecognizer section by AzureAIDocIntel 

**To Reproduce**
1. Configure ImageOcrType to AzureFormRecognizer 
2. Define APIKey and Endpoint in AzureFormRecognizer  section
3. Run it, upload a PNG in the chat and boom.

**Comment by glahaye** [comment]
Fixed with #1007 

Thanks for bringing this up!
