### ISSUE TITLE
ChatPlugin crashes on Azure OpenAI gpt-35-turbo 1106

### ISSUE THREAD

**Issue by Agazoth** [microsoft/chat-copilot#947]
**Describe the bug**
When running the app with Azure OpenAI gpt-35-turbo model 1106, the GetStreamingChatMessageContentsAsync stream throws an error when executed in 657-661.

**To Reproduce**
1: Add ```Console.WriteLine("Content piece: " + contentPiece);``` in line 659
2: Add ```var kernel = this._kernel; in line 639
3: Set a breakpoint at ```var chatMessage = await this.CreateBotMessageOnClient(```
4: Ask something in the app. 
5: Examine kernel.Plugins. It should hold 2 plugins, ChatPlugin and TimePlugin
![image](https://github.com/microsoft/chat-copilot/assets/15127301/c6014968-a3db-4ece-902a-9d9563c457b8)

6: Press continue and examine Output

**Expected behavior**
A Chat completion should start streaming to the chat window

**Screenshots**
With gpt-35-turbo we see this error:
![image](https://github.com/microsoft/chat-copilot/assets/15127301/65e83891-5354-48da-972f-bd7ea6162628)

With gpt-4 the code runs as expected:
![image](https://github.com/microsoft/chat-copilot/assets/15127301/6a53d07d-c909-444d-b497-37035c62ec10)

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: The current ChatCopilot projects sources. 

**Additional context**
We have been running gpt-4 for a long time now. We are currently investigating implementing a solution that allows switching between gpt versions. This is when we stumbled on this issue. 

When running gpt-35-turbo it seems we get a infinite recursion, if we start streaming with the ChatPlugin in the kernel. We have found that removing ChatPlugin from the kernel works with both gpt-4 and gpt-35-turbo and updated the code like this:
```dotnet
        var chatHistory = prompt.MetaPromptTemplate;
        var executionSettings = this.CreateChatRequestSettings();
        var kernel = this._kernel;
        var token = cts.Token;
        // Remove the ChatPlugin from the kernel to avoid infinite recursion in gpt-35
        var forRemoval = kernel.Plugins.Where(predicate: item => item.Name.Equals("ChatPlugin", StringComparison.Ordinal)).First();
        kernel.Plugins.Remove(forRemoval);

        var stream =
            chatCompletion.GetStreamingChatMessageContentsAsync(
                chatHistory,
                executionSettings,
                kernel,
                token);
```

We have tested in older branches and found, that Microsoft.SemanticKernel 1.3.0 and all the packages with it do not exhibit this error, but 1.5.0 up till 1.8.0 (what we use currently) has this issue.

**Comment by tdechanterac** [comment]
I've encountered the same issue as you. 
After some digging, it seems the problem lies with the return from GPT 3.5 turbo API. The chatplugin is consistently included in the functions to be used returned by GPT 3.5 turbo, leading to recursion.

Unfortunately, I haven't found a solution beyond what you've already attempted.

**Comment by Agazoth** [comment]
@tdechanterac did you also have this issue on Microsoft.SemanticKernel 1.3.0? On our environment Microsoft.SemanticKernel 1.3.0 did not produce the recursion

**Comment by Agazoth** [comment]
My thoughts exactly 😉
