### ISSUE TITLE
ServiceOptionsController return all service options from a single request

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/chat-copilot#95]
Currently the ServiceOptionsController has separate APIs for each option. It'd be nice to have one API that returns all the options, reducing the number of requests required.

Note: the current implementation only has memories store type because that is the only requested option to show in the webapp. In the future if we desire to show more options, we should combine things in a single API and a single response model.

**Comment by dehoward** [comment]
closing as this was addressed in #82
