### ISSUE TITLE
Power Platform Chatbot Copilot Studio: Issue with publishing Copilots

### ISSUE THREAD

**Issue by dhaneshpmenon** [microsoft/chat-copilot#966]
**Describe the bug**

Our copilots are taking forever to publish the chatbot, and it keeps spinning, stating that it is publishing. Is there any way to stop or reset it?

![Publish Issue](https://github.com/microsoft/chat-copilot/assets/118192568/b5d7e7dd-3a90-4648-ad79-decadf9d565b)

**Comment by glahaye** [comment]
Chat Copilot is NOT related to Microsoft Copilot.  They are different projects.
