### ISSUE TITLE
After running the memory pipeline, it keeps throwing an error: 'File not found: chatmemory/{GUID}/__pipeline_status.json

### ISSUE THREAD

**Issue by glenq** [microsoft/chat-copilot#970]
## Backgroud
- I'm running the memory pipeline according to the [webapi README](https://github.com/microsoft/chat-copilot/blob/main/webapi/README.md) and the [memory pipeline README](https://github.com/microsoft/chat-copilot/blob/main/memorypipeline/README.md).
- I'm using **AzureBlobs**, **AzureQueue**, **AzureAISearch**, **AzureOpenAI** services for chat-copilot and memory pipeline.
- I have created Azure AI Search **Indexs** according to this git issue: https://github.com/microsoft/chat-copilot/issues/958

## Question & Abnormal manifestations
- The memory pipeline **Console** keeps throwing error: `Pipeline 'xxx' not found, cancelling step 'extract'`
- The chat copilot **Console** keeps throwing error:` File not found, chatmemory/{GUID}/__pipeline_status.json`
   > However, in fact, the files do exist.
- The chat copilot front page keeps showing status: `Generating semantic chat memory...`

### Question：
The `Generating semantic chat memory...` status will keep showing for **very long time**(almost 15 mins) after running the memory pipeline(it only take 1 mins when run in `InProcess` type). Is there anyting wrong or what I can do to make it more quickly? Is there any configuration I need to check?

## Details:
- Error message in Debug cosole
![image](https://github.com/microsoft/chat-copilot/assets/17242230/885e83d9-bc5f-4a13-91f0-8aa4abdfbc7b)
- Front page keeps showing status
![image](https://github.com/microsoft/chat-copilot/assets/17242230/6fcbb7ca-ec58-4746-95e4-11ee6ca167f4)
- The pipeline status JSON files **exist** in Blob Storage, for example: 
![image](https://github.com/microsoft/chat-copilot/assets/17242230/ac511862-6c1e-46c2-afc6-d708babf6b8d)

**Comment by Dikarabo-Molele** [comment]
I found the issue to be in the settings set in CopilotChatMemoryPipeline. I resolved the issue by changing AzureBlobs:Container value to "chatmemory" 

Just make sure that the values are aligned between CopilotChatMemoryPipeline and CopilotChatWebApi
```json 
AzureBlobs": {
  "Auth": "ConnectionString","MY_AZUREBLOB_CONNECTIONSTRING"
  "Container": "chatmemory"
}

**Comment by glahaye** [comment]
Thanks for bringing this up.  @Dikarabo-Molele is right. I've change the default in memorypipeline to match webapi's.
