### ISSUE TITLE
tenant ID not documented or used in configure script

### ISSUE THREAD

**Issue by eugyev** [microsoft/chat-copilot#99]
**Describe the bug**

**To Reproduce**
1. Go to 'configure.sh' step in setup
2. the script accepts --tenantid as a parameter for setting up with Azure AD on a single enterprise.  It's in the script though not documented in readme.  on line 105 it then sets tenant ID to a default value if none is given (env_tenant_id).  on line 156 it should be using the tenant_id variable, not ENV_TENANT_ID.  this way if one is passed it, it is passed to the env file. 

Readme should get updated for single tenant deployment as an option as well.

**Comment by alliscode** [comment]
@eugyev thank you for bringing this to our attention! @momuno  and @glahaye will take a look at this.

**Comment by momuno** [comment]
Great find! Thank you @eugyev.  I'm in process of fixing the issue.

**Comment by glahaye** [comment]
Fixed with #104 - Thanks!
