### ISSUE TITLE
Getting 404 - Ressource not found

### ISSUE THREAD

**Issue by stepro71** [microsoft/chat-copilot#995]
I am using Azure Open AI. I take Endpoint and Key from "Keys and Endpoint" and use this in Configure.ps1. I have tried with and without completion model parameter. In chat copilot web-app I get error 500 and "the api deployment for this ressource does not exist." I am sure I am missing something simple, but I cannot figure it out.
Best Regards!

**Comment by glahaye** [comment]
You need to deploy a model to your Azure Open AI account.  Did you do that? It's name is then to be used as the completion model parameter.  Likewise for the embedding model.

**Comment by capesean** [comment]
you need to provide a deployment for both AzureOpenAIText and AzureOpenAIEmbedding, i.e. CompletionModel and EmbeddingModel in the Configure.ps1. The EmbeddingModel seems to be used for accessing memory during chats, so although you might think it's not necessary for straight chat, unfortunately it seems like it is required.
